// =====================================================================
// @generated
// THIS FILE IS AUTO-GENERATED by scripts/generate-session-paths.ts
// DO NOT EDIT BY HAND. Edits will be lost on next regeneration.
// Generator input: src/calculator/simple-despatch-types.ts (SimpleDespatchInput)
// Manual entries: (none)
// Read-only paths: (none)
// =====================================================================
//
// DespatchSessionPaths — path-based update API için tip-güvenli path map (AR-10).
// Mimsoft form akışında her field için `session.update(DespatchSessionPaths.X, value)` çağrısında kullanılır.
//
// Path syntax: bracket notation (örn: 'lines[0].quantity') — kütüphanedeki tüm
// validator'lar bu formatta ValidationError.path üretir, reactive session aynı convention'ı taşır.
//
// Generic tip türetimi: `DespatchSessionPathMap` ile `update<P extends keyof DespatchSessionPathMap>(path: P, value: DespatchSessionPathMap[P])`
// imzası compile-time tip kontrolü sağlar.


export const DespatchSessionPaths = {
  /**
   * Vergi kimlik numarası (10 hane VKN veya 11 hane TCKN) — zorunlu
   * Expected type: string
   */
  senderTaxNumber: 'sender.taxNumber',

  /**
   * Firma adı veya kişi adı soyadı — zorunlu
   * Expected type: string
   */
  senderName: 'sender.name',

  /**
   * Vergi dairesi — VKN için zorunlu, TCKN için opsiyonel
   * Expected type: string | undefined
   */
  senderTaxOffice: 'sender.taxOffice',

  /**
   * Adres — zorunlu
   * Expected type: string
   */
  senderAddress: 'sender.address',

  /**
   * İlçe — zorunlu
   * Expected type: string
   */
  senderDistrict: 'sender.district',

  /**
   * İl — zorunlu
   * Expected type: string
   */
  senderCity: 'sender.city',

  /**
   * Ülke — varsayılan: "Türkiye"
   * Expected type: string | undefined
   */
  senderCountry: 'sender.country',

  /**
   * Posta kodu — varsayılan: "00000"
   * Expected type: string | undefined
   */
  senderZipCode: 'sender.zipCode',

  /**
   * Telefon
   * Expected type: string | undefined
   */
  senderPhone: 'sender.phone',

  /**
   * E-posta
   * Expected type: string | undefined
   */
  senderEmail: 'sender.email',

  /**
   * Web sitesi
   * Expected type: string | undefined
   */
  senderWebsite: 'sender.website',

  /**
   * Tanımlama şema tipi (ör: "MERSISNO", "TICARETSICILNO", "HIZMETNO", "MUSTERINO", "TESISATNO")
   * Expected type: string
   */
  senderIdentificationSchemeId: (i: number) => `sender.identifications[${i}].schemeId` as `sender.identifications[${number}].schemeId`,

  /**
   * Tanımlama değeri
   * Expected type: string
   */
  senderIdentificationValue: (i: number) => `sender.identifications[${i}].value` as `sender.identifications[${number}].value`,

  /**
   * e-Fatura posta kutusu etiketi (ör: "urn:mail:defaultpk@firma.com.tr"). ⚠️ **Bu alan üretilen UBL-TR Invoice XML'ine YAZILMAZ — bilerek.** Etiket, faturanın kendisine değil **zarfa** (GİB e-Fatura Paketi SBDH: `<sender identifier="..." alias="urn:mail:..."/>` / `<receiver identifier="..." alias="..."/>`) aittir. GİB UBL-TR 1.2.1 `PartyType`'ında etiket için tanımlı bir eleman yoktur; `cbc:EndpointID` şemada bulunsa da UBL-TR kılavuzunda bu amaçla kullanılmaz, dolayısıyla oraya yazmak standart dışı olurdu. e-Arşiv faturalarında etiket kavramı hiç yoktur. Zarf üretimi kütüphanenin sorumluluk sınırının dışındadır (aynı sınır UBLExtensions/imza için de geçerlidir — bkz. B-101). Etiketi entegratöre gönderirken zarf tarafında siz taşımalısınız; alan burada yalnızca çağıranın veri modelini tek yerde tutabilmesi için durur (B-102 denetimi).
   * Expected type: string | undefined
   */
  senderAlias: 'sender.alias',

  /**
   * Vergi kimlik numarası (10 hane VKN veya 11 hane TCKN) — zorunlu
   * Expected type: string
   */
  customerTaxNumber: 'customer.taxNumber',

  /**
   * Firma adı veya kişi adı soyadı — zorunlu
   * Expected type: string
   */
  customerName: 'customer.name',

  /**
   * Vergi dairesi — VKN için zorunlu, TCKN için opsiyonel
   * Expected type: string | undefined
   */
  customerTaxOffice: 'customer.taxOffice',

  /**
   * Adres — zorunlu
   * Expected type: string
   */
  customerAddress: 'customer.address',

  /**
   * İlçe — zorunlu
   * Expected type: string
   */
  customerDistrict: 'customer.district',

  /**
   * İl — zorunlu
   * Expected type: string
   */
  customerCity: 'customer.city',

  /**
   * Ülke — varsayılan: "Türkiye"
   * Expected type: string | undefined
   */
  customerCountry: 'customer.country',

  /**
   * Posta kodu — varsayılan: "00000"
   * Expected type: string | undefined
   */
  customerZipCode: 'customer.zipCode',

  /**
   * Telefon
   * Expected type: string | undefined
   */
  customerPhone: 'customer.phone',

  /**
   * E-posta
   * Expected type: string | undefined
   */
  customerEmail: 'customer.email',

  /**
   * Web sitesi
   * Expected type: string | undefined
   */
  customerWebsite: 'customer.website',

  /**
   * Tanımlama şema tipi (ör: "MERSISNO", "TICARETSICILNO", "HIZMETNO", "MUSTERINO", "TESISATNO")
   * Expected type: string
   */
  customerIdentificationSchemeId: (i: number) => `customer.identifications[${i}].schemeId` as `customer.identifications[${number}].schemeId`,

  /**
   * Tanımlama değeri
   * Expected type: string
   */
  customerIdentificationValue: (i: number) => `customer.identifications[${i}].value` as `customer.identifications[${number}].value`,

  /**
   * e-Fatura posta kutusu etiketi (ör: "urn:mail:defaultpk@firma.com.tr"). ⚠️ **Bu alan üretilen UBL-TR Invoice XML'ine YAZILMAZ — bilerek.** Etiket, faturanın kendisine değil **zarfa** (GİB e-Fatura Paketi SBDH: `<sender identifier="..." alias="urn:mail:..."/>` / `<receiver identifier="..." alias="..."/>`) aittir. GİB UBL-TR 1.2.1 `PartyType`'ında etiket için tanımlı bir eleman yoktur; `cbc:EndpointID` şemada bulunsa da UBL-TR kılavuzunda bu amaçla kullanılmaz, dolayısıyla oraya yazmak standart dışı olurdu. e-Arşiv faturalarında etiket kavramı hiç yoktur. Zarf üretimi kütüphanenin sorumluluk sınırının dışındadır (aynı sınır UBLExtensions/imza için de geçerlidir — bkz. B-101). Etiketi entegratöre gönderirken zarf tarafında siz taşımalısınız; alan burada yalnızca çağıranın veri modelini tek yerde tutabilmesi için durur (B-102 denetimi).
   * Expected type: string | undefined
   */
  customerAlias: 'customer.alias',

  /**
   * Fiili sevk anı — `ActualDespatchDate` + `ActualDespatchTime`. `datetime` gibi TEK alandır, SDK böler. 🔴 Fiili sevk anı, düzenleme anından ÖNCE OLAMAZ (Uygulama Kılavuzu §10). İleri tarih serbesttir. Tek istisna MATBUDAN dönüşümüdür.
   * Expected type: string
   */
  shipmentActualDespatchDatetime: 'shipment.actualDespatchDatetime',

  /**
   * Açık adres — zorunlu
   * Expected type: string
   */
  shipmentDeliveryAddressAddress: 'shipment.deliveryAddress.address',

  /**
   * İlçe — zorunlu (`CitySubdivisionName`)
   * Expected type: string
   */
  shipmentDeliveryAddressDistrict: 'shipment.deliveryAddress.district',

  /**
   * İl — zorunlu (`CityName`)
   * Expected type: string
   */
  shipmentDeliveryAddressCity: 'shipment.deliveryAddress.city',

  /**
   * Ülke — varsayılan: "Türkiye"
   * Expected type: string | undefined
   */
  shipmentDeliveryAddressCountry: 'shipment.deliveryAddress.country',

  /**
   * Posta kodu — zorunlu. 🔴 Şematron TR biçimini KOŞULSUZ dayatır (`^((0[1-9])|([1-7][0-9])|(8[0-1]))[0-9]{3}$`), ülke ayrımı YAPMAZ. Yurt dışı teslimat adresi bu kapıyı geçemez — ihracat e-İrsaliyesi bu sürümde KAPSAM DIŞIDIR.
   * Expected type: string
   */
  shipmentDeliveryAddressZipCode: 'shipment.deliveryAddress.zipCode',

  /**
   * Ad — zorunlu
   * Expected type: string
   */
  shipmentDriverFirstName: (i: number) => `shipment.drivers[${i}].firstName` as `shipment.drivers[${number}].firstName`,

  /**
   * Soyad — zorunlu
   * Expected type: string
   */
  shipmentDriverFamilyName: (i: number) => `shipment.drivers[${i}].familyName` as `shipment.drivers[${number}].familyName`,

  /**
   * TCKN — zorunlu. Yabancı uyruklu şoförde pasaport numarası (e-İrsaliye Uygulama Kılavuzu §15.34: dolgu numara YASAK, UETDS bildirimiyle eşleşmek zorunda).
   * Expected type: string
   */
  shipmentDriverNationalityId: (i: number) => `shipment.drivers[${i}].nationalityId` as `shipment.drivers[${number}].nationalityId`,

  /**
   * Vergi kimlik numarası (10 hane VKN veya 11 hane TCKN) — zorunlu
   * Expected type: string
   */
  shipmentCarrierTaxNumber: 'shipment.carrier.taxNumber',

  /**
   * Firma adı veya kişi adı soyadı — zorunlu
   * Expected type: string
   */
  shipmentCarrierName: 'shipment.carrier.name',

  /**
   * Vergi dairesi — VKN için zorunlu, TCKN için opsiyonel
   * Expected type: string | undefined
   */
  shipmentCarrierTaxOffice: 'shipment.carrier.taxOffice',

  /**
   * Adres — zorunlu
   * Expected type: string
   */
  shipmentCarrierAddress: 'shipment.carrier.address',

  /**
   * İlçe — zorunlu
   * Expected type: string
   */
  shipmentCarrierDistrict: 'shipment.carrier.district',

  /**
   * İl — zorunlu
   * Expected type: string
   */
  shipmentCarrierCity: 'shipment.carrier.city',

  /**
   * Ülke — varsayılan: "Türkiye"
   * Expected type: string | undefined
   */
  shipmentCarrierCountry: 'shipment.carrier.country',

  /**
   * Posta kodu — varsayılan: "00000"
   * Expected type: string | undefined
   */
  shipmentCarrierZipCode: 'shipment.carrier.zipCode',

  /**
   * Telefon
   * Expected type: string | undefined
   */
  shipmentCarrierPhone: 'shipment.carrier.phone',

  /**
   * E-posta
   * Expected type: string | undefined
   */
  shipmentCarrierEmail: 'shipment.carrier.email',

  /**
   * Web sitesi
   * Expected type: string | undefined
   */
  shipmentCarrierWebsite: 'shipment.carrier.website',

  /**
   * Tanımlama şema tipi (ör: "MERSISNO", "TICARETSICILNO", "HIZMETNO", "MUSTERINO", "TESISATNO")
   * Expected type: string
   */
  shipmentCarrierIdentificationSchemeId: (i: number) => `shipment.carrier.identifications[${i}].schemeId` as `shipment.carrier.identifications[${number}].schemeId`,

  /**
   * Tanımlama değeri
   * Expected type: string
   */
  shipmentCarrierIdentificationValue: (i: number) => `shipment.carrier.identifications[${i}].value` as `shipment.carrier.identifications[${number}].value`,

  /**
   * e-Fatura posta kutusu etiketi (ör: "urn:mail:defaultpk@firma.com.tr"). ⚠️ **Bu alan üretilen UBL-TR Invoice XML'ine YAZILMAZ — bilerek.** Etiket, faturanın kendisine değil **zarfa** (GİB e-Fatura Paketi SBDH: `<sender identifier="..." alias="urn:mail:..."/>` / `<receiver identifier="..." alias="..."/>`) aittir. GİB UBL-TR 1.2.1 `PartyType`'ında etiket için tanımlı bir eleman yoktur; `cbc:EndpointID` şemada bulunsa da UBL-TR kılavuzunda bu amaçla kullanılmaz, dolayısıyla oraya yazmak standart dışı olurdu. e-Arşiv faturalarında etiket kavramı hiç yoktur. Zarf üretimi kütüphanenin sorumluluk sınırının dışındadır (aynı sınır UBLExtensions/imza için de geçerlidir — bkz. B-101). Etiketi entegratöre gönderirken zarf tarafında siz taşımalısınız; alan burada yalnızca çağıranın veri modelini tek yerde tutabilmesi için durur (B-102 denetimi).
   * Expected type: string | undefined
   */
  shipmentCarrierAlias: 'shipment.carrier.alias',

  /**
   * Plaka metni
   * Expected type: string
   */
  shipmentLicensePlateValue: (i: number) => `shipment.licensePlates[${i}].value` as `shipment.licensePlates[${number}].value`,

  /**
   * Şema — varsayılan: "PLAKA"
   * Expected type: 'PLAKA' | 'DORSE' | 'DORSEPLAKA' | 'YABANCIPLAKA' | 'YABANCIDORSE' | 'YABANCIDORSEPLAKA' | undefined
   */
  shipmentLicensePlateScheme: (i: number) => `shipment.licensePlates[${i}].scheme` as `shipment.licensePlates[${number}].scheme`,

  /**
   * Sevkiyat numarası — `Shipment/ID`
   * Expected type: string | undefined
   */
  shipmentShipmentId: 'shipment.shipmentId',

  /**
   * Taşınan malın beyan değeri — irsaliyedeki TEK tutar alanı
   * Expected type: number | undefined
   */
  shipmentGoodsValue: 'shipment.goodsValue',

  /**
   * Beyan değerinin para birimi — varsayılan: "TRY"
   * Expected type: string | undefined
   */
  shipmentGoodsValueCurrency: 'shipment.goodsValueCurrency',

  /**
   * Mal/hizmet adı — zorunlu (`ItemNameCheck`)
   * Expected type: string
   */
  lineName: (i: number) => `lines[${i}].name` as `lines[${number}].name`,

  /**
   * Sevk edilen miktar — zorunlu (`DeliveredQuantityCheck`)
   * Expected type: number
   */
  lineQuantity: (i: number) => `lines[${i}].quantity` as `lines[${number}].quantity`,

  /**
   * Birim kodu (UN/ECE Rec20) — zorunlu
   * Expected type: string
   */
  lineUnitCode: (i: number) => `lines[${i}].unitCode` as `lines[${number}].unitCode`,

  /**
   * Açıklama
   * Expected type: string | undefined
   */
  lineDescription: (i: number) => `lines[${i}].description` as `lines[${number}].description`,

  /**
   * Şema: "KUNYENO" (HKS, 19 karakter) / "ETIKETNO" (İDİS, 9 karakter) vb.
   * Expected type: string
   */
  lineAdditionalIdentificationScheme: (i: number, ti: number) => `lines[${i}].additionalIdentifications[${ti}].scheme` as `lines[${number}].additionalIdentifications[${number}].scheme`,

  /**
   * Değer
   * Expected type: string
   */
  lineAdditionalIdentificationValue: (i: number, ti: number) => `lines[${i}].additionalIdentifications[${ti}].value` as `lines[${number}].additionalIdentifications[${number}].value`,

  /**
   * Satır notu
   * Expected type: string | undefined
   */
  lineNote: (i: number) => `lines[${i}].note` as `lines[${number}].note`,

  /**
   * İrsaliye numarası (16 hane). Verilmezse çağıran/seri motoru doldurur.
   * Expected type: string | undefined
   */
  id: 'id',

  /**
   * ETTN. Verilmezse üretilir.
   * Expected type: string | undefined
   */
  uuid: 'uuid',

  /**
   * Düzenleme anı — SDK `issueDate` + `issueTime`e böler. Varsayılan: şimdi.
   * Expected type: string | undefined
   */
  datetime: 'datetime',

  /**
   * İrsaliye tipi: "SEVK" | "MATBUDAN" — varsayılan: "SEVK"
   * Expected type: string | undefined
   */
  type: 'type',

  /**
   * Profil: "TEMELIRSALIYE" | "HKSIRSALIYE" | "IDISIRSALIYE" — varsayılan: "TEMELIRSALIYE"
   * Expected type: string | undefined
   */
  profile: 'profile',

  /**
   * Notlar
   * Expected type: string[] | undefined
   */
  notes: 'notes',

  /**
   * Sipariş numarası
   * Expected type: string
   */
  orderReferenceId: (i: number) => `orderReferences[${i}].id` as `orderReferences[${number}].id`,

  /**
   * Sipariş tarihi (YYYY-MM-DD)
   * Expected type: string | undefined
   */
  orderReferenceIssueDate: (i: number) => `orderReferences[${i}].issueDate` as `orderReferences[${number}].issueDate`,

  /**
   * Belge numarası
   * Expected type: string
   */
  additionalDocumentId: (i: number) => `additionalDocuments[${i}].id` as `additionalDocuments[${number}].id`,

  /**
   * Belge tarihi (YYYY-MM-DD)
   * Expected type: string
   */
  additionalDocumentIssueDate: (i: number) => `additionalDocuments[${i}].issueDate` as `additionalDocuments[${number}].issueDate`,

  /**
   * Belge tipi kodu
   * Expected type: string | undefined
   */
  additionalDocumentDocumentTypeCode: (i: number) => `additionalDocuments[${i}].documentTypeCode` as `additionalDocuments[${number}].documentTypeCode`,

  /**
   * Açıklama
   * Expected type: string | undefined
   */
  additionalDocumentDescription: (i: number) => `additionalDocuments[${i}].description` as `additionalDocuments[${number}].description`,

  /**
   * Teslim eden kişinin adı — `DespatchSupplierParty/DespatchContact/Name`
   * Expected type: string | undefined
   */
  despatchContactName: 'despatchContactName',

  /**
   * Vergi kimlik numarası (10 hane VKN veya 11 hane TCKN) — zorunlu
   * Expected type: string
   */
  buyerCustomerTaxNumber: 'buyerCustomer.taxNumber',

  /**
   * Firma adı veya kişi adı soyadı — zorunlu
   * Expected type: string
   */
  buyerCustomerName: 'buyerCustomer.name',

  /**
   * Vergi dairesi — VKN için zorunlu, TCKN için opsiyonel
   * Expected type: string | undefined
   */
  buyerCustomerTaxOffice: 'buyerCustomer.taxOffice',

  /**
   * Adres — zorunlu
   * Expected type: string
   */
  buyerCustomerAddress: 'buyerCustomer.address',

  /**
   * İlçe — zorunlu
   * Expected type: string
   */
  buyerCustomerDistrict: 'buyerCustomer.district',

  /**
   * İl — zorunlu
   * Expected type: string
   */
  buyerCustomerCity: 'buyerCustomer.city',

  /**
   * Ülke — varsayılan: "Türkiye"
   * Expected type: string | undefined
   */
  buyerCustomerCountry: 'buyerCustomer.country',

  /**
   * Posta kodu — varsayılan: "00000"
   * Expected type: string | undefined
   */
  buyerCustomerZipCode: 'buyerCustomer.zipCode',

  /**
   * Telefon
   * Expected type: string | undefined
   */
  buyerCustomerPhone: 'buyerCustomer.phone',

  /**
   * E-posta
   * Expected type: string | undefined
   */
  buyerCustomerEmail: 'buyerCustomer.email',

  /**
   * Web sitesi
   * Expected type: string | undefined
   */
  buyerCustomerWebsite: 'buyerCustomer.website',

  /**
   * Tanımlama şema tipi (ör: "MERSISNO", "TICARETSICILNO", "HIZMETNO", "MUSTERINO", "TESISATNO")
   * Expected type: string
   */
  buyerCustomerIdentificationSchemeId: (i: number) => `buyerCustomer.identifications[${i}].schemeId` as `buyerCustomer.identifications[${number}].schemeId`,

  /**
   * Tanımlama değeri
   * Expected type: string
   */
  buyerCustomerIdentificationValue: (i: number) => `buyerCustomer.identifications[${i}].value` as `buyerCustomer.identifications[${number}].value`,

  /**
   * e-Fatura posta kutusu etiketi (ör: "urn:mail:defaultpk@firma.com.tr"). ⚠️ **Bu alan üretilen UBL-TR Invoice XML'ine YAZILMAZ — bilerek.** Etiket, faturanın kendisine değil **zarfa** (GİB e-Fatura Paketi SBDH: `<sender identifier="..." alias="urn:mail:..."/>` / `<receiver identifier="..." alias="..."/>`) aittir. GİB UBL-TR 1.2.1 `PartyType`'ında etiket için tanımlı bir eleman yoktur; `cbc:EndpointID` şemada bulunsa da UBL-TR kılavuzunda bu amaçla kullanılmaz, dolayısıyla oraya yazmak standart dışı olurdu. e-Arşiv faturalarında etiket kavramı hiç yoktur. Zarf üretimi kütüphanenin sorumluluk sınırının dışındadır (aynı sınır UBLExtensions/imza için de geçerlidir — bkz. B-101). Etiketi entegratöre gönderirken zarf tarafında siz taşımalısınız; alan burada yalnızca çağıranın veri modelini tek yerde tutabilmesi için durur (B-102 denetimi).
   * Expected type: string | undefined
   */
  buyerCustomerAlias: 'buyerCustomer.alias',

  /**
   * Vergi kimlik numarası (10 hane VKN veya 11 hane TCKN) — zorunlu
   * Expected type: string
   */
  sellerSupplierTaxNumber: 'sellerSupplier.taxNumber',

  /**
   * Firma adı veya kişi adı soyadı — zorunlu
   * Expected type: string
   */
  sellerSupplierName: 'sellerSupplier.name',

  /**
   * Vergi dairesi — VKN için zorunlu, TCKN için opsiyonel
   * Expected type: string | undefined
   */
  sellerSupplierTaxOffice: 'sellerSupplier.taxOffice',

  /**
   * Adres — zorunlu
   * Expected type: string
   */
  sellerSupplierAddress: 'sellerSupplier.address',

  /**
   * İlçe — zorunlu
   * Expected type: string
   */
  sellerSupplierDistrict: 'sellerSupplier.district',

  /**
   * İl — zorunlu
   * Expected type: string
   */
  sellerSupplierCity: 'sellerSupplier.city',

  /**
   * Ülke — varsayılan: "Türkiye"
   * Expected type: string | undefined
   */
  sellerSupplierCountry: 'sellerSupplier.country',

  /**
   * Posta kodu — varsayılan: "00000"
   * Expected type: string | undefined
   */
  sellerSupplierZipCode: 'sellerSupplier.zipCode',

  /**
   * Telefon
   * Expected type: string | undefined
   */
  sellerSupplierPhone: 'sellerSupplier.phone',

  /**
   * E-posta
   * Expected type: string | undefined
   */
  sellerSupplierEmail: 'sellerSupplier.email',

  /**
   * Web sitesi
   * Expected type: string | undefined
   */
  sellerSupplierWebsite: 'sellerSupplier.website',

  /**
   * Tanımlama şema tipi (ör: "MERSISNO", "TICARETSICILNO", "HIZMETNO", "MUSTERINO", "TESISATNO")
   * Expected type: string
   */
  sellerSupplierIdentificationSchemeId: (i: number) => `sellerSupplier.identifications[${i}].schemeId` as `sellerSupplier.identifications[${number}].schemeId`,

  /**
   * Tanımlama değeri
   * Expected type: string
   */
  sellerSupplierIdentificationValue: (i: number) => `sellerSupplier.identifications[${i}].value` as `sellerSupplier.identifications[${number}].value`,

  /**
   * e-Fatura posta kutusu etiketi (ör: "urn:mail:defaultpk@firma.com.tr"). ⚠️ **Bu alan üretilen UBL-TR Invoice XML'ine YAZILMAZ — bilerek.** Etiket, faturanın kendisine değil **zarfa** (GİB e-Fatura Paketi SBDH: `<sender identifier="..." alias="urn:mail:..."/>` / `<receiver identifier="..." alias="..."/>`) aittir. GİB UBL-TR 1.2.1 `PartyType`'ında etiket için tanımlı bir eleman yoktur; `cbc:EndpointID` şemada bulunsa da UBL-TR kılavuzunda bu amaçla kullanılmaz, dolayısıyla oraya yazmak standart dışı olurdu. e-Arşiv faturalarında etiket kavramı hiç yoktur. Zarf üretimi kütüphanenin sorumluluk sınırının dışındadır (aynı sınır UBLExtensions/imza için de geçerlidir — bkz. B-101). Etiketi entegratöre gönderirken zarf tarafında siz taşımalısınız; alan burada yalnızca çağıranın veri modelini tek yerde tutabilmesi için durur (B-102 denetimi).
   * Expected type: string | undefined
   */
  sellerSupplierAlias: 'sellerSupplier.alias',

  /**
   * Vergi kimlik numarası (10 hane VKN veya 11 hane TCKN) — zorunlu
   * Expected type: string
   */
  originatorTaxNumber: 'originator.taxNumber',

  /**
   * Firma adı veya kişi adı soyadı — zorunlu
   * Expected type: string
   */
  originatorName: 'originator.name',

  /**
   * Vergi dairesi — VKN için zorunlu, TCKN için opsiyonel
   * Expected type: string | undefined
   */
  originatorTaxOffice: 'originator.taxOffice',

  /**
   * Adres — zorunlu
   * Expected type: string
   */
  originatorAddress: 'originator.address',

  /**
   * İlçe — zorunlu
   * Expected type: string
   */
  originatorDistrict: 'originator.district',

  /**
   * İl — zorunlu
   * Expected type: string
   */
  originatorCity: 'originator.city',

  /**
   * Ülke — varsayılan: "Türkiye"
   * Expected type: string | undefined
   */
  originatorCountry: 'originator.country',

  /**
   * Posta kodu — varsayılan: "00000"
   * Expected type: string | undefined
   */
  originatorZipCode: 'originator.zipCode',

  /**
   * Telefon
   * Expected type: string | undefined
   */
  originatorPhone: 'originator.phone',

  /**
   * E-posta
   * Expected type: string | undefined
   */
  originatorEmail: 'originator.email',

  /**
   * Web sitesi
   * Expected type: string | undefined
   */
  originatorWebsite: 'originator.website',

  /**
   * Tanımlama şema tipi (ör: "MERSISNO", "TICARETSICILNO", "HIZMETNO", "MUSTERINO", "TESISATNO")
   * Expected type: string
   */
  originatorIdentificationSchemeId: (i: number) => `originator.identifications[${i}].schemeId` as `originator.identifications[${number}].schemeId`,

  /**
   * Tanımlama değeri
   * Expected type: string
   */
  originatorIdentificationValue: (i: number) => `originator.identifications[${i}].value` as `originator.identifications[${number}].value`,

  /**
   * e-Fatura posta kutusu etiketi (ör: "urn:mail:defaultpk@firma.com.tr"). ⚠️ **Bu alan üretilen UBL-TR Invoice XML'ine YAZILMAZ — bilerek.** Etiket, faturanın kendisine değil **zarfa** (GİB e-Fatura Paketi SBDH: `<sender identifier="..." alias="urn:mail:..."/>` / `<receiver identifier="..." alias="..."/>`) aittir. GİB UBL-TR 1.2.1 `PartyType`'ında etiket için tanımlı bir eleman yoktur; `cbc:EndpointID` şemada bulunsa da UBL-TR kılavuzunda bu amaçla kullanılmaz, dolayısıyla oraya yazmak standart dışı olurdu. e-Arşiv faturalarında etiket kavramı hiç yoktur. Zarf üretimi kütüphanenin sorumluluk sınırının dışındadır (aynı sınır UBLExtensions/imza için de geçerlidir — bkz. B-101). Etiketi entegratöre gönderirken zarf tarafında siz taşımalısınız; alan burada yalnızca çağıranın veri modelini tek yerde tutabilmesi için durur (B-102 denetimi).
   * Expected type: string | undefined
   */
  originatorAlias: 'originator.alias',
} as const;

export interface DespatchSessionPathMap {
  'sender.taxNumber': string;
  'sender.name': string;
  'sender.taxOffice': string | undefined;
  'sender.address': string;
  'sender.district': string;
  'sender.city': string;
  'sender.country': string | undefined;
  'sender.zipCode': string | undefined;
  'sender.phone': string | undefined;
  'sender.email': string | undefined;
  'sender.website': string | undefined;
  'sender.identifications[${number}].schemeId': string;
  'sender.identifications[${number}].value': string;
  'sender.alias': string | undefined;
  'customer.taxNumber': string;
  'customer.name': string;
  'customer.taxOffice': string | undefined;
  'customer.address': string;
  'customer.district': string;
  'customer.city': string;
  'customer.country': string | undefined;
  'customer.zipCode': string | undefined;
  'customer.phone': string | undefined;
  'customer.email': string | undefined;
  'customer.website': string | undefined;
  'customer.identifications[${number}].schemeId': string;
  'customer.identifications[${number}].value': string;
  'customer.alias': string | undefined;
  'shipment.actualDespatchDatetime': string;
  'shipment.deliveryAddress.address': string;
  'shipment.deliveryAddress.district': string;
  'shipment.deliveryAddress.city': string;
  'shipment.deliveryAddress.country': string | undefined;
  'shipment.deliveryAddress.zipCode': string;
  'shipment.drivers[${number}].firstName': string;
  'shipment.drivers[${number}].familyName': string;
  'shipment.drivers[${number}].nationalityId': string;
  'shipment.carrier.taxNumber': string;
  'shipment.carrier.name': string;
  'shipment.carrier.taxOffice': string | undefined;
  'shipment.carrier.address': string;
  'shipment.carrier.district': string;
  'shipment.carrier.city': string;
  'shipment.carrier.country': string | undefined;
  'shipment.carrier.zipCode': string | undefined;
  'shipment.carrier.phone': string | undefined;
  'shipment.carrier.email': string | undefined;
  'shipment.carrier.website': string | undefined;
  'shipment.carrier.identifications[${number}].schemeId': string;
  'shipment.carrier.identifications[${number}].value': string;
  'shipment.carrier.alias': string | undefined;
  'shipment.licensePlates[${number}].value': string;
  'shipment.licensePlates[${number}].scheme': 'PLAKA' | 'DORSE' | 'DORSEPLAKA' | 'YABANCIPLAKA' | 'YABANCIDORSE' | 'YABANCIDORSEPLAKA' | undefined;
  'shipment.shipmentId': string | undefined;
  'shipment.goodsValue': number | undefined;
  'shipment.goodsValueCurrency': string | undefined;
  'lines[${number}].name': string;
  'lines[${number}].quantity': number;
  'lines[${number}].unitCode': string;
  'lines[${number}].description': string | undefined;
  'lines[${number}].additionalIdentifications[${number}].scheme': string;
  'lines[${number}].additionalIdentifications[${number}].value': string;
  'lines[${number}].note': string | undefined;
  'id': string | undefined;
  'uuid': string | undefined;
  'datetime': string | undefined;
  'type': string | undefined;
  'profile': string | undefined;
  'notes': string[] | undefined;
  'orderReferences[${number}].id': string;
  'orderReferences[${number}].issueDate': string | undefined;
  'additionalDocuments[${number}].id': string;
  'additionalDocuments[${number}].issueDate': string;
  'additionalDocuments[${number}].documentTypeCode': string | undefined;
  'additionalDocuments[${number}].description': string | undefined;
  'despatchContactName': string | undefined;
  'buyerCustomer.taxNumber': string;
  'buyerCustomer.name': string;
  'buyerCustomer.taxOffice': string | undefined;
  'buyerCustomer.address': string;
  'buyerCustomer.district': string;
  'buyerCustomer.city': string;
  'buyerCustomer.country': string | undefined;
  'buyerCustomer.zipCode': string | undefined;
  'buyerCustomer.phone': string | undefined;
  'buyerCustomer.email': string | undefined;
  'buyerCustomer.website': string | undefined;
  'buyerCustomer.identifications[${number}].schemeId': string;
  'buyerCustomer.identifications[${number}].value': string;
  'buyerCustomer.alias': string | undefined;
  'sellerSupplier.taxNumber': string;
  'sellerSupplier.name': string;
  'sellerSupplier.taxOffice': string | undefined;
  'sellerSupplier.address': string;
  'sellerSupplier.district': string;
  'sellerSupplier.city': string;
  'sellerSupplier.country': string | undefined;
  'sellerSupplier.zipCode': string | undefined;
  'sellerSupplier.phone': string | undefined;
  'sellerSupplier.email': string | undefined;
  'sellerSupplier.website': string | undefined;
  'sellerSupplier.identifications[${number}].schemeId': string;
  'sellerSupplier.identifications[${number}].value': string;
  'sellerSupplier.alias': string | undefined;
  'originator.taxNumber': string;
  'originator.name': string;
  'originator.taxOffice': string | undefined;
  'originator.address': string;
  'originator.district': string;
  'originator.city': string;
  'originator.country': string | undefined;
  'originator.zipCode': string | undefined;
  'originator.phone': string | undefined;
  'originator.email': string | undefined;
  'originator.website': string | undefined;
  'originator.identifications[${number}].schemeId': string;
  'originator.identifications[${number}].value': string;
  'originator.alias': string | undefined;
}

export const DESPATCH_KNOWN_PATH_TEMPLATES: ReadonlySet<string> = new Set([
  'additionalDocuments[*].description',
  'additionalDocuments[*].documentTypeCode',
  'additionalDocuments[*].id',
  'additionalDocuments[*].issueDate',
  'buyerCustomer.address',
  'buyerCustomer.alias',
  'buyerCustomer.city',
  'buyerCustomer.country',
  'buyerCustomer.district',
  'buyerCustomer.email',
  'buyerCustomer.identifications[*].schemeId',
  'buyerCustomer.identifications[*].value',
  'buyerCustomer.name',
  'buyerCustomer.phone',
  'buyerCustomer.taxNumber',
  'buyerCustomer.taxOffice',
  'buyerCustomer.website',
  'buyerCustomer.zipCode',
  'customer.address',
  'customer.alias',
  'customer.city',
  'customer.country',
  'customer.district',
  'customer.email',
  'customer.identifications[*].schemeId',
  'customer.identifications[*].value',
  'customer.name',
  'customer.phone',
  'customer.taxNumber',
  'customer.taxOffice',
  'customer.website',
  'customer.zipCode',
  'datetime',
  'despatchContactName',
  'id',
  'lines[*].additionalIdentifications[*].scheme',
  'lines[*].additionalIdentifications[*].value',
  'lines[*].description',
  'lines[*].name',
  'lines[*].note',
  'lines[*].quantity',
  'lines[*].unitCode',
  'notes',
  'orderReferences[*].id',
  'orderReferences[*].issueDate',
  'originator.address',
  'originator.alias',
  'originator.city',
  'originator.country',
  'originator.district',
  'originator.email',
  'originator.identifications[*].schemeId',
  'originator.identifications[*].value',
  'originator.name',
  'originator.phone',
  'originator.taxNumber',
  'originator.taxOffice',
  'originator.website',
  'originator.zipCode',
  'profile',
  'sellerSupplier.address',
  'sellerSupplier.alias',
  'sellerSupplier.city',
  'sellerSupplier.country',
  'sellerSupplier.district',
  'sellerSupplier.email',
  'sellerSupplier.identifications[*].schemeId',
  'sellerSupplier.identifications[*].value',
  'sellerSupplier.name',
  'sellerSupplier.phone',
  'sellerSupplier.taxNumber',
  'sellerSupplier.taxOffice',
  'sellerSupplier.website',
  'sellerSupplier.zipCode',
  'sender.address',
  'sender.alias',
  'sender.city',
  'sender.country',
  'sender.district',
  'sender.email',
  'sender.identifications[*].schemeId',
  'sender.identifications[*].value',
  'sender.name',
  'sender.phone',
  'sender.taxNumber',
  'sender.taxOffice',
  'sender.website',
  'sender.zipCode',
  'shipment.actualDespatchDatetime',
  'shipment.carrier.address',
  'shipment.carrier.alias',
  'shipment.carrier.city',
  'shipment.carrier.country',
  'shipment.carrier.district',
  'shipment.carrier.email',
  'shipment.carrier.identifications[*].schemeId',
  'shipment.carrier.identifications[*].value',
  'shipment.carrier.name',
  'shipment.carrier.phone',
  'shipment.carrier.taxNumber',
  'shipment.carrier.taxOffice',
  'shipment.carrier.website',
  'shipment.carrier.zipCode',
  'shipment.deliveryAddress.address',
  'shipment.deliveryAddress.city',
  'shipment.deliveryAddress.country',
  'shipment.deliveryAddress.district',
  'shipment.deliveryAddress.zipCode',
  'shipment.drivers[*].familyName',
  'shipment.drivers[*].firstName',
  'shipment.drivers[*].nationalityId',
  'shipment.goodsValue',
  'shipment.goodsValueCurrency',
  'shipment.licensePlates[*].scheme',
  'shipment.licensePlates[*].value',
  'shipment.shipmentId',
  'type',
  'uuid',
]);

export const DESPATCH_READ_ONLY_PATHS: ReadonlySet<string> = new Set([]);

/**
 * Sprint 8l.2 / v2.2.4 — Tüm path overload'larının deklaratif kaynağı.
 *
 * TS 5.7+ template literal type inference uyumsuzluğunu çözer (Library Öneri #6).
 * `despatch-session.ts` declaration merging ile `DespatchSession` class'ına enjekte eder:
 *
 *   export interface DespatchSession extends DespatchSessionUpdateOverloads {}
 *
 * TÜM path'ler için spesifik overload üretilir (doc-level literal + fonksiyonel
 * `${number}` placeholder); class'ta `<P extends keyof DespatchSessionPathMap>` generic
 * yok — TS 5.7+ keyof distributive union template literal key'leri açamıyor.
 * Generator regenerate sonrası overload listesi otomatik güncellenir.
 */
export interface DespatchSessionUpdateOverloads {
  update(path: 'sender.taxNumber', value: string): void;
  update(path: 'sender.name', value: string): void;
  update(path: 'sender.taxOffice', value: string | undefined): void;
  update(path: 'sender.address', value: string): void;
  update(path: 'sender.district', value: string): void;
  update(path: 'sender.city', value: string): void;
  update(path: 'sender.country', value: string | undefined): void;
  update(path: 'sender.zipCode', value: string | undefined): void;
  update(path: 'sender.phone', value: string | undefined): void;
  update(path: 'sender.email', value: string | undefined): void;
  update(path: 'sender.website', value: string | undefined): void;
  update(path: `sender.identifications[${number}].schemeId`, value: string): void;
  update(path: `sender.identifications[${number}].value`, value: string): void;
  update(path: 'sender.alias', value: string | undefined): void;
  update(path: 'customer.taxNumber', value: string): void;
  update(path: 'customer.name', value: string): void;
  update(path: 'customer.taxOffice', value: string | undefined): void;
  update(path: 'customer.address', value: string): void;
  update(path: 'customer.district', value: string): void;
  update(path: 'customer.city', value: string): void;
  update(path: 'customer.country', value: string | undefined): void;
  update(path: 'customer.zipCode', value: string | undefined): void;
  update(path: 'customer.phone', value: string | undefined): void;
  update(path: 'customer.email', value: string | undefined): void;
  update(path: 'customer.website', value: string | undefined): void;
  update(path: `customer.identifications[${number}].schemeId`, value: string): void;
  update(path: `customer.identifications[${number}].value`, value: string): void;
  update(path: 'customer.alias', value: string | undefined): void;
  update(path: 'shipment.actualDespatchDatetime', value: string): void;
  update(path: 'shipment.deliveryAddress.address', value: string): void;
  update(path: 'shipment.deliveryAddress.district', value: string): void;
  update(path: 'shipment.deliveryAddress.city', value: string): void;
  update(path: 'shipment.deliveryAddress.country', value: string | undefined): void;
  update(path: 'shipment.deliveryAddress.zipCode', value: string): void;
  update(path: `shipment.drivers[${number}].firstName`, value: string): void;
  update(path: `shipment.drivers[${number}].familyName`, value: string): void;
  update(path: `shipment.drivers[${number}].nationalityId`, value: string): void;
  update(path: 'shipment.carrier.taxNumber', value: string): void;
  update(path: 'shipment.carrier.name', value: string): void;
  update(path: 'shipment.carrier.taxOffice', value: string | undefined): void;
  update(path: 'shipment.carrier.address', value: string): void;
  update(path: 'shipment.carrier.district', value: string): void;
  update(path: 'shipment.carrier.city', value: string): void;
  update(path: 'shipment.carrier.country', value: string | undefined): void;
  update(path: 'shipment.carrier.zipCode', value: string | undefined): void;
  update(path: 'shipment.carrier.phone', value: string | undefined): void;
  update(path: 'shipment.carrier.email', value: string | undefined): void;
  update(path: 'shipment.carrier.website', value: string | undefined): void;
  update(path: `shipment.carrier.identifications[${number}].schemeId`, value: string): void;
  update(path: `shipment.carrier.identifications[${number}].value`, value: string): void;
  update(path: 'shipment.carrier.alias', value: string | undefined): void;
  update(path: `shipment.licensePlates[${number}].value`, value: string): void;
  update(path: `shipment.licensePlates[${number}].scheme`, value: 'PLAKA' | 'DORSE' | 'DORSEPLAKA' | 'YABANCIPLAKA' | 'YABANCIDORSE' | 'YABANCIDORSEPLAKA' | undefined): void;
  update(path: 'shipment.shipmentId', value: string | undefined): void;
  update(path: 'shipment.goodsValue', value: number | undefined): void;
  update(path: 'shipment.goodsValueCurrency', value: string | undefined): void;
  update(path: `lines[${number}].name`, value: string): void;
  update(path: `lines[${number}].quantity`, value: number): void;
  update(path: `lines[${number}].unitCode`, value: string): void;
  update(path: `lines[${number}].description`, value: string | undefined): void;
  update(path: `lines[${number}].additionalIdentifications[${number}].scheme`, value: string): void;
  update(path: `lines[${number}].additionalIdentifications[${number}].value`, value: string): void;
  update(path: `lines[${number}].note`, value: string | undefined): void;
  update(path: 'id', value: string | undefined): void;
  update(path: 'uuid', value: string | undefined): void;
  update(path: 'datetime', value: string | undefined): void;
  update(path: 'type', value: string | undefined): void;
  update(path: 'profile', value: string | undefined): void;
  update(path: 'notes', value: string[] | undefined): void;
  update(path: `orderReferences[${number}].id`, value: string): void;
  update(path: `orderReferences[${number}].issueDate`, value: string | undefined): void;
  update(path: `additionalDocuments[${number}].id`, value: string): void;
  update(path: `additionalDocuments[${number}].issueDate`, value: string): void;
  update(path: `additionalDocuments[${number}].documentTypeCode`, value: string | undefined): void;
  update(path: `additionalDocuments[${number}].description`, value: string | undefined): void;
  update(path: 'despatchContactName', value: string | undefined): void;
  update(path: 'buyerCustomer.taxNumber', value: string): void;
  update(path: 'buyerCustomer.name', value: string): void;
  update(path: 'buyerCustomer.taxOffice', value: string | undefined): void;
  update(path: 'buyerCustomer.address', value: string): void;
  update(path: 'buyerCustomer.district', value: string): void;
  update(path: 'buyerCustomer.city', value: string): void;
  update(path: 'buyerCustomer.country', value: string | undefined): void;
  update(path: 'buyerCustomer.zipCode', value: string | undefined): void;
  update(path: 'buyerCustomer.phone', value: string | undefined): void;
  update(path: 'buyerCustomer.email', value: string | undefined): void;
  update(path: 'buyerCustomer.website', value: string | undefined): void;
  update(path: `buyerCustomer.identifications[${number}].schemeId`, value: string): void;
  update(path: `buyerCustomer.identifications[${number}].value`, value: string): void;
  update(path: 'buyerCustomer.alias', value: string | undefined): void;
  update(path: 'sellerSupplier.taxNumber', value: string): void;
  update(path: 'sellerSupplier.name', value: string): void;
  update(path: 'sellerSupplier.taxOffice', value: string | undefined): void;
  update(path: 'sellerSupplier.address', value: string): void;
  update(path: 'sellerSupplier.district', value: string): void;
  update(path: 'sellerSupplier.city', value: string): void;
  update(path: 'sellerSupplier.country', value: string | undefined): void;
  update(path: 'sellerSupplier.zipCode', value: string | undefined): void;
  update(path: 'sellerSupplier.phone', value: string | undefined): void;
  update(path: 'sellerSupplier.email', value: string | undefined): void;
  update(path: 'sellerSupplier.website', value: string | undefined): void;
  update(path: `sellerSupplier.identifications[${number}].schemeId`, value: string): void;
  update(path: `sellerSupplier.identifications[${number}].value`, value: string): void;
  update(path: 'sellerSupplier.alias', value: string | undefined): void;
  update(path: 'originator.taxNumber', value: string): void;
  update(path: 'originator.name', value: string): void;
  update(path: 'originator.taxOffice', value: string | undefined): void;
  update(path: 'originator.address', value: string): void;
  update(path: 'originator.district', value: string): void;
  update(path: 'originator.city', value: string): void;
  update(path: 'originator.country', value: string | undefined): void;
  update(path: 'originator.zipCode', value: string | undefined): void;
  update(path: 'originator.phone', value: string | undefined): void;
  update(path: 'originator.email', value: string | undefined): void;
  update(path: 'originator.website', value: string | undefined): void;
  update(path: `originator.identifications[${number}].schemeId`, value: string): void;
  update(path: `originator.identifications[${number}].value`, value: string): void;
  update(path: 'originator.alias', value: string | undefined): void;
}

