// =====================================================================
// @generated
// THIS FILE IS AUTO-GENERATED by scripts/generate-session-paths.ts
// DO NOT EDIT BY HAND. Edits will be lost on next regeneration.
// Generator input: src/types/despatch-input.ts (DespatchInput)
// Manual entries: (none)
// Read-only paths: (none)
// =====================================================================
//
// DespatchSessionPaths — path-based update API için tip-güvenli path map (AR-10).
// Mimsoft form akışında her field için `session.update(DespatchSessionPaths.X, value)` çağrısında kullanılır.
//
// Path syntax: bracket notation (örn: 'lines[0].deliveredQuantity') — kütüphanedeki tüm
// validator'lar bu formatta ValidationError.path üretir, reactive session aynı convention'ı taşır.
//
// Generic tip türetimi: `DespatchSessionPathMap` ile `update<P extends keyof DespatchSessionPathMap>(path: P, value: DespatchSessionPathMap[P])`
// imzası compile-time tip kontrolü sağlar.


export const DespatchSessionPaths = {
  /**
   * İrsaliye numarası: ^[A-Z0-9]{3}20[0-9]{2}[0-9]{9}$
   * Expected type: string
   */
  id: 'id',

  /**
   * UUID v4
   * Expected type: string
   */
  uuid: 'uuid',

  /**
   * Profil türü
   * Expected type: 'TEMELIRSALIYE' | 'HKSIRSALIYE' | 'IDISIRSALIYE'
   */
  profileId: 'profileId',

  /**
   * İrsaliye tip kodu
   * Expected type: 'SEVK' | 'MATBUDAN'
   */
  despatchTypeCode: 'despatchTypeCode',

  /**
   * Düzenleme tarihi: YYYY-MM-DD
   * Expected type: string
   */
  issueDate: 'issueDate',

  /**
   * Düzenleme saati: HH:mm:ss — XSD zorunlu (B-18)
   * Expected type: string
   */
  issueTime: 'issueTime',

  /**
   * 10 hane VKN veya 11 hane TCKN
   * Expected type: string
   */
  supplierVknTckn: 'supplier.vknTckn',

  /** Expected type: 'VKN' | 'TCKN' */
  supplierTaxIdType: 'supplier.taxIdType',

  /** Expected type: string */
  supplierAdditionalIdentifierSchemeId: (i: number) => `supplier.additionalIdentifiers[${i}].schemeId` as `supplier.additionalIdentifiers[${number}].schemeId`,

  /** Expected type: string */
  supplierAdditionalIdentifierValue: (i: number) => `supplier.additionalIdentifiers[${i}].value` as `supplier.additionalIdentifiers[${number}].value`,

  /**
   * Tüzel kişi adı — VKN ise zorunlu
   * Expected type: string | undefined
   */
  supplierName: 'supplier.name',

  /**
   * Gerçek kişi adı — TCKN ise zorunlu
   * Expected type: string | undefined
   */
  supplierFirstName: 'supplier.firstName',

  /** Expected type: string | undefined */
  supplierMiddleName: 'supplier.middleName',

  /**
   * Gerçek kişi soyadı — TCKN ise zorunlu
   * Expected type: string | undefined
   */
  supplierFamilyName: 'supplier.familyName',

  /**
   * Adres bilgileri
   * Expected type: string | undefined
   */
  supplierStreetName: 'supplier.streetName',

  /** Expected type: string | undefined */
  supplierBuildingName: 'supplier.buildingName',

  /** Expected type: string | undefined */
  supplierBuildingNumber: 'supplier.buildingNumber',

  /** Expected type: string | undefined */
  supplierRoom: 'supplier.room',

  /**
   * Apartman / blok adı — B-98
   * Expected type: string | undefined
   */
  supplierBlockName: 'supplier.blockName',

  /**
   * Mahalle / district — B-98
   * Expected type: string | undefined
   */
  supplierDistrict: 'supplier.district',

  /**
   * Posta kutusu — B-98
   * Expected type: string | undefined
   */
  supplierPostbox: 'supplier.postbox',

  /** Expected type: string | undefined */
  supplierCitySubdivisionName: 'supplier.citySubdivisionName',

  /** Expected type: string | undefined */
  supplierCityName: 'supplier.cityName',

  /** Expected type: string | undefined */
  supplierPostalZone: 'supplier.postalZone',

  /** Expected type: string | undefined */
  supplierRegion: 'supplier.region',

  /**
   * Ülke adı — cac:Country/cbc:Name
   * Expected type: string | undefined
   */
  supplierCountry: 'supplier.country',

  /**
   * Ülke kodu ISO 3166-1 alpha-2 — cac:Country/cbc:IdentificationCode (B-100)
   * Expected type: string | undefined
   */
  supplierCountryCode: 'supplier.countryCode',

  /**
   * Vergi dairesi adı
   * Expected type: string | undefined
   */
  supplierTaxOffice: 'supplier.taxOffice',

  /**
   * İletişim bilgileri
   * Expected type: string | undefined
   */
  supplierTelephone: 'supplier.telephone',

  /** Expected type: string | undefined */
  supplierTelefax: 'supplier.telefax',

  /** Expected type: string | undefined */
  supplierEmail: 'supplier.email',

  /** Expected type: string | undefined */
  supplierWebsiteUri: 'supplier.websiteUri',

  /**
   * Tüzel kişilik kayıt adı — §3.3 IHRACAT için
   * Expected type: string | undefined
   */
  supplierRegistrationName: 'supplier.registrationName',

  /**
   * Uyruk — §3.4 YOLCUBERABERFATURA Person için
   * Expected type: string | undefined
   */
  supplierNationalityId: 'supplier.nationalityId',

  /**
   * Pasaport numarası — §3.4 YOLCUBERABERFATURA için
   * Expected type: string | undefined
   */
  supplierPassportId: 'supplier.passportId',

  /**
   * 10 hane VKN veya 11 hane TCKN
   * Expected type: string
   */
  customerVknTckn: 'customer.vknTckn',

  /** Expected type: 'VKN' | 'TCKN' */
  customerTaxIdType: 'customer.taxIdType',

  /** Expected type: string */
  customerAdditionalIdentifierSchemeId: (i: number) => `customer.additionalIdentifiers[${i}].schemeId` as `customer.additionalIdentifiers[${number}].schemeId`,

  /** Expected type: string */
  customerAdditionalIdentifierValue: (i: number) => `customer.additionalIdentifiers[${i}].value` as `customer.additionalIdentifiers[${number}].value`,

  /**
   * Tüzel kişi adı — VKN ise zorunlu
   * Expected type: string | undefined
   */
  customerName: 'customer.name',

  /**
   * Gerçek kişi adı — TCKN ise zorunlu
   * Expected type: string | undefined
   */
  customerFirstName: 'customer.firstName',

  /** Expected type: string | undefined */
  customerMiddleName: 'customer.middleName',

  /**
   * Gerçek kişi soyadı — TCKN ise zorunlu
   * Expected type: string | undefined
   */
  customerFamilyName: 'customer.familyName',

  /**
   * Adres bilgileri
   * Expected type: string | undefined
   */
  customerStreetName: 'customer.streetName',

  /** Expected type: string | undefined */
  customerBuildingName: 'customer.buildingName',

  /** Expected type: string | undefined */
  customerBuildingNumber: 'customer.buildingNumber',

  /** Expected type: string | undefined */
  customerRoom: 'customer.room',

  /**
   * Apartman / blok adı — B-98
   * Expected type: string | undefined
   */
  customerBlockName: 'customer.blockName',

  /**
   * Mahalle / district — B-98
   * Expected type: string | undefined
   */
  customerDistrict: 'customer.district',

  /**
   * Posta kutusu — B-98
   * Expected type: string | undefined
   */
  customerPostbox: 'customer.postbox',

  /** Expected type: string | undefined */
  customerCitySubdivisionName: 'customer.citySubdivisionName',

  /** Expected type: string | undefined */
  customerCityName: 'customer.cityName',

  /** Expected type: string | undefined */
  customerPostalZone: 'customer.postalZone',

  /** Expected type: string | undefined */
  customerRegion: 'customer.region',

  /**
   * Ülke adı — cac:Country/cbc:Name
   * Expected type: string | undefined
   */
  customerCountry: 'customer.country',

  /**
   * Ülke kodu ISO 3166-1 alpha-2 — cac:Country/cbc:IdentificationCode (B-100)
   * Expected type: string | undefined
   */
  customerCountryCode: 'customer.countryCode',

  /**
   * Vergi dairesi adı
   * Expected type: string | undefined
   */
  customerTaxOffice: 'customer.taxOffice',

  /**
   * İletişim bilgileri
   * Expected type: string | undefined
   */
  customerTelephone: 'customer.telephone',

  /** Expected type: string | undefined */
  customerTelefax: 'customer.telefax',

  /** Expected type: string | undefined */
  customerEmail: 'customer.email',

  /** Expected type: string | undefined */
  customerWebsiteUri: 'customer.websiteUri',

  /**
   * Tüzel kişilik kayıt adı — §3.3 IHRACAT için
   * Expected type: string | undefined
   */
  customerRegistrationName: 'customer.registrationName',

  /**
   * Uyruk — §3.4 YOLCUBERABERFATURA Person için
   * Expected type: string | undefined
   */
  customerNationalityId: 'customer.nationalityId',

  /**
   * Pasaport numarası — §3.4 YOLCUBERABERFATURA için
   * Expected type: string | undefined
   */
  customerPassportId: 'customer.passportId',

  /**
   * Gerçek sevk tarihi: YYYY-MM-DD — zorunlu
   * Expected type: string
   */
  shipmentActualDespatchDate: 'shipment.actualDespatchDate',

  /**
   * Gerçek sevk saati: HH:mm:ss — zorunlu
   * Expected type: string
   */
  shipmentActualDespatchTime: 'shipment.actualDespatchTime',

  /** Expected type: string | undefined */
  shipmentDeliveryAddressStreetName: 'shipment.deliveryAddress.streetName',

  /** Expected type: string | undefined */
  shipmentDeliveryAddressBuildingName: 'shipment.deliveryAddress.buildingName',

  /** Expected type: string | undefined */
  shipmentDeliveryAddressBuildingNumber: 'shipment.deliveryAddress.buildingNumber',

  /** Expected type: string | undefined */
  shipmentDeliveryAddressRoom: 'shipment.deliveryAddress.room',

  /**
   * Apartman / blok adı — B-98
   * Expected type: string | undefined
   */
  shipmentDeliveryAddressBlockName: 'shipment.deliveryAddress.blockName',

  /**
   * Mahalle / district — B-98
   * Expected type: string | undefined
   */
  shipmentDeliveryAddressDistrict: 'shipment.deliveryAddress.district',

  /**
   * Posta kutusu — B-98
   * Expected type: string | undefined
   */
  shipmentDeliveryAddressPostbox: 'shipment.deliveryAddress.postbox',

  /**
   * İlçe adı — XSD zorunlu (B-35)
   * Expected type: string
   */
  shipmentDeliveryAddressCitySubdivisionName: 'shipment.deliveryAddress.citySubdivisionName',

  /**
   * Şehir adı — XSD zorunlu (B-35)
   * Expected type: string
   */
  shipmentDeliveryAddressCityName: 'shipment.deliveryAddress.cityName',

  /** Expected type: string | undefined */
  shipmentDeliveryAddressPostalZone: 'shipment.deliveryAddress.postalZone',

  /** Expected type: string | undefined */
  shipmentDeliveryAddressRegion: 'shipment.deliveryAddress.region',

  /**
   * Ülke adı — cac:Country/cbc:Name
   * Expected type: string | undefined
   */
  shipmentDeliveryAddressCountry: 'shipment.deliveryAddress.country',

  /**
   * Ülke kodu ISO 3166-1 alpha-2 — cac:Country/cbc:IdentificationCode (B-100)
   * Expected type: string | undefined
   */
  shipmentDeliveryAddressCountryCode: 'shipment.deliveryAddress.countryCode',

  /** Expected type: string */
  shipmentDriverPersonFirstName: (i: number) => `shipment.driverPersons[${i}].firstName` as `shipment.driverPersons[${number}].firstName`,

  /** Expected type: string */
  shipmentDriverPersonFamilyName: (i: number) => `shipment.driverPersons[${i}].familyName` as `shipment.driverPersons[${number}].familyName`,

  /** Expected type: string */
  shipmentDriverPersonNationalityId: (i: number) => `shipment.driverPersons[${i}].nationalityId` as `shipment.driverPersons[${number}].nationalityId`,

  /** Expected type: string | undefined */
  shipmentDriverPersonTitle: (i: number) => `shipment.driverPersons[${i}].title` as `shipment.driverPersons[${number}].title`,

  /** Expected type: string */
  shipmentCarrierPartyVknTckn: 'shipment.carrierParty.vknTckn',

  /** Expected type: 'VKN' | 'TCKN' */
  shipmentCarrierPartyTaxIdType: 'shipment.carrierParty.taxIdType',

  /** Expected type: string | undefined */
  shipmentCarrierPartyName: 'shipment.carrierParty.name',

  /** Expected type: string | undefined */
  shipmentCarrierPartyFirstName: 'shipment.carrierParty.firstName',

  /** Expected type: string | undefined */
  shipmentCarrierPartyFamilyName: 'shipment.carrierParty.familyName',

  /** Expected type: string */
  shipmentCarrierPartyAdditionalIdentifierSchemeId: (i: number) => `shipment.carrierParty.additionalIdentifiers[${i}].schemeId` as `shipment.carrierParty.additionalIdentifiers[${number}].schemeId`,

  /** Expected type: string */
  shipmentCarrierPartyAdditionalIdentifierValue: (i: number) => `shipment.carrierParty.additionalIdentifiers[${i}].value` as `shipment.carrierParty.additionalIdentifiers[${number}].value`,

  /**
   * Plaka numarası. TR schemeID'lerinde `^(0[1-9]|[1-7][0-9]|8[01])[A-Z]+[0-9]+$`, `YABANCI*` schemeID'lerinde `^[A-Z0-9_-]+$` formatında olmalıdır.
   * Expected type: string
   */
  shipmentLicensePlatePlateNumber: (i: number) => `shipment.licensePlates[${i}].plateNumber` as `shipment.licensePlates[${number}].plateNumber`,

  /**
   * Schematron `$LicensePlateIDSchemeIDType` — 6 değer (Sprint 9'da 2'den genişledi)
   * Expected type: 'PLAKA' | 'DORSE' | 'DORSEPLAKA' | 'YABANCIPLAKA' | 'YABANCIDORSE' | 'YABANCIDORSEPLAKA'
   */
  shipmentLicensePlateSchemeId: (i: number) => `shipment.licensePlates[${i}].schemeId` as `shipment.licensePlates[${number}].schemeId`,

  /**
   * B-72: Shipment/cbc:ID değeri (default: '1')
   * Expected type: string | undefined
   */
  shipmentShipmentId: 'shipment.shipmentId',

  /**
   * TransportEquipment cbc:ID (örn. plaka numarası)
   * Expected type: string
   */
  shipmentTransportHandlingUnitTransportEquipmentId: (i: number) => `shipment.transportHandlingUnits[${i}].transportEquipmentId` as `shipment.transportHandlingUnits[${number}].transportEquipmentId`,

  /**
   * schemeID (default: 'DORSEPLAKA')
   * Expected type: string | undefined
   */
  shipmentTransportHandlingUnitSchemeId: (i: number) => `shipment.transportHandlingUnits[${i}].schemeId` as `shipment.transportHandlingUnits[${number}].schemeId`,

  /**
   * Satır numarası (numerik)
   * Expected type: string
   */
  lineId: (i: number) => `lines[${i}].id` as `lines[${number}].id`,

  /**
   * Teslim edilen miktar
   * Expected type: number
   */
  lineDeliveredQuantity: (i: number) => `lines[${i}].deliveredQuantity` as `lines[${number}].deliveredQuantity`,

  /**
   * Birim kodu (UnitCodeList)
   * Expected type: string
   */
  lineUnitCode: (i: number) => `lines[${i}].unitCode` as `lines[${number}].unitCode`,

  /**
   * Ürün adı — boş olamaz
   * Expected type: string
   */
  lineItemName: (i: number) => `lines[${i}].item.name` as `lines[${number}].item.name`,

  /**
   * schemeID: KUNYENO, ILAC, TIBBICIHAZ, DIGER, TELEFON, TABLET_PC, ETIKETNO vb.
   * Expected type: string
   */
  lineItemAdditionalItemIdentificationSchemeId: (i: number, ti: number) => `lines[${i}].item.additionalItemIdentifications[${ti}].schemeId` as `lines[${number}].item.additionalItemIdentifications[${number}].schemeId`,

  /** Expected type: string */
  lineItemAdditionalItemIdentificationValue: (i: number, ti: number) => `lines[${i}].item.additionalItemIdentifications[${ti}].value` as `lines[${number}].item.additionalItemIdentifications[${number}].value`,

  /**
   * Notlar
   * Expected type: string[] | undefined
   */
  notes: 'notes',

  /** Expected type: string */
  orderReferenceId: (i: number) => `orderReferences[${i}].id` as `orderReferences[${number}].id`,

  /**
   * XSD zorunlu (B-33)
   * Expected type: string
   */
  orderReferenceIssueDate: (i: number) => `orderReferences[${i}].issueDate` as `orderReferences[${number}].issueDate`,

  /** Expected type: string */
  additionalDocumentId: (i: number) => `additionalDocuments[${i}].id` as `additionalDocuments[${number}].id`,

  /**
   * `cbc:ID/@schemeID` (Sprint 9). SARJ faturalarında `EnerjiESURaporIDCheck` `schemeID="ESURaporID"` taşıyan en az bir referans zorunlu kılar.
   * Expected type: string | undefined
   */
  additionalDocumentSchemeId: (i: number) => `additionalDocuments[${i}].schemeId` as `additionalDocuments[${number}].schemeId`,

  /** Expected type: string | undefined */
  additionalDocumentIssueDate: (i: number) => `additionalDocuments[${i}].issueDate` as `additionalDocuments[${number}].issueDate`,

  /** Expected type: string | undefined */
  additionalDocumentDocumentTypeCode: (i: number) => `additionalDocuments[${i}].documentTypeCode` as `additionalDocuments[${number}].documentTypeCode`,

  /** Expected type: string | undefined */
  additionalDocumentDocumentType: (i: number) => `additionalDocuments[${i}].documentType` as `additionalDocuments[${number}].documentType`,

  /** Expected type: string | undefined */
  additionalDocumentDocumentDescription: (i: number) => `additionalDocuments[${i}].documentDescription` as `additionalDocuments[${number}].documentDescription`,

  /** Expected type: string */
  additionalDocumentAttachmentEmbeddedBinaryObjectContent: (i: number) => `additionalDocuments[${i}].attachment.embeddedBinaryObject.content` as `additionalDocuments[${number}].attachment.embeddedBinaryObject.content`,

  /** Expected type: string */
  additionalDocumentAttachmentEmbeddedBinaryObjectMimeCode: (i: number) => `additionalDocuments[${i}].attachment.embeddedBinaryObject.mimeCode` as `additionalDocuments[${number}].attachment.embeddedBinaryObject.mimeCode`,

  /** Expected type: string | undefined */
  additionalDocumentAttachmentEmbeddedBinaryObjectEncodingCode: (i: number) => `additionalDocuments[${i}].attachment.embeddedBinaryObject.encodingCode` as `additionalDocuments[${number}].attachment.embeddedBinaryObject.encodingCode`,

  /** Expected type: string | undefined */
  additionalDocumentAttachmentEmbeddedBinaryObjectCharacterSetCode: (i: number) => `additionalDocuments[${i}].attachment.embeddedBinaryObject.characterSetCode` as `additionalDocuments[${number}].attachment.embeddedBinaryObject.characterSetCode`,

  /** Expected type: string | undefined */
  additionalDocumentAttachmentEmbeddedBinaryObjectFilename: (i: number) => `additionalDocuments[${i}].attachment.embeddedBinaryObject.filename` as `additionalDocuments[${number}].attachment.embeddedBinaryObject.filename`,

  /** Expected type: string */
  additionalDocumentAttachmentExternalReferenceUri: (i: number) => `additionalDocuments[${i}].attachment.externalReference.uri` as `additionalDocuments[${number}].attachment.externalReference.uri`,

  /**
   * VKN veya TCKN değeri
   * Expected type: string
   */
  signatureInfoId: 'signatureInfo.id',

  /**
   * 10 hane VKN veya 11 hane TCKN
   * Expected type: string
   */
  signatureInfoSignatoryPartyVknTckn: 'signatureInfo.signatoryParty.vknTckn',

  /** Expected type: 'VKN' | 'TCKN' */
  signatureInfoSignatoryPartyTaxIdType: 'signatureInfo.signatoryParty.taxIdType',

  /** Expected type: string */
  signatureInfoSignatoryPartyAdditionalIdentifierSchemeId: (i: number) => `signatureInfo.signatoryParty.additionalIdentifiers[${i}].schemeId` as `signatureInfo.signatoryParty.additionalIdentifiers[${number}].schemeId`,

  /** Expected type: string */
  signatureInfoSignatoryPartyAdditionalIdentifierValue: (i: number) => `signatureInfo.signatoryParty.additionalIdentifiers[${i}].value` as `signatureInfo.signatoryParty.additionalIdentifiers[${number}].value`,

  /**
   * Tüzel kişi adı — VKN ise zorunlu
   * Expected type: string | undefined
   */
  signatureInfoSignatoryPartyName: 'signatureInfo.signatoryParty.name',

  /**
   * Gerçek kişi adı — TCKN ise zorunlu
   * Expected type: string | undefined
   */
  signatureInfoSignatoryPartyFirstName: 'signatureInfo.signatoryParty.firstName',

  /** Expected type: string | undefined */
  signatureInfoSignatoryPartyMiddleName: 'signatureInfo.signatoryParty.middleName',

  /**
   * Gerçek kişi soyadı — TCKN ise zorunlu
   * Expected type: string | undefined
   */
  signatureInfoSignatoryPartyFamilyName: 'signatureInfo.signatoryParty.familyName',

  /**
   * Adres bilgileri
   * Expected type: string | undefined
   */
  signatureInfoSignatoryPartyStreetName: 'signatureInfo.signatoryParty.streetName',

  /** Expected type: string | undefined */
  signatureInfoSignatoryPartyBuildingName: 'signatureInfo.signatoryParty.buildingName',

  /** Expected type: string | undefined */
  signatureInfoSignatoryPartyBuildingNumber: 'signatureInfo.signatoryParty.buildingNumber',

  /** Expected type: string | undefined */
  signatureInfoSignatoryPartyRoom: 'signatureInfo.signatoryParty.room',

  /**
   * Apartman / blok adı — B-98
   * Expected type: string | undefined
   */
  signatureInfoSignatoryPartyBlockName: 'signatureInfo.signatoryParty.blockName',

  /**
   * Mahalle / district — B-98
   * Expected type: string | undefined
   */
  signatureInfoSignatoryPartyDistrict: 'signatureInfo.signatoryParty.district',

  /**
   * Posta kutusu — B-98
   * Expected type: string | undefined
   */
  signatureInfoSignatoryPartyPostbox: 'signatureInfo.signatoryParty.postbox',

  /** Expected type: string | undefined */
  signatureInfoSignatoryPartyCitySubdivisionName: 'signatureInfo.signatoryParty.citySubdivisionName',

  /** Expected type: string | undefined */
  signatureInfoSignatoryPartyCityName: 'signatureInfo.signatoryParty.cityName',

  /** Expected type: string | undefined */
  signatureInfoSignatoryPartyPostalZone: 'signatureInfo.signatoryParty.postalZone',

  /** Expected type: string | undefined */
  signatureInfoSignatoryPartyRegion: 'signatureInfo.signatoryParty.region',

  /**
   * Ülke adı — cac:Country/cbc:Name
   * Expected type: string | undefined
   */
  signatureInfoSignatoryPartyCountry: 'signatureInfo.signatoryParty.country',

  /**
   * Ülke kodu ISO 3166-1 alpha-2 — cac:Country/cbc:IdentificationCode (B-100)
   * Expected type: string | undefined
   */
  signatureInfoSignatoryPartyCountryCode: 'signatureInfo.signatoryParty.countryCode',

  /**
   * Vergi dairesi adı
   * Expected type: string | undefined
   */
  signatureInfoSignatoryPartyTaxOffice: 'signatureInfo.signatoryParty.taxOffice',

  /**
   * İletişim bilgileri
   * Expected type: string | undefined
   */
  signatureInfoSignatoryPartyTelephone: 'signatureInfo.signatoryParty.telephone',

  /** Expected type: string | undefined */
  signatureInfoSignatoryPartyTelefax: 'signatureInfo.signatoryParty.telefax',

  /** Expected type: string | undefined */
  signatureInfoSignatoryPartyEmail: 'signatureInfo.signatoryParty.email',

  /** Expected type: string | undefined */
  signatureInfoSignatoryPartyWebsiteUri: 'signatureInfo.signatoryParty.websiteUri',

  /**
   * Tüzel kişilik kayıt adı — §3.3 IHRACAT için
   * Expected type: string | undefined
   */
  signatureInfoSignatoryPartyRegistrationName: 'signatureInfo.signatoryParty.registrationName',

  /**
   * Uyruk — §3.4 YOLCUBERABERFATURA Person için
   * Expected type: string | undefined
   */
  signatureInfoSignatoryPartyNationalityId: 'signatureInfo.signatoryParty.nationalityId',

  /**
   * Pasaport numarası — §3.4 YOLCUBERABERFATURA için
   * Expected type: string | undefined
   */
  signatureInfoSignatoryPartyPassportId: 'signatureInfo.signatoryParty.passportId',

  /**
   * #Signature_{ID} referansı
   * Expected type: string | undefined
   */
  signatureInfoDigitalSignatureUri: 'signatureInfo.digitalSignatureUri',

  /**
   * Teslim eden kişinin adı — DespatchSupplierParty altındaki DespatchContact/Name
   * Expected type: string | undefined
   */
  despatchContactName: 'despatchContactName',

  /**
   * 10 hane VKN veya 11 hane TCKN
   * Expected type: string
   */
  buyerCustomerVknTckn: 'buyerCustomer.vknTckn',

  /** Expected type: 'VKN' | 'TCKN' */
  buyerCustomerTaxIdType: 'buyerCustomer.taxIdType',

  /** Expected type: string */
  buyerCustomerAdditionalIdentifierSchemeId: (i: number) => `buyerCustomer.additionalIdentifiers[${i}].schemeId` as `buyerCustomer.additionalIdentifiers[${number}].schemeId`,

  /** Expected type: string */
  buyerCustomerAdditionalIdentifierValue: (i: number) => `buyerCustomer.additionalIdentifiers[${i}].value` as `buyerCustomer.additionalIdentifiers[${number}].value`,

  /**
   * Tüzel kişi adı — VKN ise zorunlu
   * Expected type: string | undefined
   */
  buyerCustomerName: 'buyerCustomer.name',

  /**
   * Gerçek kişi adı — TCKN ise zorunlu
   * Expected type: string | undefined
   */
  buyerCustomerFirstName: 'buyerCustomer.firstName',

  /** Expected type: string | undefined */
  buyerCustomerMiddleName: 'buyerCustomer.middleName',

  /**
   * Gerçek kişi soyadı — TCKN ise zorunlu
   * Expected type: string | undefined
   */
  buyerCustomerFamilyName: 'buyerCustomer.familyName',

  /**
   * Adres bilgileri
   * Expected type: string | undefined
   */
  buyerCustomerStreetName: 'buyerCustomer.streetName',

  /** Expected type: string | undefined */
  buyerCustomerBuildingName: 'buyerCustomer.buildingName',

  /** Expected type: string | undefined */
  buyerCustomerBuildingNumber: 'buyerCustomer.buildingNumber',

  /** Expected type: string | undefined */
  buyerCustomerRoom: 'buyerCustomer.room',

  /**
   * Apartman / blok adı — B-98
   * Expected type: string | undefined
   */
  buyerCustomerBlockName: 'buyerCustomer.blockName',

  /**
   * Mahalle / district — B-98
   * Expected type: string | undefined
   */
  buyerCustomerDistrict: 'buyerCustomer.district',

  /**
   * Posta kutusu — B-98
   * Expected type: string | undefined
   */
  buyerCustomerPostbox: 'buyerCustomer.postbox',

  /** Expected type: string | undefined */
  buyerCustomerCitySubdivisionName: 'buyerCustomer.citySubdivisionName',

  /** Expected type: string | undefined */
  buyerCustomerCityName: 'buyerCustomer.cityName',

  /** Expected type: string | undefined */
  buyerCustomerPostalZone: 'buyerCustomer.postalZone',

  /** Expected type: string | undefined */
  buyerCustomerRegion: 'buyerCustomer.region',

  /**
   * Ülke adı — cac:Country/cbc:Name
   * Expected type: string | undefined
   */
  buyerCustomerCountry: 'buyerCustomer.country',

  /**
   * Ülke kodu ISO 3166-1 alpha-2 — cac:Country/cbc:IdentificationCode (B-100)
   * Expected type: string | undefined
   */
  buyerCustomerCountryCode: 'buyerCustomer.countryCode',

  /**
   * Vergi dairesi adı
   * Expected type: string | undefined
   */
  buyerCustomerTaxOffice: 'buyerCustomer.taxOffice',

  /**
   * İletişim bilgileri
   * Expected type: string | undefined
   */
  buyerCustomerTelephone: 'buyerCustomer.telephone',

  /** Expected type: string | undefined */
  buyerCustomerTelefax: 'buyerCustomer.telefax',

  /** Expected type: string | undefined */
  buyerCustomerEmail: 'buyerCustomer.email',

  /** Expected type: string | undefined */
  buyerCustomerWebsiteUri: 'buyerCustomer.websiteUri',

  /**
   * Tüzel kişilik kayıt adı — §3.3 IHRACAT için
   * Expected type: string | undefined
   */
  buyerCustomerRegistrationName: 'buyerCustomer.registrationName',

  /**
   * Uyruk — §3.4 YOLCUBERABERFATURA Person için
   * Expected type: string | undefined
   */
  buyerCustomerNationalityId: 'buyerCustomer.nationalityId',

  /**
   * Pasaport numarası — §3.4 YOLCUBERABERFATURA için
   * Expected type: string | undefined
   */
  buyerCustomerPassportId: 'buyerCustomer.passportId',

  /**
   * 10 hane VKN veya 11 hane TCKN
   * Expected type: string
   */
  sellerSupplierVknTckn: 'sellerSupplier.vknTckn',

  /** Expected type: 'VKN' | 'TCKN' */
  sellerSupplierTaxIdType: 'sellerSupplier.taxIdType',

  /** Expected type: string */
  sellerSupplierAdditionalIdentifierSchemeId: (i: number) => `sellerSupplier.additionalIdentifiers[${i}].schemeId` as `sellerSupplier.additionalIdentifiers[${number}].schemeId`,

  /** Expected type: string */
  sellerSupplierAdditionalIdentifierValue: (i: number) => `sellerSupplier.additionalIdentifiers[${i}].value` as `sellerSupplier.additionalIdentifiers[${number}].value`,

  /**
   * Tüzel kişi adı — VKN ise zorunlu
   * Expected type: string | undefined
   */
  sellerSupplierName: 'sellerSupplier.name',

  /**
   * Gerçek kişi adı — TCKN ise zorunlu
   * Expected type: string | undefined
   */
  sellerSupplierFirstName: 'sellerSupplier.firstName',

  /** Expected type: string | undefined */
  sellerSupplierMiddleName: 'sellerSupplier.middleName',

  /**
   * Gerçek kişi soyadı — TCKN ise zorunlu
   * Expected type: string | undefined
   */
  sellerSupplierFamilyName: 'sellerSupplier.familyName',

  /**
   * Adres bilgileri
   * Expected type: string | undefined
   */
  sellerSupplierStreetName: 'sellerSupplier.streetName',

  /** Expected type: string | undefined */
  sellerSupplierBuildingName: 'sellerSupplier.buildingName',

  /** Expected type: string | undefined */
  sellerSupplierBuildingNumber: 'sellerSupplier.buildingNumber',

  /** Expected type: string | undefined */
  sellerSupplierRoom: 'sellerSupplier.room',

  /**
   * Apartman / blok adı — B-98
   * Expected type: string | undefined
   */
  sellerSupplierBlockName: 'sellerSupplier.blockName',

  /**
   * Mahalle / district — B-98
   * Expected type: string | undefined
   */
  sellerSupplierDistrict: 'sellerSupplier.district',

  /**
   * Posta kutusu — B-98
   * Expected type: string | undefined
   */
  sellerSupplierPostbox: 'sellerSupplier.postbox',

  /** Expected type: string | undefined */
  sellerSupplierCitySubdivisionName: 'sellerSupplier.citySubdivisionName',

  /** Expected type: string | undefined */
  sellerSupplierCityName: 'sellerSupplier.cityName',

  /** Expected type: string | undefined */
  sellerSupplierPostalZone: 'sellerSupplier.postalZone',

  /** Expected type: string | undefined */
  sellerSupplierRegion: 'sellerSupplier.region',

  /**
   * Ülke adı — cac:Country/cbc:Name
   * Expected type: string | undefined
   */
  sellerSupplierCountry: 'sellerSupplier.country',

  /**
   * Ülke kodu ISO 3166-1 alpha-2 — cac:Country/cbc:IdentificationCode (B-100)
   * Expected type: string | undefined
   */
  sellerSupplierCountryCode: 'sellerSupplier.countryCode',

  /**
   * Vergi dairesi adı
   * Expected type: string | undefined
   */
  sellerSupplierTaxOffice: 'sellerSupplier.taxOffice',

  /**
   * İletişim bilgileri
   * Expected type: string | undefined
   */
  sellerSupplierTelephone: 'sellerSupplier.telephone',

  /** Expected type: string | undefined */
  sellerSupplierTelefax: 'sellerSupplier.telefax',

  /** Expected type: string | undefined */
  sellerSupplierEmail: 'sellerSupplier.email',

  /** Expected type: string | undefined */
  sellerSupplierWebsiteUri: 'sellerSupplier.websiteUri',

  /**
   * Tüzel kişilik kayıt adı — §3.3 IHRACAT için
   * Expected type: string | undefined
   */
  sellerSupplierRegistrationName: 'sellerSupplier.registrationName',

  /**
   * Uyruk — §3.4 YOLCUBERABERFATURA Person için
   * Expected type: string | undefined
   */
  sellerSupplierNationalityId: 'sellerSupplier.nationalityId',

  /**
   * Pasaport numarası — §3.4 YOLCUBERABERFATURA için
   * Expected type: string | undefined
   */
  sellerSupplierPassportId: 'sellerSupplier.passportId',

  /**
   * 10 hane VKN veya 11 hane TCKN
   * Expected type: string
   */
  originatorVknTckn: 'originator.vknTckn',

  /** Expected type: 'VKN' | 'TCKN' */
  originatorTaxIdType: 'originator.taxIdType',

  /** Expected type: string */
  originatorAdditionalIdentifierSchemeId: (i: number) => `originator.additionalIdentifiers[${i}].schemeId` as `originator.additionalIdentifiers[${number}].schemeId`,

  /** Expected type: string */
  originatorAdditionalIdentifierValue: (i: number) => `originator.additionalIdentifiers[${i}].value` as `originator.additionalIdentifiers[${number}].value`,

  /**
   * Tüzel kişi adı — VKN ise zorunlu
   * Expected type: string | undefined
   */
  originatorName: 'originator.name',

  /**
   * Gerçek kişi adı — TCKN ise zorunlu
   * Expected type: string | undefined
   */
  originatorFirstName: 'originator.firstName',

  /** Expected type: string | undefined */
  originatorMiddleName: 'originator.middleName',

  /**
   * Gerçek kişi soyadı — TCKN ise zorunlu
   * Expected type: string | undefined
   */
  originatorFamilyName: 'originator.familyName',

  /**
   * Adres bilgileri
   * Expected type: string | undefined
   */
  originatorStreetName: 'originator.streetName',

  /** Expected type: string | undefined */
  originatorBuildingName: 'originator.buildingName',

  /** Expected type: string | undefined */
  originatorBuildingNumber: 'originator.buildingNumber',

  /** Expected type: string | undefined */
  originatorRoom: 'originator.room',

  /**
   * Apartman / blok adı — B-98
   * Expected type: string | undefined
   */
  originatorBlockName: 'originator.blockName',

  /**
   * Mahalle / district — B-98
   * Expected type: string | undefined
   */
  originatorDistrict: 'originator.district',

  /**
   * Posta kutusu — B-98
   * Expected type: string | undefined
   */
  originatorPostbox: 'originator.postbox',

  /** Expected type: string | undefined */
  originatorCitySubdivisionName: 'originator.citySubdivisionName',

  /** Expected type: string | undefined */
  originatorCityName: 'originator.cityName',

  /** Expected type: string | undefined */
  originatorPostalZone: 'originator.postalZone',

  /** Expected type: string | undefined */
  originatorRegion: 'originator.region',

  /**
   * Ülke adı — cac:Country/cbc:Name
   * Expected type: string | undefined
   */
  originatorCountry: 'originator.country',

  /**
   * Ülke kodu ISO 3166-1 alpha-2 — cac:Country/cbc:IdentificationCode (B-100)
   * Expected type: string | undefined
   */
  originatorCountryCode: 'originator.countryCode',

  /**
   * Vergi dairesi adı
   * Expected type: string | undefined
   */
  originatorTaxOffice: 'originator.taxOffice',

  /**
   * İletişim bilgileri
   * Expected type: string | undefined
   */
  originatorTelephone: 'originator.telephone',

  /** Expected type: string | undefined */
  originatorTelefax: 'originator.telefax',

  /** Expected type: string | undefined */
  originatorEmail: 'originator.email',

  /** Expected type: string | undefined */
  originatorWebsiteUri: 'originator.websiteUri',

  /**
   * Tüzel kişilik kayıt adı — §3.3 IHRACAT için
   * Expected type: string | undefined
   */
  originatorRegistrationName: 'originator.registrationName',

  /**
   * Uyruk — §3.4 YOLCUBERABERFATURA Person için
   * Expected type: string | undefined
   */
  originatorNationalityId: 'originator.nationalityId',

  /**
   * Pasaport numarası — §3.4 YOLCUBERABERFATURA için
   * Expected type: string | undefined
   */
  originatorPassportId: 'originator.passportId',
} as const;

export interface DespatchSessionPathMap {
  'id': string;
  'uuid': string;
  'profileId': 'TEMELIRSALIYE' | 'HKSIRSALIYE' | 'IDISIRSALIYE';
  'despatchTypeCode': 'SEVK' | 'MATBUDAN';
  'issueDate': string;
  'issueTime': string;
  'supplier.vknTckn': string;
  'supplier.taxIdType': 'VKN' | 'TCKN';
  'supplier.additionalIdentifiers[${number}].schemeId': string;
  'supplier.additionalIdentifiers[${number}].value': string;
  'supplier.name': string | undefined;
  'supplier.firstName': string | undefined;
  'supplier.middleName': string | undefined;
  'supplier.familyName': string | undefined;
  'supplier.streetName': string | undefined;
  'supplier.buildingName': string | undefined;
  'supplier.buildingNumber': string | undefined;
  'supplier.room': string | undefined;
  'supplier.blockName': string | undefined;
  'supplier.district': string | undefined;
  'supplier.postbox': string | undefined;
  'supplier.citySubdivisionName': string | undefined;
  'supplier.cityName': string | undefined;
  'supplier.postalZone': string | undefined;
  'supplier.region': string | undefined;
  'supplier.country': string | undefined;
  'supplier.countryCode': string | undefined;
  'supplier.taxOffice': string | undefined;
  'supplier.telephone': string | undefined;
  'supplier.telefax': string | undefined;
  'supplier.email': string | undefined;
  'supplier.websiteUri': string | undefined;
  'supplier.registrationName': string | undefined;
  'supplier.nationalityId': string | undefined;
  'supplier.passportId': string | undefined;
  'customer.vknTckn': string;
  'customer.taxIdType': 'VKN' | 'TCKN';
  'customer.additionalIdentifiers[${number}].schemeId': string;
  'customer.additionalIdentifiers[${number}].value': string;
  'customer.name': string | undefined;
  'customer.firstName': string | undefined;
  'customer.middleName': string | undefined;
  'customer.familyName': string | undefined;
  'customer.streetName': string | undefined;
  'customer.buildingName': string | undefined;
  'customer.buildingNumber': string | undefined;
  'customer.room': string | undefined;
  'customer.blockName': string | undefined;
  'customer.district': string | undefined;
  'customer.postbox': string | undefined;
  'customer.citySubdivisionName': string | undefined;
  'customer.cityName': string | undefined;
  'customer.postalZone': string | undefined;
  'customer.region': string | undefined;
  'customer.country': string | undefined;
  'customer.countryCode': string | undefined;
  'customer.taxOffice': string | undefined;
  'customer.telephone': string | undefined;
  'customer.telefax': string | undefined;
  'customer.email': string | undefined;
  'customer.websiteUri': string | undefined;
  'customer.registrationName': string | undefined;
  'customer.nationalityId': string | undefined;
  'customer.passportId': string | undefined;
  'shipment.actualDespatchDate': string;
  'shipment.actualDespatchTime': string;
  'shipment.deliveryAddress.streetName': string | undefined;
  'shipment.deliveryAddress.buildingName': string | undefined;
  'shipment.deliveryAddress.buildingNumber': string | undefined;
  'shipment.deliveryAddress.room': string | undefined;
  'shipment.deliveryAddress.blockName': string | undefined;
  'shipment.deliveryAddress.district': string | undefined;
  'shipment.deliveryAddress.postbox': string | undefined;
  'shipment.deliveryAddress.citySubdivisionName': string;
  'shipment.deliveryAddress.cityName': string;
  'shipment.deliveryAddress.postalZone': string | undefined;
  'shipment.deliveryAddress.region': string | undefined;
  'shipment.deliveryAddress.country': string | undefined;
  'shipment.deliveryAddress.countryCode': string | undefined;
  'shipment.driverPersons[${number}].firstName': string;
  'shipment.driverPersons[${number}].familyName': string;
  'shipment.driverPersons[${number}].nationalityId': string;
  'shipment.driverPersons[${number}].title': string | undefined;
  'shipment.carrierParty.vknTckn': string;
  'shipment.carrierParty.taxIdType': 'VKN' | 'TCKN';
  'shipment.carrierParty.name': string | undefined;
  'shipment.carrierParty.firstName': string | undefined;
  'shipment.carrierParty.familyName': string | undefined;
  'shipment.carrierParty.additionalIdentifiers[${number}].schemeId': string;
  'shipment.carrierParty.additionalIdentifiers[${number}].value': string;
  'shipment.licensePlates[${number}].plateNumber': string;
  'shipment.licensePlates[${number}].schemeId': 'PLAKA' | 'DORSE' | 'DORSEPLAKA' | 'YABANCIPLAKA' | 'YABANCIDORSE' | 'YABANCIDORSEPLAKA';
  'shipment.shipmentId': string | undefined;
  'shipment.transportHandlingUnits[${number}].transportEquipmentId': string;
  'shipment.transportHandlingUnits[${number}].schemeId': string | undefined;
  'lines[${number}].id': string;
  'lines[${number}].deliveredQuantity': number;
  'lines[${number}].unitCode': string;
  'lines[${number}].item.name': string;
  'lines[${number}].item.additionalItemIdentifications[${number}].schemeId': string;
  'lines[${number}].item.additionalItemIdentifications[${number}].value': string;
  'notes': string[] | undefined;
  'orderReferences[${number}].id': string;
  'orderReferences[${number}].issueDate': string;
  'additionalDocuments[${number}].id': string;
  'additionalDocuments[${number}].schemeId': string | undefined;
  'additionalDocuments[${number}].issueDate': string | undefined;
  'additionalDocuments[${number}].documentTypeCode': string | undefined;
  'additionalDocuments[${number}].documentType': string | undefined;
  'additionalDocuments[${number}].documentDescription': string | undefined;
  'additionalDocuments[${number}].attachment.embeddedBinaryObject.content': string;
  'additionalDocuments[${number}].attachment.embeddedBinaryObject.mimeCode': string;
  'additionalDocuments[${number}].attachment.embeddedBinaryObject.encodingCode': string | undefined;
  'additionalDocuments[${number}].attachment.embeddedBinaryObject.characterSetCode': string | undefined;
  'additionalDocuments[${number}].attachment.embeddedBinaryObject.filename': string | undefined;
  'additionalDocuments[${number}].attachment.externalReference.uri': string;
  'signatureInfo.id': string;
  'signatureInfo.signatoryParty.vknTckn': string;
  'signatureInfo.signatoryParty.taxIdType': 'VKN' | 'TCKN';
  'signatureInfo.signatoryParty.additionalIdentifiers[${number}].schemeId': string;
  'signatureInfo.signatoryParty.additionalIdentifiers[${number}].value': string;
  'signatureInfo.signatoryParty.name': string | undefined;
  'signatureInfo.signatoryParty.firstName': string | undefined;
  'signatureInfo.signatoryParty.middleName': string | undefined;
  'signatureInfo.signatoryParty.familyName': string | undefined;
  'signatureInfo.signatoryParty.streetName': string | undefined;
  'signatureInfo.signatoryParty.buildingName': string | undefined;
  'signatureInfo.signatoryParty.buildingNumber': string | undefined;
  'signatureInfo.signatoryParty.room': string | undefined;
  'signatureInfo.signatoryParty.blockName': string | undefined;
  'signatureInfo.signatoryParty.district': string | undefined;
  'signatureInfo.signatoryParty.postbox': string | undefined;
  'signatureInfo.signatoryParty.citySubdivisionName': string | undefined;
  'signatureInfo.signatoryParty.cityName': string | undefined;
  'signatureInfo.signatoryParty.postalZone': string | undefined;
  'signatureInfo.signatoryParty.region': string | undefined;
  'signatureInfo.signatoryParty.country': string | undefined;
  'signatureInfo.signatoryParty.countryCode': string | undefined;
  'signatureInfo.signatoryParty.taxOffice': string | undefined;
  'signatureInfo.signatoryParty.telephone': string | undefined;
  'signatureInfo.signatoryParty.telefax': string | undefined;
  'signatureInfo.signatoryParty.email': string | undefined;
  'signatureInfo.signatoryParty.websiteUri': string | undefined;
  'signatureInfo.signatoryParty.registrationName': string | undefined;
  'signatureInfo.signatoryParty.nationalityId': string | undefined;
  'signatureInfo.signatoryParty.passportId': string | undefined;
  'signatureInfo.digitalSignatureUri': string | undefined;
  'despatchContactName': string | undefined;
  'buyerCustomer.vknTckn': string;
  'buyerCustomer.taxIdType': 'VKN' | 'TCKN';
  'buyerCustomer.additionalIdentifiers[${number}].schemeId': string;
  'buyerCustomer.additionalIdentifiers[${number}].value': string;
  'buyerCustomer.name': string | undefined;
  'buyerCustomer.firstName': string | undefined;
  'buyerCustomer.middleName': string | undefined;
  'buyerCustomer.familyName': string | undefined;
  'buyerCustomer.streetName': string | undefined;
  'buyerCustomer.buildingName': string | undefined;
  'buyerCustomer.buildingNumber': string | undefined;
  'buyerCustomer.room': string | undefined;
  'buyerCustomer.blockName': string | undefined;
  'buyerCustomer.district': string | undefined;
  'buyerCustomer.postbox': string | undefined;
  'buyerCustomer.citySubdivisionName': string | undefined;
  'buyerCustomer.cityName': string | undefined;
  'buyerCustomer.postalZone': string | undefined;
  'buyerCustomer.region': string | undefined;
  'buyerCustomer.country': string | undefined;
  'buyerCustomer.countryCode': string | undefined;
  'buyerCustomer.taxOffice': string | undefined;
  'buyerCustomer.telephone': string | undefined;
  'buyerCustomer.telefax': string | undefined;
  'buyerCustomer.email': string | undefined;
  'buyerCustomer.websiteUri': string | undefined;
  'buyerCustomer.registrationName': string | undefined;
  'buyerCustomer.nationalityId': string | undefined;
  'buyerCustomer.passportId': string | undefined;
  'sellerSupplier.vknTckn': string;
  'sellerSupplier.taxIdType': 'VKN' | 'TCKN';
  'sellerSupplier.additionalIdentifiers[${number}].schemeId': string;
  'sellerSupplier.additionalIdentifiers[${number}].value': string;
  'sellerSupplier.name': string | undefined;
  'sellerSupplier.firstName': string | undefined;
  'sellerSupplier.middleName': string | undefined;
  'sellerSupplier.familyName': string | undefined;
  'sellerSupplier.streetName': string | undefined;
  'sellerSupplier.buildingName': string | undefined;
  'sellerSupplier.buildingNumber': string | undefined;
  'sellerSupplier.room': string | undefined;
  'sellerSupplier.blockName': string | undefined;
  'sellerSupplier.district': string | undefined;
  'sellerSupplier.postbox': string | undefined;
  'sellerSupplier.citySubdivisionName': string | undefined;
  'sellerSupplier.cityName': string | undefined;
  'sellerSupplier.postalZone': string | undefined;
  'sellerSupplier.region': string | undefined;
  'sellerSupplier.country': string | undefined;
  'sellerSupplier.countryCode': string | undefined;
  'sellerSupplier.taxOffice': string | undefined;
  'sellerSupplier.telephone': string | undefined;
  'sellerSupplier.telefax': string | undefined;
  'sellerSupplier.email': string | undefined;
  'sellerSupplier.websiteUri': string | undefined;
  'sellerSupplier.registrationName': string | undefined;
  'sellerSupplier.nationalityId': string | undefined;
  'sellerSupplier.passportId': string | undefined;
  'originator.vknTckn': string;
  'originator.taxIdType': 'VKN' | 'TCKN';
  'originator.additionalIdentifiers[${number}].schemeId': string;
  'originator.additionalIdentifiers[${number}].value': string;
  'originator.name': string | undefined;
  'originator.firstName': string | undefined;
  'originator.middleName': string | undefined;
  'originator.familyName': string | undefined;
  'originator.streetName': string | undefined;
  'originator.buildingName': string | undefined;
  'originator.buildingNumber': string | undefined;
  'originator.room': string | undefined;
  'originator.blockName': string | undefined;
  'originator.district': string | undefined;
  'originator.postbox': string | undefined;
  'originator.citySubdivisionName': string | undefined;
  'originator.cityName': string | undefined;
  'originator.postalZone': string | undefined;
  'originator.region': string | undefined;
  'originator.country': string | undefined;
  'originator.countryCode': string | undefined;
  'originator.taxOffice': string | undefined;
  'originator.telephone': string | undefined;
  'originator.telefax': string | undefined;
  'originator.email': string | undefined;
  'originator.websiteUri': string | undefined;
  'originator.registrationName': string | undefined;
  'originator.nationalityId': string | undefined;
  'originator.passportId': string | undefined;
}

export const DESPATCH_KNOWN_PATH_TEMPLATES: ReadonlySet<string> = new Set([
  'additionalDocuments[*].attachment.embeddedBinaryObject.characterSetCode',
  'additionalDocuments[*].attachment.embeddedBinaryObject.content',
  'additionalDocuments[*].attachment.embeddedBinaryObject.encodingCode',
  'additionalDocuments[*].attachment.embeddedBinaryObject.filename',
  'additionalDocuments[*].attachment.embeddedBinaryObject.mimeCode',
  'additionalDocuments[*].attachment.externalReference.uri',
  'additionalDocuments[*].documentDescription',
  'additionalDocuments[*].documentType',
  'additionalDocuments[*].documentTypeCode',
  'additionalDocuments[*].id',
  'additionalDocuments[*].issueDate',
  'additionalDocuments[*].schemeId',
  'buyerCustomer.additionalIdentifiers[*].schemeId',
  'buyerCustomer.additionalIdentifiers[*].value',
  'buyerCustomer.blockName',
  'buyerCustomer.buildingName',
  'buyerCustomer.buildingNumber',
  'buyerCustomer.cityName',
  'buyerCustomer.citySubdivisionName',
  'buyerCustomer.country',
  'buyerCustomer.countryCode',
  'buyerCustomer.district',
  'buyerCustomer.email',
  'buyerCustomer.familyName',
  'buyerCustomer.firstName',
  'buyerCustomer.middleName',
  'buyerCustomer.name',
  'buyerCustomer.nationalityId',
  'buyerCustomer.passportId',
  'buyerCustomer.postalZone',
  'buyerCustomer.postbox',
  'buyerCustomer.region',
  'buyerCustomer.registrationName',
  'buyerCustomer.room',
  'buyerCustomer.streetName',
  'buyerCustomer.taxIdType',
  'buyerCustomer.taxOffice',
  'buyerCustomer.telefax',
  'buyerCustomer.telephone',
  'buyerCustomer.vknTckn',
  'buyerCustomer.websiteUri',
  'customer.additionalIdentifiers[*].schemeId',
  'customer.additionalIdentifiers[*].value',
  'customer.blockName',
  'customer.buildingName',
  'customer.buildingNumber',
  'customer.cityName',
  'customer.citySubdivisionName',
  'customer.country',
  'customer.countryCode',
  'customer.district',
  'customer.email',
  'customer.familyName',
  'customer.firstName',
  'customer.middleName',
  'customer.name',
  'customer.nationalityId',
  'customer.passportId',
  'customer.postalZone',
  'customer.postbox',
  'customer.region',
  'customer.registrationName',
  'customer.room',
  'customer.streetName',
  'customer.taxIdType',
  'customer.taxOffice',
  'customer.telefax',
  'customer.telephone',
  'customer.vknTckn',
  'customer.websiteUri',
  'despatchContactName',
  'despatchTypeCode',
  'id',
  'issueDate',
  'issueTime',
  'lines[*].deliveredQuantity',
  'lines[*].id',
  'lines[*].item.additionalItemIdentifications[*].schemeId',
  'lines[*].item.additionalItemIdentifications[*].value',
  'lines[*].item.name',
  'lines[*].unitCode',
  'notes',
  'orderReferences[*].id',
  'orderReferences[*].issueDate',
  'originator.additionalIdentifiers[*].schemeId',
  'originator.additionalIdentifiers[*].value',
  'originator.blockName',
  'originator.buildingName',
  'originator.buildingNumber',
  'originator.cityName',
  'originator.citySubdivisionName',
  'originator.country',
  'originator.countryCode',
  'originator.district',
  'originator.email',
  'originator.familyName',
  'originator.firstName',
  'originator.middleName',
  'originator.name',
  'originator.nationalityId',
  'originator.passportId',
  'originator.postalZone',
  'originator.postbox',
  'originator.region',
  'originator.registrationName',
  'originator.room',
  'originator.streetName',
  'originator.taxIdType',
  'originator.taxOffice',
  'originator.telefax',
  'originator.telephone',
  'originator.vknTckn',
  'originator.websiteUri',
  'profileId',
  'sellerSupplier.additionalIdentifiers[*].schemeId',
  'sellerSupplier.additionalIdentifiers[*].value',
  'sellerSupplier.blockName',
  'sellerSupplier.buildingName',
  'sellerSupplier.buildingNumber',
  'sellerSupplier.cityName',
  'sellerSupplier.citySubdivisionName',
  'sellerSupplier.country',
  'sellerSupplier.countryCode',
  'sellerSupplier.district',
  'sellerSupplier.email',
  'sellerSupplier.familyName',
  'sellerSupplier.firstName',
  'sellerSupplier.middleName',
  'sellerSupplier.name',
  'sellerSupplier.nationalityId',
  'sellerSupplier.passportId',
  'sellerSupplier.postalZone',
  'sellerSupplier.postbox',
  'sellerSupplier.region',
  'sellerSupplier.registrationName',
  'sellerSupplier.room',
  'sellerSupplier.streetName',
  'sellerSupplier.taxIdType',
  'sellerSupplier.taxOffice',
  'sellerSupplier.telefax',
  'sellerSupplier.telephone',
  'sellerSupplier.vknTckn',
  'sellerSupplier.websiteUri',
  'shipment.actualDespatchDate',
  'shipment.actualDespatchTime',
  'shipment.carrierParty.additionalIdentifiers[*].schemeId',
  'shipment.carrierParty.additionalIdentifiers[*].value',
  'shipment.carrierParty.familyName',
  'shipment.carrierParty.firstName',
  'shipment.carrierParty.name',
  'shipment.carrierParty.taxIdType',
  'shipment.carrierParty.vknTckn',
  'shipment.deliveryAddress.blockName',
  'shipment.deliveryAddress.buildingName',
  'shipment.deliveryAddress.buildingNumber',
  'shipment.deliveryAddress.cityName',
  'shipment.deliveryAddress.citySubdivisionName',
  'shipment.deliveryAddress.country',
  'shipment.deliveryAddress.countryCode',
  'shipment.deliveryAddress.district',
  'shipment.deliveryAddress.postalZone',
  'shipment.deliveryAddress.postbox',
  'shipment.deliveryAddress.region',
  'shipment.deliveryAddress.room',
  'shipment.deliveryAddress.streetName',
  'shipment.driverPersons[*].familyName',
  'shipment.driverPersons[*].firstName',
  'shipment.driverPersons[*].nationalityId',
  'shipment.driverPersons[*].title',
  'shipment.licensePlates[*].plateNumber',
  'shipment.licensePlates[*].schemeId',
  'shipment.shipmentId',
  'shipment.transportHandlingUnits[*].schemeId',
  'shipment.transportHandlingUnits[*].transportEquipmentId',
  'signatureInfo.digitalSignatureUri',
  'signatureInfo.id',
  'signatureInfo.signatoryParty.additionalIdentifiers[*].schemeId',
  'signatureInfo.signatoryParty.additionalIdentifiers[*].value',
  'signatureInfo.signatoryParty.blockName',
  'signatureInfo.signatoryParty.buildingName',
  'signatureInfo.signatoryParty.buildingNumber',
  'signatureInfo.signatoryParty.cityName',
  'signatureInfo.signatoryParty.citySubdivisionName',
  'signatureInfo.signatoryParty.country',
  'signatureInfo.signatoryParty.countryCode',
  'signatureInfo.signatoryParty.district',
  'signatureInfo.signatoryParty.email',
  'signatureInfo.signatoryParty.familyName',
  'signatureInfo.signatoryParty.firstName',
  'signatureInfo.signatoryParty.middleName',
  'signatureInfo.signatoryParty.name',
  'signatureInfo.signatoryParty.nationalityId',
  'signatureInfo.signatoryParty.passportId',
  'signatureInfo.signatoryParty.postalZone',
  'signatureInfo.signatoryParty.postbox',
  'signatureInfo.signatoryParty.region',
  'signatureInfo.signatoryParty.registrationName',
  'signatureInfo.signatoryParty.room',
  'signatureInfo.signatoryParty.streetName',
  'signatureInfo.signatoryParty.taxIdType',
  'signatureInfo.signatoryParty.taxOffice',
  'signatureInfo.signatoryParty.telefax',
  'signatureInfo.signatoryParty.telephone',
  'signatureInfo.signatoryParty.vknTckn',
  'signatureInfo.signatoryParty.websiteUri',
  'supplier.additionalIdentifiers[*].schemeId',
  'supplier.additionalIdentifiers[*].value',
  'supplier.blockName',
  'supplier.buildingName',
  'supplier.buildingNumber',
  'supplier.cityName',
  'supplier.citySubdivisionName',
  'supplier.country',
  'supplier.countryCode',
  'supplier.district',
  'supplier.email',
  'supplier.familyName',
  'supplier.firstName',
  'supplier.middleName',
  'supplier.name',
  'supplier.nationalityId',
  'supplier.passportId',
  'supplier.postalZone',
  'supplier.postbox',
  'supplier.region',
  'supplier.registrationName',
  'supplier.room',
  'supplier.streetName',
  'supplier.taxIdType',
  'supplier.taxOffice',
  'supplier.telefax',
  'supplier.telephone',
  'supplier.vknTckn',
  'supplier.websiteUri',
  'uuid',
]);

export const DESPATCH_READ_ONLY_PATHS: ReadonlySet<string> = new Set([]);

/**
 * Sprint 8l.2 / v2.2.4 — Tüm path overload'larının deklaratif kaynağı.
 *
 * TS 5.7+ template literal type inference uyumsuzluğunu çözer (Library Öneri #6).
 * `despatch-session.ts` declaration merging ile `DespatchSession` class'ına enjekte eder:
 *
 *   export interface DespatchSession extends DespatchSessionUpdateOverloads {}
 *
 * TÜM path'ler için spesifik overload üretilir (doc-level literal + fonksiyonel
 * `${number}` placeholder); class'ta `<P extends keyof DespatchSessionPathMap>` generic
 * yok — TS 5.7+ keyof distributive union template literal key'leri açamıyor.
 * Generator regenerate sonrası overload listesi otomatik güncellenir.
 */
export interface DespatchSessionUpdateOverloads {
  update(path: 'id', value: string): void;
  update(path: 'uuid', value: string): void;
  update(path: 'profileId', value: 'TEMELIRSALIYE' | 'HKSIRSALIYE' | 'IDISIRSALIYE'): void;
  update(path: 'despatchTypeCode', value: 'SEVK' | 'MATBUDAN'): void;
  update(path: 'issueDate', value: string): void;
  update(path: 'issueTime', value: string): void;
  update(path: 'supplier.vknTckn', value: string): void;
  update(path: 'supplier.taxIdType', value: 'VKN' | 'TCKN'): void;
  update(path: `supplier.additionalIdentifiers[${number}].schemeId`, value: string): void;
  update(path: `supplier.additionalIdentifiers[${number}].value`, value: string): void;
  update(path: 'supplier.name', value: string | undefined): void;
  update(path: 'supplier.firstName', value: string | undefined): void;
  update(path: 'supplier.middleName', value: string | undefined): void;
  update(path: 'supplier.familyName', value: string | undefined): void;
  update(path: 'supplier.streetName', value: string | undefined): void;
  update(path: 'supplier.buildingName', value: string | undefined): void;
  update(path: 'supplier.buildingNumber', value: string | undefined): void;
  update(path: 'supplier.room', value: string | undefined): void;
  update(path: 'supplier.blockName', value: string | undefined): void;
  update(path: 'supplier.district', value: string | undefined): void;
  update(path: 'supplier.postbox', value: string | undefined): void;
  update(path: 'supplier.citySubdivisionName', value: string | undefined): void;
  update(path: 'supplier.cityName', value: string | undefined): void;
  update(path: 'supplier.postalZone', value: string | undefined): void;
  update(path: 'supplier.region', value: string | undefined): void;
  update(path: 'supplier.country', value: string | undefined): void;
  update(path: 'supplier.countryCode', value: string | undefined): void;
  update(path: 'supplier.taxOffice', value: string | undefined): void;
  update(path: 'supplier.telephone', value: string | undefined): void;
  update(path: 'supplier.telefax', value: string | undefined): void;
  update(path: 'supplier.email', value: string | undefined): void;
  update(path: 'supplier.websiteUri', value: string | undefined): void;
  update(path: 'supplier.registrationName', value: string | undefined): void;
  update(path: 'supplier.nationalityId', value: string | undefined): void;
  update(path: 'supplier.passportId', value: string | undefined): void;
  update(path: 'customer.vknTckn', value: string): void;
  update(path: 'customer.taxIdType', value: 'VKN' | 'TCKN'): void;
  update(path: `customer.additionalIdentifiers[${number}].schemeId`, value: string): void;
  update(path: `customer.additionalIdentifiers[${number}].value`, value: string): void;
  update(path: 'customer.name', value: string | undefined): void;
  update(path: 'customer.firstName', value: string | undefined): void;
  update(path: 'customer.middleName', value: string | undefined): void;
  update(path: 'customer.familyName', value: string | undefined): void;
  update(path: 'customer.streetName', value: string | undefined): void;
  update(path: 'customer.buildingName', value: string | undefined): void;
  update(path: 'customer.buildingNumber', value: string | undefined): void;
  update(path: 'customer.room', value: string | undefined): void;
  update(path: 'customer.blockName', value: string | undefined): void;
  update(path: 'customer.district', value: string | undefined): void;
  update(path: 'customer.postbox', value: string | undefined): void;
  update(path: 'customer.citySubdivisionName', value: string | undefined): void;
  update(path: 'customer.cityName', value: string | undefined): void;
  update(path: 'customer.postalZone', value: string | undefined): void;
  update(path: 'customer.region', value: string | undefined): void;
  update(path: 'customer.country', value: string | undefined): void;
  update(path: 'customer.countryCode', value: string | undefined): void;
  update(path: 'customer.taxOffice', value: string | undefined): void;
  update(path: 'customer.telephone', value: string | undefined): void;
  update(path: 'customer.telefax', value: string | undefined): void;
  update(path: 'customer.email', value: string | undefined): void;
  update(path: 'customer.websiteUri', value: string | undefined): void;
  update(path: 'customer.registrationName', value: string | undefined): void;
  update(path: 'customer.nationalityId', value: string | undefined): void;
  update(path: 'customer.passportId', value: string | undefined): void;
  update(path: 'shipment.actualDespatchDate', value: string): void;
  update(path: 'shipment.actualDespatchTime', value: string): void;
  update(path: 'shipment.deliveryAddress.streetName', value: string | undefined): void;
  update(path: 'shipment.deliveryAddress.buildingName', value: string | undefined): void;
  update(path: 'shipment.deliveryAddress.buildingNumber', value: string | undefined): void;
  update(path: 'shipment.deliveryAddress.room', value: string | undefined): void;
  update(path: 'shipment.deliveryAddress.blockName', value: string | undefined): void;
  update(path: 'shipment.deliveryAddress.district', value: string | undefined): void;
  update(path: 'shipment.deliveryAddress.postbox', value: string | undefined): void;
  update(path: 'shipment.deliveryAddress.citySubdivisionName', value: string): void;
  update(path: 'shipment.deliveryAddress.cityName', value: string): void;
  update(path: 'shipment.deliveryAddress.postalZone', value: string | undefined): void;
  update(path: 'shipment.deliveryAddress.region', value: string | undefined): void;
  update(path: 'shipment.deliveryAddress.country', value: string | undefined): void;
  update(path: 'shipment.deliveryAddress.countryCode', value: string | undefined): void;
  update(path: `shipment.driverPersons[${number}].firstName`, value: string): void;
  update(path: `shipment.driverPersons[${number}].familyName`, value: string): void;
  update(path: `shipment.driverPersons[${number}].nationalityId`, value: string): void;
  update(path: `shipment.driverPersons[${number}].title`, value: string | undefined): void;
  update(path: 'shipment.carrierParty.vknTckn', value: string): void;
  update(path: 'shipment.carrierParty.taxIdType', value: 'VKN' | 'TCKN'): void;
  update(path: 'shipment.carrierParty.name', value: string | undefined): void;
  update(path: 'shipment.carrierParty.firstName', value: string | undefined): void;
  update(path: 'shipment.carrierParty.familyName', value: string | undefined): void;
  update(path: `shipment.carrierParty.additionalIdentifiers[${number}].schemeId`, value: string): void;
  update(path: `shipment.carrierParty.additionalIdentifiers[${number}].value`, value: string): void;
  update(path: `shipment.licensePlates[${number}].plateNumber`, value: string): void;
  update(path: `shipment.licensePlates[${number}].schemeId`, value: 'PLAKA' | 'DORSE' | 'DORSEPLAKA' | 'YABANCIPLAKA' | 'YABANCIDORSE' | 'YABANCIDORSEPLAKA'): void;
  update(path: 'shipment.shipmentId', value: string | undefined): void;
  update(path: `shipment.transportHandlingUnits[${number}].transportEquipmentId`, value: string): void;
  update(path: `shipment.transportHandlingUnits[${number}].schemeId`, value: string | undefined): void;
  update(path: `lines[${number}].id`, value: string): void;
  update(path: `lines[${number}].deliveredQuantity`, value: number): void;
  update(path: `lines[${number}].unitCode`, value: string): void;
  update(path: `lines[${number}].item.name`, value: string): void;
  update(path: `lines[${number}].item.additionalItemIdentifications[${number}].schemeId`, value: string): void;
  update(path: `lines[${number}].item.additionalItemIdentifications[${number}].value`, value: string): void;
  update(path: 'notes', value: string[] | undefined): void;
  update(path: `orderReferences[${number}].id`, value: string): void;
  update(path: `orderReferences[${number}].issueDate`, value: string): void;
  update(path: `additionalDocuments[${number}].id`, value: string): void;
  update(path: `additionalDocuments[${number}].schemeId`, value: string | undefined): void;
  update(path: `additionalDocuments[${number}].issueDate`, value: string | undefined): void;
  update(path: `additionalDocuments[${number}].documentTypeCode`, value: string | undefined): void;
  update(path: `additionalDocuments[${number}].documentType`, value: string | undefined): void;
  update(path: `additionalDocuments[${number}].documentDescription`, value: string | undefined): void;
  update(path: `additionalDocuments[${number}].attachment.embeddedBinaryObject.content`, value: string): void;
  update(path: `additionalDocuments[${number}].attachment.embeddedBinaryObject.mimeCode`, value: string): void;
  update(path: `additionalDocuments[${number}].attachment.embeddedBinaryObject.encodingCode`, value: string | undefined): void;
  update(path: `additionalDocuments[${number}].attachment.embeddedBinaryObject.characterSetCode`, value: string | undefined): void;
  update(path: `additionalDocuments[${number}].attachment.embeddedBinaryObject.filename`, value: string | undefined): void;
  update(path: `additionalDocuments[${number}].attachment.externalReference.uri`, value: string): void;
  update(path: 'signatureInfo.id', value: string): void;
  update(path: 'signatureInfo.signatoryParty.vknTckn', value: string): void;
  update(path: 'signatureInfo.signatoryParty.taxIdType', value: 'VKN' | 'TCKN'): void;
  update(path: `signatureInfo.signatoryParty.additionalIdentifiers[${number}].schemeId`, value: string): void;
  update(path: `signatureInfo.signatoryParty.additionalIdentifiers[${number}].value`, value: string): void;
  update(path: 'signatureInfo.signatoryParty.name', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.firstName', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.middleName', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.familyName', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.streetName', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.buildingName', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.buildingNumber', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.room', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.blockName', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.district', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.postbox', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.citySubdivisionName', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.cityName', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.postalZone', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.region', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.country', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.countryCode', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.taxOffice', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.telephone', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.telefax', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.email', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.websiteUri', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.registrationName', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.nationalityId', value: string | undefined): void;
  update(path: 'signatureInfo.signatoryParty.passportId', value: string | undefined): void;
  update(path: 'signatureInfo.digitalSignatureUri', value: string | undefined): void;
  update(path: 'despatchContactName', value: string | undefined): void;
  update(path: 'buyerCustomer.vknTckn', value: string): void;
  update(path: 'buyerCustomer.taxIdType', value: 'VKN' | 'TCKN'): void;
  update(path: `buyerCustomer.additionalIdentifiers[${number}].schemeId`, value: string): void;
  update(path: `buyerCustomer.additionalIdentifiers[${number}].value`, value: string): void;
  update(path: 'buyerCustomer.name', value: string | undefined): void;
  update(path: 'buyerCustomer.firstName', value: string | undefined): void;
  update(path: 'buyerCustomer.middleName', value: string | undefined): void;
  update(path: 'buyerCustomer.familyName', value: string | undefined): void;
  update(path: 'buyerCustomer.streetName', value: string | undefined): void;
  update(path: 'buyerCustomer.buildingName', value: string | undefined): void;
  update(path: 'buyerCustomer.buildingNumber', value: string | undefined): void;
  update(path: 'buyerCustomer.room', value: string | undefined): void;
  update(path: 'buyerCustomer.blockName', value: string | undefined): void;
  update(path: 'buyerCustomer.district', value: string | undefined): void;
  update(path: 'buyerCustomer.postbox', value: string | undefined): void;
  update(path: 'buyerCustomer.citySubdivisionName', value: string | undefined): void;
  update(path: 'buyerCustomer.cityName', value: string | undefined): void;
  update(path: 'buyerCustomer.postalZone', value: string | undefined): void;
  update(path: 'buyerCustomer.region', value: string | undefined): void;
  update(path: 'buyerCustomer.country', value: string | undefined): void;
  update(path: 'buyerCustomer.countryCode', value: string | undefined): void;
  update(path: 'buyerCustomer.taxOffice', value: string | undefined): void;
  update(path: 'buyerCustomer.telephone', value: string | undefined): void;
  update(path: 'buyerCustomer.telefax', value: string | undefined): void;
  update(path: 'buyerCustomer.email', value: string | undefined): void;
  update(path: 'buyerCustomer.websiteUri', value: string | undefined): void;
  update(path: 'buyerCustomer.registrationName', value: string | undefined): void;
  update(path: 'buyerCustomer.nationalityId', value: string | undefined): void;
  update(path: 'buyerCustomer.passportId', value: string | undefined): void;
  update(path: 'sellerSupplier.vknTckn', value: string): void;
  update(path: 'sellerSupplier.taxIdType', value: 'VKN' | 'TCKN'): void;
  update(path: `sellerSupplier.additionalIdentifiers[${number}].schemeId`, value: string): void;
  update(path: `sellerSupplier.additionalIdentifiers[${number}].value`, value: string): void;
  update(path: 'sellerSupplier.name', value: string | undefined): void;
  update(path: 'sellerSupplier.firstName', value: string | undefined): void;
  update(path: 'sellerSupplier.middleName', value: string | undefined): void;
  update(path: 'sellerSupplier.familyName', value: string | undefined): void;
  update(path: 'sellerSupplier.streetName', value: string | undefined): void;
  update(path: 'sellerSupplier.buildingName', value: string | undefined): void;
  update(path: 'sellerSupplier.buildingNumber', value: string | undefined): void;
  update(path: 'sellerSupplier.room', value: string | undefined): void;
  update(path: 'sellerSupplier.blockName', value: string | undefined): void;
  update(path: 'sellerSupplier.district', value: string | undefined): void;
  update(path: 'sellerSupplier.postbox', value: string | undefined): void;
  update(path: 'sellerSupplier.citySubdivisionName', value: string | undefined): void;
  update(path: 'sellerSupplier.cityName', value: string | undefined): void;
  update(path: 'sellerSupplier.postalZone', value: string | undefined): void;
  update(path: 'sellerSupplier.region', value: string | undefined): void;
  update(path: 'sellerSupplier.country', value: string | undefined): void;
  update(path: 'sellerSupplier.countryCode', value: string | undefined): void;
  update(path: 'sellerSupplier.taxOffice', value: string | undefined): void;
  update(path: 'sellerSupplier.telephone', value: string | undefined): void;
  update(path: 'sellerSupplier.telefax', value: string | undefined): void;
  update(path: 'sellerSupplier.email', value: string | undefined): void;
  update(path: 'sellerSupplier.websiteUri', value: string | undefined): void;
  update(path: 'sellerSupplier.registrationName', value: string | undefined): void;
  update(path: 'sellerSupplier.nationalityId', value: string | undefined): void;
  update(path: 'sellerSupplier.passportId', value: string | undefined): void;
  update(path: 'originator.vknTckn', value: string): void;
  update(path: 'originator.taxIdType', value: 'VKN' | 'TCKN'): void;
  update(path: `originator.additionalIdentifiers[${number}].schemeId`, value: string): void;
  update(path: `originator.additionalIdentifiers[${number}].value`, value: string): void;
  update(path: 'originator.name', value: string | undefined): void;
  update(path: 'originator.firstName', value: string | undefined): void;
  update(path: 'originator.middleName', value: string | undefined): void;
  update(path: 'originator.familyName', value: string | undefined): void;
  update(path: 'originator.streetName', value: string | undefined): void;
  update(path: 'originator.buildingName', value: string | undefined): void;
  update(path: 'originator.buildingNumber', value: string | undefined): void;
  update(path: 'originator.room', value: string | undefined): void;
  update(path: 'originator.blockName', value: string | undefined): void;
  update(path: 'originator.district', value: string | undefined): void;
  update(path: 'originator.postbox', value: string | undefined): void;
  update(path: 'originator.citySubdivisionName', value: string | undefined): void;
  update(path: 'originator.cityName', value: string | undefined): void;
  update(path: 'originator.postalZone', value: string | undefined): void;
  update(path: 'originator.region', value: string | undefined): void;
  update(path: 'originator.country', value: string | undefined): void;
  update(path: 'originator.countryCode', value: string | undefined): void;
  update(path: 'originator.taxOffice', value: string | undefined): void;
  update(path: 'originator.telephone', value: string | undefined): void;
  update(path: 'originator.telefax', value: string | undefined): void;
  update(path: 'originator.email', value: string | undefined): void;
  update(path: 'originator.websiteUri', value: string | undefined): void;
  update(path: 'originator.registrationName', value: string | undefined): void;
  update(path: 'originator.nationalityId', value: string | undefined): void;
  update(path: 'originator.passportId', value: string | undefined): void;
}

