// =====================================================================
// @generated
// THIS FILE IS AUTO-GENERATED by scripts/generate-session-paths.ts
// DO NOT EDIT BY HAND. Edits will be lost on next regeneration.
// Generator input: src/calculator/simple-types.ts (SimpleInvoiceInput)
// Manual entries: liability (session-level state, see scripts/generate-session-paths.ts MANUAL_ENTRIES)
// Read-only paths: isExport (constructor-locked, D-10)
// =====================================================================
//
// SessionPaths — path-based update API için tip-güvenli path map (AR-10).
// Mimsoft form akışında her field için `session.update(SessionPaths.X, value)` çağrısında kullanılır.
//
// Path syntax: bracket notation (örn: 'lines[0].kdvPercent') — kütüphanedeki tüm
// validator'lar bu formatta ValidationError.path üretir, reactive session aynı convention'ı taşır.
//
// Generic tip türetimi: `SessionPathMap` ile `update<P extends keyof SessionPathMap>(path: P, value: SessionPathMap[P])`
// imzası compile-time tip kontrolü sağlar.


export const SessionPaths = {
  /**
   * Vergi kimlik numarası (10 hane VKN veya 11 hane TCKN) — zorunlu
   * Expected type: string
   */
  senderTaxNumber: 'sender.taxNumber',

  /**
   * Firma adı veya kişi adı soyadı — zorunlu
   * Expected type: string
   */
  senderName: 'sender.name',

  /**
   * Vergi dairesi — VKN için zorunlu, TCKN için opsiyonel
   * Expected type: string | undefined
   */
  senderTaxOffice: 'sender.taxOffice',

  /**
   * Adres — zorunlu
   * Expected type: string
   */
  senderAddress: 'sender.address',

  /**
   * İlçe — zorunlu
   * Expected type: string
   */
  senderDistrict: 'sender.district',

  /**
   * İl — zorunlu
   * Expected type: string
   */
  senderCity: 'sender.city',

  /**
   * Ülke — varsayılan: "Türkiye"
   * Expected type: string | undefined
   */
  senderCountry: 'sender.country',

  /**
   * Posta kodu — varsayılan: "00000"
   * Expected type: string | undefined
   */
  senderZipCode: 'sender.zipCode',

  /**
   * Telefon
   * Expected type: string | undefined
   */
  senderPhone: 'sender.phone',

  /**
   * E-posta
   * Expected type: string | undefined
   */
  senderEmail: 'sender.email',

  /**
   * Web sitesi
   * Expected type: string | undefined
   */
  senderWebsite: 'sender.website',

  /**
   * e-Fatura/e-Arşiv posta kutusu etiketi (ör: "urn:mail:defaultpk@...")
   * Expected type: string | undefined
   */
  senderAlias: 'sender.alias',

  /**
   * Vergi kimlik numarası (10 hane VKN veya 11 hane TCKN) — zorunlu
   * Expected type: string
   */
  customerTaxNumber: 'customer.taxNumber',

  /**
   * Firma adı veya kişi adı soyadı — zorunlu
   * Expected type: string
   */
  customerName: 'customer.name',

  /**
   * Vergi dairesi — VKN için zorunlu, TCKN için opsiyonel
   * Expected type: string | undefined
   */
  customerTaxOffice: 'customer.taxOffice',

  /**
   * Adres — zorunlu
   * Expected type: string
   */
  customerAddress: 'customer.address',

  /**
   * İlçe — zorunlu
   * Expected type: string
   */
  customerDistrict: 'customer.district',

  /**
   * İl — zorunlu
   * Expected type: string
   */
  customerCity: 'customer.city',

  /**
   * Ülke — varsayılan: "Türkiye"
   * Expected type: string | undefined
   */
  customerCountry: 'customer.country',

  /**
   * Posta kodu — varsayılan: "00000"
   * Expected type: string | undefined
   */
  customerZipCode: 'customer.zipCode',

  /**
   * Telefon
   * Expected type: string | undefined
   */
  customerPhone: 'customer.phone',

  /**
   * E-posta
   * Expected type: string | undefined
   */
  customerEmail: 'customer.email',

  /**
   * Web sitesi
   * Expected type: string | undefined
   */
  customerWebsite: 'customer.website',

  /**
   * e-Fatura/e-Arşiv posta kutusu etiketi (ör: "urn:mail:defaultpk@...")
   * Expected type: string | undefined
   */
  customerAlias: 'customer.alias',

  /**
   * Ürün/hizmet adı — zorunlu
   * Expected type: string
   */
  lineName: (i: number) => `lines[${i}].name`,

  /**
   * Miktar — zorunlu
   * Expected type: number
   */
  lineQuantity: (i: number) => `lines[${i}].quantity`,

  /**
   * Birim fiyat (KDV hariç) — zorunlu
   * Expected type: number
   */
  linePrice: (i: number) => `lines[${i}].price`,

  /**
   * Birim kodu (Türkçe isim veya UBL kodu: "Adet" veya "C62") — varsayılan: "Adet"
   * Expected type: string | undefined
   */
  lineUnitCode: (i: number) => `lines[${i}].unitCode`,

  /**
   * KDV oranı (%) — zorunlu
   * Expected type: number
   */
  lineKdvPercent: (i: number) => `lines[${i}].kdvPercent`,

  /**
   * Satır bazı KDV istisna sebep kodu (B-NEW-11 / M11). KDV=0 kalem için manuel verilmeli (ör. 351). Verilmezse belge seviyesi `SimpleInvoiceInput.kdvExemptionCode` fallback olarak kullanılır. Self-exemption tiplerinde (ISTISNA, IHRACKAYITLI, OZELMATRAH + IHRACAT, YOLCUBERABERFATURA, OZELFATURA, YATIRIMTESVIK profilleri) zorunlu değil; dışındaki tiplerde KDV=0 kaleminde zorunlu.
   * Expected type: string | undefined
   */
  lineKdvExemptionCode: (i: number) => `lines[${i}].kdvExemptionCode`,

  /**
   * İskonto oranı (%) — opsiyonel
   * Expected type: number | undefined
   */
  lineAllowancePercent: (i: number) => `lines[${i}].allowancePercent`,

  /**
   * Vergi kodu (ör: "0071" ÖTV 1. Liste, "1047" Damga V.) — zorunlu
   * Expected type: string
   */
  lineTaxCode: (i: number, ti: number) => `lines[${i}].taxes[${ti}].code`,

  /**
   * Vergi oranı (%) — zorunlu
   * Expected type: number
   */
  lineTaxPercent: (i: number, ti: number) => `lines[${i}].taxes[${ti}].percent`,

  /**
   * KDV tevkifat kodu (ör: "602") — opsiyonel, verilirse fatura tipi TEVKIFAT olur
   * Expected type: string | undefined
   */
  lineWithholdingTaxCode: (i: number) => `lines[${i}].withholdingTaxCode`,

  /**
   * Tevkifat 650 (Diğer) kodu için dinamik yüzde (0-100). Sadece 650 kodu ile kullanılır; diğer tevkifat kodlarında oran config'den gelir.
   * Expected type: number | undefined
   */
  lineWithholdingTaxPercent: (i: number) => `lines[${i}].withholdingTaxPercent`,

  /**
   * Ürün açıklaması
   * Expected type: string | undefined
   */
  lineDescription: (i: number) => `lines[${i}].description`,

  /**
   * Marka
   * Expected type: string | undefined
   */
  lineBrand: (i: number) => `lines[${i}].brand`,

  /**
   * Model
   * Expected type: string | undefined
   */
  lineModel: (i: number) => `lines[${i}].model`,

  /**
   * Alıcı ürün kodu
   * Expected type: string | undefined
   */
  lineBuyerCode: (i: number) => `lines[${i}].buyerCode`,

  /**
   * Satıcı ürün kodu
   * Expected type: string | undefined
   */
  lineSellerCode: (i: number) => `lines[${i}].sellerCode`,

  /**
   * Üretici ürün kodu
   * Expected type: string | undefined
   */
  lineManufacturerCode: (i: number) => `lines[${i}].manufacturerCode`,

  /**
   * Menşe ülke
   * Expected type: string | undefined
   */
  lineOrigin: (i: number) => `lines[${i}].origin`,

  /**
   * Satır notu
   * Expected type: string | undefined
   */
  lineNote: (i: number) => `lines[${i}].note`,

  /**
   * Teslimat şartı kodu (INCOTERMS: "EXW", "FOB", "CIF" vb.)
   * Expected type: string | undefined
   */
  lineDeliveryDeliveryTermCode: (i: number) => `lines[${i}].delivery.deliveryTermCode`,

  /**
   * GTİP numarası (12 hane, IHRACKAYITLI+702 için zorunlu)
   * Expected type: string | undefined
   */
  lineDeliveryGtipNo: (i: number) => `lines[${i}].delivery.gtipNo`,

  /**
   * Alıcı DİB Satır Kodu (11 hane, IHRACKAYITLI+702 için zorunlu — B-07). Mapper bu alanı Shipment/TransportHandlingUnit/CustomsDeclaration/ IssuerParty/PartyIdentification[schemeID='ALICIDIBSATIRKOD'] UBL ağacına eşler. Sprint 8c.2 / B-NEW-12 ile eklendi.
   * Expected type: string | undefined
   */
  lineDeliveryAlicidibsatirkod: (i: number) => `lines[${i}].delivery.alicidibsatirkod`,

  /**
   * Taşıma modu kodu (ör: "1" Deniz, "3" Karayolu, "4" Havayolu)
   * Expected type: string | undefined
   */
  lineDeliveryTransportModeCode: (i: number) => `lines[${i}].delivery.transportModeCode`,

  /**
   * Paket ID
   * Expected type: string | undefined
   */
  lineDeliveryPackageId: (i: number) => `lines[${i}].delivery.packageId`,

  /**
   * Paket miktarı
   * Expected type: number | undefined
   */
  lineDeliveryPackageQuantity: (i: number) => `lines[${i}].delivery.packageQuantity`,

  /**
   * Paket tipi kodu
   * Expected type: string | undefined
   */
  lineDeliveryPackageTypeCode: (i: number) => `lines[${i}].delivery.packageTypeCode`,

  /**
   * Harcama tipi kodu — YATIRIMTESVIK: 01=Makine/Teçhizat, 02=Yazılım, 03=Bina İnşaat, 04=Diğer
   * Expected type: string | undefined
   */
  lineItemClassificationCode: (i: number) => `lines[${i}].itemClassificationCode`,

  /**
   * Makine Teçhizat sıra no — YATIRIMTESVIK Kod 01 için zorunlu
   * Expected type: string | undefined
   */
  lineProductTraceId: (i: number) => `lines[${i}].productTraceId`,

  /**
   * Makine ID — YATIRIMTESVIK Kod 01 için zorunlu
   * Expected type: string | undefined
   */
  lineSerialId: (i: number) => `lines[${i}].serialId`,

  /**
   * Tanımlama şema tipi (ör: "TELEFON", "TABLET_PC")
   * Expected type: string
   */
  lineAdditionalItemIdentificationSchemeId: (i: number, ti: number) => `lines[${i}].additionalItemIdentifications[${ti}].schemeId`,

  /**
   * Tanımlama değeri
   * Expected type: string
   */
  lineAdditionalItemIdentificationValue: (i: number, ti: number) => `lines[${i}].additionalItemIdentifications[${ti}].value`,

  /**
   * Fatura numarası (ör: "ABC2025000000001") — opsiyonel, seri/numara sistemi için
   * Expected type: string | undefined
   */
  id: 'id',

  /**
   * Fatura UUID — opsiyonel, verilmezse otomatik üretilir
   * Expected type: string | undefined
   */
  uuid: 'uuid',

  /**
   * Fatura tarihi/saati (ISO format: "2025-01-15T10:30:00") — opsiyonel, verilmezse şimdiki zaman
   * Expected type: string | undefined
   */
  datetime: 'datetime',

  /**
   * Fatura tipi — opsiyonel. Verilmezse satır vergi durumlarına göre otomatik tespit edilir:   - Tevkifat varsa → TEVKIFAT   - KDV %0 ise ve istisna kodu verilmişse → ISTISNA / IHRACKAYITLI / OZELMATRAH   - Diğer → SATIS Manuel override: "SATIS" | "IADE" | "TEVKIFAT" | "ISTISNA" | "IHRACKAYITLI" | "OZELMATRAH" | "SGK"
   * Expected type: string | undefined
   */
  type: 'type',

  /**
   * Fatura profili — opsiyonel. Verilmezse otomatik tespit edilir. Manuel override: "TEMELFATURA" | "TICARIFATURA" | "EARSIVFATURA" | "IHRACAT" | "KAMU"
   * Expected type: string | undefined
   */
  profile: 'profile',

  /**
   * Para birimi kodu — varsayılan: "TRY"
   * Expected type: string | undefined
   */
  currencyCode: 'currencyCode',

  /**
   * Döviz kuru (TRY dışı para birimlerinde zorunlu)
   * Expected type: number | undefined
   */
  exchangeRate: 'exchangeRate',

  /**
   * KDV istisna kodu — ISTISNA, IHRACKAYITLI, OZELMATRAH tipleri için. İstisna kodları: 201-350 (istisna), 701-703 (ihraç kayıtlı), 801-812 (özel matrah)
   * Expected type: string | undefined
   */
  kdvExemptionCode: 'kdvExemptionCode',

  /**
   * Özel matrah KDV oranı
   * Expected type: number
   */
  ozelMatrahPercent: 'ozelMatrah.percent',

  /**
   * Özel matrah tutarı
   * Expected type: number
   */
  ozelMatrahTaxable: 'ozelMatrah.taxable',

  /**
   * Özel matrah KDV tutarı
   * Expected type: number
   */
  ozelMatrahAmount: 'ozelMatrah.amount',

  /**
   * Sipariş numarası
   * Expected type: string
   */
  orderReferenceId: 'orderReference.id',

  /**
   * Sipariş tarihi (ISO format: "2025-01-15")
   * Expected type: string
   */
  orderReferenceIssueDate: 'orderReference.issueDate',

  /**
   * Referans fatura numarası (Schematron: IADE grubu tiplerinde 16 karakter zorunlu)
   * Expected type: string
   */
  billingReferenceId: 'billingReference.id',

  /**
   * Referans fatura tarihi
   * Expected type: string
   */
  billingReferenceIssueDate: 'billingReference.issueDate',

  /**
   * Belge tipi kodu. - IADE grubu tiplerinde otomatik `'IADE'` atanır (Schematron zorunlu). - Diğer tiplerde serbest metin — Schematron kısıtlaması yoktur.
   * Expected type: string | undefined
   */
  billingReferenceDocumentTypeCode: 'billingReference.documentTypeCode',

  /**
   * İrsaliye numarası
   * Expected type: string
   */
  despatchReferenceId: (i: number) => `despatchReferences[${i}].id`,

  /**
   * İrsaliye tarihi
   * Expected type: string
   */
  despatchReferenceIssueDate: (i: number) => `despatchReferences[${i}].issueDate`,

  /**
   * Belge ID
   * Expected type: string
   */
  additionalDocumentId: (i: number) => `additionalDocuments[${i}].id`,

  /**
   * Belge tarihi
   * Expected type: string | undefined
   */
  additionalDocumentIssueDate: (i: number) => `additionalDocuments[${i}].issueDate`,

  /**
   * Belge tipi kodu
   * Expected type: string | undefined
   */
  additionalDocumentDocumentTypeCode: (i: number) => `additionalDocuments[${i}].documentTypeCode`,

  /**
   * Belge tipi
   * Expected type: string | undefined
   */
  additionalDocumentDocumentType: (i: number) => `additionalDocuments[${i}].documentType`,

  /**
   * Belge açıklaması
   * Expected type: string | undefined
   */
  additionalDocumentDocumentDescription: (i: number) => `additionalDocuments[${i}].documentDescription`,

  /**
   * Ödeme yöntemi kodu (ör: "1" Nakit, "42" Banka, "48" Kredi Kartı, "ZZZ" Diğer)
   * Expected type: string
   */
  paymentMeansMeansCode: 'paymentMeans.meansCode',

  /**
   * Son ödeme tarihi
   * Expected type: string | undefined
   */
  paymentMeansDueDate: 'paymentMeans.dueDate',

  /**
   * Ödeme kanalı kodu
   * Expected type: string | undefined
   */
  paymentMeansChannelCode: 'paymentMeans.channelCode',

  /**
   * Hesap numarası / IBAN
   * Expected type: string | undefined
   */
  paymentMeansAccountNumber: 'paymentMeans.accountNumber',

  /**
   * Ödeme notu
   * Expected type: string | undefined
   */
  paymentMeansPaymentNote: 'paymentMeans.paymentNote',

  /**
   * Fatura notları
   * Expected type: string[] | undefined
   */
  notes: 'notes',

  /**
   * Alıcı adı
   * Expected type: string
   */
  buyerCustomerName: 'buyerCustomer.name',

  /**
   * Vergi numarası veya kimlik numarası
   * Expected type: string
   */
  buyerCustomerTaxNumber: 'buyerCustomer.taxNumber',

  /**
   * Adres
   * Expected type: string
   */
  buyerCustomerAddress: 'buyerCustomer.address',

  /**
   * İl
   * Expected type: string
   */
  buyerCustomerCity: 'buyerCustomer.city',

  /**
   * İlçe
   * Expected type: string
   */
  buyerCustomerDistrict: 'buyerCustomer.district',

  /**
   * Ülke
   * Expected type: string
   */
  buyerCustomerCountry: 'buyerCustomer.country',

  /**
   * Posta kodu
   * Expected type: string | undefined
   */
  buyerCustomerZipCode: 'buyerCustomer.zipCode',

  /**
   * Telefon
   * Expected type: string | undefined
   */
  buyerCustomerPhone: 'buyerCustomer.phone',

  /**
   * E-posta
   * Expected type: string | undefined
   */
  buyerCustomerEmail: 'buyerCustomer.email',

  /**
   * Uyruk (ISO 3166-1 alpha-2 ülke kodu, ör. 'DE', 'US') — YOLCUBERABERFATURA profili için zorunlu (B-NEW-13 / Sprint 8c.4).
   * Expected type: string | undefined
   */
  buyerCustomerNationalityId: 'buyerCustomer.nationalityId',

  /**
   * Pasaport numarası — YOLCUBERABERFATURA profili için zorunlu (B-NEW-13).
   * Expected type: string | undefined
   */
  buyerCustomerPassportId: 'buyerCustomer.passportId',

  /**
   * ARACIKURUMVKN — VKN (10 hane) veya TCKN (11 hane)
   * Expected type: string
   */
  taxRepresentativePartyVknTckn: 'taxRepresentativeParty.vknTckn',

  /**
   * ARACIKURUMETIKET — aracı kurum etiket adı
   * Expected type: string
   */
  taxRepresentativePartyLabel: 'taxRepresentativeParty.label',

  /**
   * Aracı kurum tüzel adı (opsiyonel)
   * Expected type: string | undefined
   */
  taxRepresentativePartyName: 'taxRepresentativeParty.name',

  /**
   * SGK tipi — whitelist kontrolü runtime'da tetiklenir (B-NEW-09)
   * Expected type: 'SAGLIK_ECZ' | 'SAGLIK_HAS' | 'SAGLIK_OPT' | 'SAGLIK_MED' | 'ABONELIK' | 'MAL_HIZMET' | 'DIGER'
   */
  sgkType: 'sgk.type',

  /**
   * Döküm numarası — boş olamaz (B-NEW-10)
   * Expected type: string
   */
  sgkDocumentNo: 'sgk.documentNo',

  /**
   * Firma/Kurum adı
   * Expected type: string
   */
  sgkCompanyName: 'sgk.companyName',

  /**
   * Firma/Kurum sicil kodu
   * Expected type: string
   */
  sgkCompanyCode: 'sgk.companyCode',

  /**
   * Online satış mı?
   * Expected type: boolean
   */
  onlineSaleIsOnlineSale: 'onlineSale.isOnlineSale',

  /**
   * Mağaza URL'si
   * Expected type: string
   */
  onlineSaleStoreUrl: 'onlineSale.storeUrl',

  /**
   * Ödeme yöntemi (KREDIKARTI, BANKAHAVALESI, EFT, KAPIDAODEME vb.)
   * Expected type: string
   */
  onlineSalePaymentMethod: 'onlineSale.paymentMethod',

  /**
   * Ödeme tarihi
   * Expected type: string
   */
  onlineSalePaymentDate: 'onlineSale.paymentDate',

  /**
   * Kargo firma vergi numarası
   * Expected type: string | undefined
   */
  onlineSaleCarrierTaxNumber: 'onlineSale.carrierTaxNumber',

  /**
   * Kargo firma adı
   * Expected type: string | undefined
   */
  onlineSaleCarrierName: 'onlineSale.carrierName',

  /**
   * Teslimat tarihi
   * Expected type: string | undefined
   */
  onlineSaleDeliveryDate: 'onlineSale.deliveryDate',

  /**
   * Gönderim tipi: "ELEKTRONIK" veya "KAGIT"
   * Expected type: "ELEKTRONIK" | "KAGIT"
   */
  eArchiveInfoSendType: 'eArchiveInfo.sendType',

  /**
   * Dönem başlangıç tarihi (ISO format)
   * Expected type: string
   */
  invoicePeriodStartDate: 'invoicePeriod.startDate',

  /**
   * Dönem bitiş tarihi (ISO format)
   * Expected type: string
   */
  invoicePeriodEndDate: 'invoicePeriod.endDate',

  /**
   * Yatırım Teşvik Belgesi numarası (6 haneli numerik) — YATIRIMTESVIK profili için zorunlu
   * Expected type: string | undefined
   */
  ytbNo: 'ytbNo',

  /**
   * YTB belge tarihi (ISO format: "2025-01-15")
   * Expected type: string | undefined
   */
  ytbIssueDate: 'ytbIssueDate',

  /**
   * XSLT şablon (Base64) — fatura görsel şablonu
   * Expected type: string | undefined
   */
  xsltTemplate: 'xsltTemplate',

  /**
   * Customer liability (e-invoice / e-archive enrolment). Session-level state, not part of SimpleInvoiceInput. Note: ignored when session was created with isExport=true (M10 contract → LIABILITY_LOCKED_BY_EXPORT pathError).
   * Expected type: 'einvoice' | 'earchive' | undefined
   */
  liability: 'liability',
} as const;

export interface SessionPathMap {
  'sender.taxNumber': string;
  'sender.name': string;
  'sender.taxOffice': string | undefined;
  'sender.address': string;
  'sender.district': string;
  'sender.city': string;
  'sender.country': string | undefined;
  'sender.zipCode': string | undefined;
  'sender.phone': string | undefined;
  'sender.email': string | undefined;
  'sender.website': string | undefined;
  'sender.alias': string | undefined;
  'customer.taxNumber': string;
  'customer.name': string;
  'customer.taxOffice': string | undefined;
  'customer.address': string;
  'customer.district': string;
  'customer.city': string;
  'customer.country': string | undefined;
  'customer.zipCode': string | undefined;
  'customer.phone': string | undefined;
  'customer.email': string | undefined;
  'customer.website': string | undefined;
  'customer.alias': string | undefined;
  'lines[${number}].name': string;
  'lines[${number}].quantity': number;
  'lines[${number}].price': number;
  'lines[${number}].unitCode': string | undefined;
  'lines[${number}].kdvPercent': number;
  'lines[${number}].kdvExemptionCode': string | undefined;
  'lines[${number}].allowancePercent': number | undefined;
  'lines[${number}].taxes[${number}].code': string;
  'lines[${number}].taxes[${number}].percent': number;
  'lines[${number}].withholdingTaxCode': string | undefined;
  'lines[${number}].withholdingTaxPercent': number | undefined;
  'lines[${number}].description': string | undefined;
  'lines[${number}].brand': string | undefined;
  'lines[${number}].model': string | undefined;
  'lines[${number}].buyerCode': string | undefined;
  'lines[${number}].sellerCode': string | undefined;
  'lines[${number}].manufacturerCode': string | undefined;
  'lines[${number}].origin': string | undefined;
  'lines[${number}].note': string | undefined;
  'lines[${number}].delivery.deliveryTermCode': string | undefined;
  'lines[${number}].delivery.gtipNo': string | undefined;
  'lines[${number}].delivery.alicidibsatirkod': string | undefined;
  'lines[${number}].delivery.transportModeCode': string | undefined;
  'lines[${number}].delivery.packageId': string | undefined;
  'lines[${number}].delivery.packageQuantity': number | undefined;
  'lines[${number}].delivery.packageTypeCode': string | undefined;
  'lines[${number}].itemClassificationCode': string | undefined;
  'lines[${number}].productTraceId': string | undefined;
  'lines[${number}].serialId': string | undefined;
  'lines[${number}].additionalItemIdentifications[${number}].schemeId': string;
  'lines[${number}].additionalItemIdentifications[${number}].value': string;
  'id': string | undefined;
  'uuid': string | undefined;
  'datetime': string | undefined;
  'type': string | undefined;
  'profile': string | undefined;
  'currencyCode': string | undefined;
  'exchangeRate': number | undefined;
  'kdvExemptionCode': string | undefined;
  'ozelMatrah.percent': number;
  'ozelMatrah.taxable': number;
  'ozelMatrah.amount': number;
  'orderReference.id': string;
  'orderReference.issueDate': string;
  'billingReference.id': string;
  'billingReference.issueDate': string;
  'billingReference.documentTypeCode': string | undefined;
  'despatchReferences[${number}].id': string;
  'despatchReferences[${number}].issueDate': string;
  'additionalDocuments[${number}].id': string;
  'additionalDocuments[${number}].issueDate': string | undefined;
  'additionalDocuments[${number}].documentTypeCode': string | undefined;
  'additionalDocuments[${number}].documentType': string | undefined;
  'additionalDocuments[${number}].documentDescription': string | undefined;
  'paymentMeans.meansCode': string;
  'paymentMeans.dueDate': string | undefined;
  'paymentMeans.channelCode': string | undefined;
  'paymentMeans.accountNumber': string | undefined;
  'paymentMeans.paymentNote': string | undefined;
  'notes': string[] | undefined;
  'buyerCustomer.name': string;
  'buyerCustomer.taxNumber': string;
  'buyerCustomer.address': string;
  'buyerCustomer.city': string;
  'buyerCustomer.district': string;
  'buyerCustomer.country': string;
  'buyerCustomer.zipCode': string | undefined;
  'buyerCustomer.phone': string | undefined;
  'buyerCustomer.email': string | undefined;
  'buyerCustomer.nationalityId': string | undefined;
  'buyerCustomer.passportId': string | undefined;
  'taxRepresentativeParty.vknTckn': string;
  'taxRepresentativeParty.label': string;
  'taxRepresentativeParty.name': string | undefined;
  'sgk.type': 'SAGLIK_ECZ' | 'SAGLIK_HAS' | 'SAGLIK_OPT' | 'SAGLIK_MED' | 'ABONELIK' | 'MAL_HIZMET' | 'DIGER';
  'sgk.documentNo': string;
  'sgk.companyName': string;
  'sgk.companyCode': string;
  'onlineSale.isOnlineSale': boolean;
  'onlineSale.storeUrl': string;
  'onlineSale.paymentMethod': string;
  'onlineSale.paymentDate': string;
  'onlineSale.carrierTaxNumber': string | undefined;
  'onlineSale.carrierName': string | undefined;
  'onlineSale.deliveryDate': string | undefined;
  'eArchiveInfo.sendType': "ELEKTRONIK" | "KAGIT";
  'invoicePeriod.startDate': string;
  'invoicePeriod.endDate': string;
  'ytbNo': string | undefined;
  'ytbIssueDate': string | undefined;
  'xsltTemplate': string | undefined;
  'liability': 'einvoice' | 'earchive' | undefined;
}

export const KNOWN_PATH_TEMPLATES: ReadonlySet<string> = new Set([
  'additionalDocuments[*].documentDescription',
  'additionalDocuments[*].documentType',
  'additionalDocuments[*].documentTypeCode',
  'additionalDocuments[*].id',
  'additionalDocuments[*].issueDate',
  'billingReference.documentTypeCode',
  'billingReference.id',
  'billingReference.issueDate',
  'buyerCustomer.address',
  'buyerCustomer.city',
  'buyerCustomer.country',
  'buyerCustomer.district',
  'buyerCustomer.email',
  'buyerCustomer.name',
  'buyerCustomer.nationalityId',
  'buyerCustomer.passportId',
  'buyerCustomer.phone',
  'buyerCustomer.taxNumber',
  'buyerCustomer.zipCode',
  'currencyCode',
  'customer.address',
  'customer.alias',
  'customer.city',
  'customer.country',
  'customer.district',
  'customer.email',
  'customer.name',
  'customer.phone',
  'customer.taxNumber',
  'customer.taxOffice',
  'customer.website',
  'customer.zipCode',
  'datetime',
  'despatchReferences[*].id',
  'despatchReferences[*].issueDate',
  'eArchiveInfo.sendType',
  'exchangeRate',
  'id',
  'invoicePeriod.endDate',
  'invoicePeriod.startDate',
  'kdvExemptionCode',
  'liability',
  'lines[*].additionalItemIdentifications[*].schemeId',
  'lines[*].additionalItemIdentifications[*].value',
  'lines[*].allowancePercent',
  'lines[*].brand',
  'lines[*].buyerCode',
  'lines[*].delivery.alicidibsatirkod',
  'lines[*].delivery.deliveryTermCode',
  'lines[*].delivery.gtipNo',
  'lines[*].delivery.packageId',
  'lines[*].delivery.packageQuantity',
  'lines[*].delivery.packageTypeCode',
  'lines[*].delivery.transportModeCode',
  'lines[*].description',
  'lines[*].itemClassificationCode',
  'lines[*].kdvExemptionCode',
  'lines[*].kdvPercent',
  'lines[*].manufacturerCode',
  'lines[*].model',
  'lines[*].name',
  'lines[*].note',
  'lines[*].origin',
  'lines[*].price',
  'lines[*].productTraceId',
  'lines[*].quantity',
  'lines[*].sellerCode',
  'lines[*].serialId',
  'lines[*].taxes[*].code',
  'lines[*].taxes[*].percent',
  'lines[*].unitCode',
  'lines[*].withholdingTaxCode',
  'lines[*].withholdingTaxPercent',
  'notes',
  'onlineSale.carrierName',
  'onlineSale.carrierTaxNumber',
  'onlineSale.deliveryDate',
  'onlineSale.isOnlineSale',
  'onlineSale.paymentDate',
  'onlineSale.paymentMethod',
  'onlineSale.storeUrl',
  'orderReference.id',
  'orderReference.issueDate',
  'ozelMatrah.amount',
  'ozelMatrah.percent',
  'ozelMatrah.taxable',
  'paymentMeans.accountNumber',
  'paymentMeans.channelCode',
  'paymentMeans.dueDate',
  'paymentMeans.meansCode',
  'paymentMeans.paymentNote',
  'profile',
  'sender.address',
  'sender.alias',
  'sender.city',
  'sender.country',
  'sender.district',
  'sender.email',
  'sender.name',
  'sender.phone',
  'sender.taxNumber',
  'sender.taxOffice',
  'sender.website',
  'sender.zipCode',
  'sgk.companyCode',
  'sgk.companyName',
  'sgk.documentNo',
  'sgk.type',
  'taxRepresentativeParty.label',
  'taxRepresentativeParty.name',
  'taxRepresentativeParty.vknTckn',
  'type',
  'uuid',
  'xsltTemplate',
  'ytbIssueDate',
  'ytbNo',
]);

export const READ_ONLY_PATHS: ReadonlySet<string> = new Set([
  'isExport',
]);

