/**
 * Sprint 8e — Hardcoded scenario spec array'leri.
 *
 * Hedef: 164 valid + 108 invalid = 272 spec.
 *
 * Sprint disiplini: spec'ler explicit yazılır (generator fonksiyonları değil).
 * Diff-friendly, Berkay tek tek okuyabilir. Dosya ~1500+ satıra ulaşırsa
 * `specs/<profile>.ts` parçalara bölünür (Sprint 8e içi karar).
 *
 * Slug kuralı:
 *   - Valid invoice: `<profile-lowercase>-<type-lowercase>-<variantSlug>`
 *     Klasör: `valid/<profile-lowercase>/<slug>/`
 *   - Valid despatch: `<profile-lowercase>-<type-lowercase>-<variantSlug>`
 *     Klasör: `valid/<profile-lowercase>/<slug>/`
 *   - Invalid: `<error-code-slug>-<variantSlug>`
 *     Klasör: `invalid/<error-code-slug>/<slug>/`
 *     (`<error-code-slug>` = primaryCode lowercase'ed, `_` → `-`)
 */

import type { ValidSpec, InvalidSpec } from './scenario-spec';
import type { SimplePartyInput } from '../../src/calculator/simple-types';

/**
 * Tekrarı azaltmak için standart sender/customer template'leri.
 * Spec içinde `sender: STANDARD_SENDER` gibi kullanılır, override gereken
 * field'lar spread sonrası eklenir.
 */
const STANDARD_SENDER: SimplePartyInput = {
  taxNumber: '1234567890',
  name: 'Matrix Test Satıcı A.Ş.',
  taxOffice: 'Beşiktaş',
  address: 'Levent Mah. No:42',
  district: 'Beşiktaş',
  city: 'İstanbul',
};

const STANDARD_CUSTOMER: SimplePartyInput = {
  taxNumber: '9876543210',
  name: 'Matrix Test Alıcı Ltd.',
  taxOffice: 'Kadıköy',
  address: 'Bağdat Cad. No:100',
  district: 'Kadıköy',
  city: 'İstanbul',
};

/** KAMU profili için aracı kurum template'i (BuyerCustomerParty). */
const KAMU_BUYER_CUSTOMER = {
  name: 'Matrix Kamu Aracı Kurumu',
  taxNumber: '3333333333',
  address: 'Mevlana Bulvarı No:233',
  district: 'Çankaya',
  city: 'Ankara',
  country: 'Türkiye',
  identifications: [
    { schemeId: 'MUSTERINO', value: 'KAMU-MUSTERI-2026-MTX' },
  ],
};

/** KAMU profili için PaymentMeans template'i (TR IBAN). */
const KAMU_PAYMENT_MEANS = {
  meansCode: '42',
  accountNumber: 'TR330006100519786457841326',
  dueDate: '2026-05-24',
};

export const validSpecs: ValidSpec[] = [
  // ───────────────────────────────────────────────────────────────────────
  // TEMELFATURA — 32 senaryo (10 baseline + 12 tip-özel + 10 feature cross)
  // ───────────────────────────────────────────────────────────────────────

  // TEMELFATURA+SATIS — baseline + feature varyantları
  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TEMELFATURA',
    type: 'SATIS',
    notes: 'Baseline — TEMELFATURA+SATIS, tek satır %20 KDV, TRY',
    dimensions: {
      kdvBreakdown: [20],
      currency: 'TRY',
      exchangeRate: false,
      exemptionCodes: [],
      withholdingCodes: [],
      allowanceCharge: { line: false, document: false },
      lineCount: 1,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000001',
      uuid: 'a1000001-0001-4000-8001-000000000001',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'SATIS',
      currencyCode: 'TRY',
      sender: {
        taxNumber: '1234567890',
        name: 'Matrix Test Satıcı A.Ş.',
        taxOffice: 'Beşiktaş',
        address: 'Levent Mah. No:42',
        district: 'Beşiktaş',
        city: 'İstanbul',
      },
      customer: {
        taxNumber: '9876543210',
        name: 'Matrix Test Alıcı Ltd.',
        taxOffice: 'Kadıköy',
        address: 'Bağdat Cad. No:100',
        district: 'Kadıköy',
        city: 'İstanbul',
      },
      lines: [
        {
          name: 'Demo hizmet — %20 KDV',
          quantity: 1,
          price: 1000,
          unitCode: 'Adet',
          kdvPercent: 20,
        },
      ],
    },
  },
  {
    kind: 'invoice',
    variantSlug: 'coklu-kdv',
    profile: 'TEMELFATURA',
    type: 'SATIS',
    notes: 'Çoklu satır — karışık KDV oranları (%0 kodsuz 351, %10, %20)',
    dimensions: {
      kdvBreakdown: [0, 10, 20],
      currency: 'TRY',
      exchangeRate: false,
      exemptionCodes: ['351'],
      withholdingCodes: [],
      allowanceCharge: { line: false, document: false },
      lineCount: 3,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000002',
      uuid: 'a1000002-0001-4000-8001-000000000002',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'SATIS',
      currencyCode: 'TRY',
      kdvExemptionCode: '351',
      sender: {
        taxNumber: '1234567890',
        name: 'Matrix Test Satıcı A.Ş.',
        taxOffice: 'Beşiktaş',
        address: 'Levent Mah. No:42',
        district: 'Beşiktaş',
        city: 'İstanbul',
      },
      customer: {
        taxNumber: '9876543210',
        name: 'Matrix Test Alıcı Ltd.',
        taxOffice: 'Kadıköy',
        address: 'Bağdat Cad. No:100',
        district: 'Kadıköy',
        city: 'İstanbul',
      },
      lines: [
        {
          name: 'İstisnalı hizmet — %0 (351)',
          quantity: 1,
          price: 500,
          unitCode: 'Adet',
          kdvPercent: 0,
        },
        {
          name: 'İndirimli ürün — %10',
          quantity: 2,
          price: 250,
          unitCode: 'Adet',
          kdvPercent: 10,
        },
        {
          name: 'Genel hizmet — %20',
          quantity: 1,
          price: 1000,
          unitCode: 'Adet',
          kdvPercent: 20,
        },
      ],
    },
  },
  {
    kind: 'invoice',
    variantSlug: 'eur-doviz',
    profile: 'TEMELFATURA',
    type: 'SATIS',
    notes: 'Yabancı para birimi — EUR + ExchangeRate 35.5',
    dimensions: {
      kdvBreakdown: [20],
      currency: 'EUR',
      exchangeRate: true,
      exemptionCodes: [],
      withholdingCodes: [],
      allowanceCharge: { line: false, document: false },
      lineCount: 1,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000003',
      uuid: 'a1000003-0001-4000-8001-000000000003',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'SATIS',
      currencyCode: 'EUR',
      exchangeRate: 35.5,
      sender: {
        taxNumber: '1234567890',
        name: 'Matrix Test Satıcı A.Ş.',
        taxOffice: 'Beşiktaş',
        address: 'Levent Mah. No:42',
        district: 'Beşiktaş',
        city: 'İstanbul',
      },
      customer: {
        taxNumber: '9876543210',
        name: 'Matrix Test Alıcı Ltd.',
        taxOffice: 'Kadıköy',
        address: 'Bağdat Cad. No:100',
        district: 'Kadıköy',
        city: 'İstanbul',
      },
      lines: [
        {
          name: 'Yazılım lisansı — EUR ödeme',
          quantity: 1,
          price: 1000,
          unitCode: 'Adet',
          kdvPercent: 20,
        },
      ],
    },
  },

  // TEMELFATURA+IADE baseline — BillingReference zorunlu
  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TEMELFATURA',
    type: 'IADE',
    notes: 'Baseline — TEMELFATURA+IADE, orijinal faturaya referans (BillingReference zorunlu)',
    dimensions: {
      kdvBreakdown: [20],
      currency: 'TRY',
      exchangeRate: false,
      exemptionCodes: [],
      withholdingCodes: [],
      allowanceCharge: { line: false, document: false },
      lineCount: 1,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: ['billingReference'],
    },
    input: {
      id: 'MTX2026000000004',
      uuid: 'a1000004-0001-4000-8001-000000000004',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'IADE',
      currencyCode: 'TRY',
      billingReference: {
        id: 'MTX2026000000001',
        issueDate: '2026-04-24',
      },
      sender: {
        taxNumber: '1234567890',
        name: 'Matrix Test Satıcı A.Ş.',
        taxOffice: 'Beşiktaş',
        address: 'Levent Mah. No:42',
        district: 'Beşiktaş',
        city: 'İstanbul',
      },
      customer: {
        taxNumber: '9876543210',
        name: 'Matrix Test Alıcı Ltd.',
        taxOffice: 'Kadıköy',
        address: 'Bağdat Cad. No:100',
        district: 'Kadıköy',
        city: 'İstanbul',
      },
      lines: [
        {
          name: 'İade edilen hizmet',
          quantity: 1,
          price: 1000,
          unitCode: 'Adet',
          kdvPercent: 20,
        },
      ],
    },
  },

  // TEMELFATURA+TEVKIFAT baseline — withholdingTaxCode zorunlu
  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TEMELFATURA',
    type: 'TEVKIFAT',
    notes: 'Baseline — TEMELFATURA+TEVKIFAT, kod 603 (%70 bakım-onarım)',
    dimensions: {
      kdvBreakdown: [20],
      currency: 'TRY',
      exchangeRate: false,
      exemptionCodes: [],
      withholdingCodes: ['603'],
      allowanceCharge: { line: false, document: false },
      lineCount: 1,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000005',
      uuid: 'a1000005-0001-4000-8001-000000000005',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'TEVKIFAT',
      currencyCode: 'TRY',
      sender: {
        taxNumber: '1234567890',
        name: 'Matrix Test Satıcı A.Ş.',
        taxOffice: 'Beşiktaş',
        address: 'Levent Mah. No:42',
        district: 'Beşiktaş',
        city: 'İstanbul',
      },
      customer: {
        taxNumber: '9876543210',
        name: 'Matrix Test Alıcı Ltd.',
        taxOffice: 'Kadıköy',
        address: 'Bağdat Cad. No:100',
        district: 'Kadıköy',
        city: 'İstanbul',
      },
      lines: [
        {
          name: 'Bakım-onarım hizmeti — %70 tevkifat',
          quantity: 1,
          price: 1000,
          unitCode: 'Adet',
          kdvPercent: 20,
          withholdingTaxCode: '603',
        },
      ],
    },
  },

  // TEMELFATURA+TEVKIFATIADE baseline — Bulunan Bug #1 nedeniyle geçici olarak kaldırıldı.
  // Bug: `WITHHOLDING_ALLOWED_TYPES` (src/config/constants.ts:77) listesinde TEVKIFATIADE
  // ve YTBTEVKIFATIADE yok. Satırdaki `withholdingTaxCode`, builder tarafından
  // `input.withholdingTaxTotals`'a otomatik eklenir; sonra type-validators.ts:33 bu
  // listede olmayan tip için INVALID_VALUE hatası atar. Düzeltme Sprint 8f'te.
  // Detay: audit/sprint-08e-implementation-log.md — Bulunan Buglar.

  // TEMELFATURA+ISTISNA baseline — 213 (gemi/uçak yakıt/bakım istisnası)
  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TEMELFATURA',
    type: 'ISTISNA',
    notes: 'Baseline — TEMELFATURA+ISTISNA, kod 213 (deniz/hava taşıtları için yapılan tadil)',
    dimensions: {
      kdvBreakdown: [0],
      currency: 'TRY',
      exchangeRate: false,
      exemptionCodes: ['213'],
      withholdingCodes: [],
      allowanceCharge: { line: false, document: false },
      lineCount: 1,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000007',
      uuid: 'a1000007-0001-4000-8001-000000000007',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'ISTISNA',
      currencyCode: 'TRY',
      kdvExemptionCode: '213',
      sender: {
        taxNumber: '1234567890',
        name: 'Matrix Test Satıcı A.Ş.',
        taxOffice: 'Beşiktaş',
        address: 'Levent Mah. No:42',
        district: 'Beşiktaş',
        city: 'İstanbul',
      },
      customer: {
        taxNumber: '9876543210',
        name: 'Matrix Test Alıcı Ltd.',
        taxOffice: 'Kadıköy',
        address: 'Bağdat Cad. No:100',
        district: 'Kadıköy',
        city: 'İstanbul',
      },
      lines: [
        {
          name: 'Deniz taşıtı tadil hizmeti',
          quantity: 1,
          price: 1000,
          unitCode: 'Adet',
          kdvPercent: 0,
        },
      ],
    },
  },

  // TEMELFATURA+OZELMATRAH baseline — 801 (kullanılmış binek otomobil)
  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TEMELFATURA',
    type: 'OZELMATRAH',
    notes: 'Baseline — TEMELFATURA+OZELMATRAH, kod 801 (kullanılmış binek otomobil KDV)',
    dimensions: {
      kdvBreakdown: [0],
      currency: 'TRY',
      exchangeRate: false,
      exemptionCodes: ['801'],
      withholdingCodes: [],
      allowanceCharge: { line: false, document: false },
      lineCount: 1,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: ['ozelMatrah'],
    },
    input: {
      id: 'MTX2026000000008',
      uuid: 'a1000008-0001-4000-8001-000000000008',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'OZELMATRAH',
      currencyCode: 'TRY',
      kdvExemptionCode: '801',
      ozelMatrah: {
        percent: 18,
        taxable: 500,
        amount: 90,
      },
      sender: {
        taxNumber: '1234567890',
        name: 'Matrix Test Oto A.Ş.',
        taxOffice: 'Beşiktaş',
        address: 'Levent Mah. No:42',
        district: 'Beşiktaş',
        city: 'İstanbul',
      },
      customer: {
        taxNumber: '9876543210',
        name: 'Matrix Test Alıcı Ltd.',
        taxOffice: 'Kadıköy',
        address: 'Bağdat Cad. No:100',
        district: 'Kadıköy',
        city: 'İstanbul',
      },
      lines: [
        {
          name: '2019 Model İkinci El Binek Otomobil',
          quantity: 1,
          price: 1000,
          unitCode: 'Adet',
          kdvPercent: 0,
        },
      ],
    },
  },

  // TEMELFATURA+IHRACKAYITLI baseline — 702 (DİİB) + GTİP + ALICIDIBKOD
  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TEMELFATURA',
    type: 'IHRACKAYITLI',
    notes: 'Baseline — TEMELFATURA+IHRACKAYITLI, kod 702 (DİİB) + GTİP 12 hane + ALICIDIBKOD 11 hane',
    dimensions: {
      kdvBreakdown: [0],
      currency: 'TRY',
      exchangeRate: false,
      exemptionCodes: ['702'],
      withholdingCodes: [],
      allowanceCharge: { line: false, document: false },
      lineCount: 1,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: ['gtip', 'alicidibkod'],
    },
    input: {
      id: 'MTX2026000000009',
      uuid: 'a1000009-0001-4000-8001-000000000009',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'IHRACKAYITLI',
      currencyCode: 'TRY',
      kdvExemptionCode: '702',
      sender: {
        taxNumber: '1234567890',
        name: 'Matrix Test İhracatçı A.Ş.',
        taxOffice: 'Beşiktaş',
        address: 'Levent Mah. No:42',
        district: 'Beşiktaş',
        city: 'İstanbul',
      },
      customer: {
        taxNumber: '9876543210',
        name: 'Matrix Test Aracı İhracat A.Ş.',
        taxOffice: 'Kadıköy',
        address: 'Bağdat Cad. No:100',
        district: 'Kadıköy',
        city: 'İstanbul',
      },
      lines: [
        {
          name: 'İhraç kayıtlı tekstil ürünü',
          quantity: 10,
          price: 100,
          unitCode: 'Adet',
          kdvPercent: 0,
          delivery: {
            gtipNo: '620342000010',
            alicidibsatirkod: '12345678901',
            deliveryAddress: {
              address: 'İhracat Serbest Bölgesi',
              district: 'Ambarlı',
              city: 'İstanbul',
              country: 'Türkiye',
            },
          },
        },
      ],
    },
  },

  // TEMELFATURA+SGK baseline — sgk objesi zorunlu
  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TEMELFATURA',
    type: 'SGK',
    notes: 'Baseline — TEMELFATURA+SGK, SAGLIK_ECZ (eczane reçetesi)',
    dimensions: {
      kdvBreakdown: [20],
      currency: 'TRY',
      exchangeRate: false,
      exemptionCodes: [],
      withholdingCodes: [],
      allowanceCharge: { line: false, document: false },
      lineCount: 1,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: ['sgk'],
    },
    input: {
      id: 'MTX2026000000010',
      uuid: 'a1000010-0001-4000-8001-000000000010',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'SGK',
      currencyCode: 'TRY',
      sgk: {
        type: 'SAGLIK_ECZ',
        documentNo: 'SGK-ECZ-2026-MTX001',
        companyName: 'Matrix Test Eczane Ltd.',
        companyCode: 'SGK-COMP-MTX',
      },
      sender: {
        taxNumber: '1234567890',
        name: 'Matrix Test Eczane Ltd.',
        taxOffice: 'Beşiktaş',
        address: 'Levent Mah. No:42',
        district: 'Beşiktaş',
        city: 'İstanbul',
      },
      customer: {
        taxNumber: '9876543210',
        name: 'Sosyal Güvenlik Kurumu',
        taxOffice: 'Kadıköy',
        address: 'SGK Bölge Müdürlüğü',
        district: 'Kadıköy',
        city: 'İstanbul',
      },
      lines: [
        {
          name: 'Reçeteli ilaç',
          quantity: 10,
          price: 100,
          unitCode: 'Adet',
          kdvPercent: 20,
        },
      ],
    },
  },

  // TEMELFATURA+KOMISYONCU baseline
  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TEMELFATURA',
    type: 'KOMISYONCU',
    notes: 'Baseline — TEMELFATURA+KOMISYONCU, komisyoncu satış',
    dimensions: {
      kdvBreakdown: [20],
      currency: 'TRY',
      exchangeRate: false,
      exemptionCodes: [],
      withholdingCodes: [],
      allowanceCharge: { line: false, document: false },
      lineCount: 1,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000011',
      uuid: 'a1000011-0001-4000-8001-000000000011',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'KOMISYONCU',
      currencyCode: 'TRY',
      sender: {
        taxNumber: '1234567890',
        name: 'Matrix Test Komisyoncu A.Ş.',
        taxOffice: 'Beşiktaş',
        address: 'Levent Mah. No:42',
        district: 'Beşiktaş',
        city: 'İstanbul',
      },
      customer: {
        taxNumber: '9876543210',
        name: 'Matrix Test Alıcı Ltd.',
        taxOffice: 'Kadıköy',
        address: 'Bağdat Cad. No:100',
        district: 'Kadıköy',
        city: 'İstanbul',
      },
      lines: [
        {
          name: 'Komisyoncu hizmet bedeli',
          quantity: 1,
          price: 1000,
          unitCode: 'Adet',
          kdvPercent: 20,
        },
      ],
    },
  },

  // TEMELFATURA+KONAKLAMAVERGISI baseline
  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TEMELFATURA',
    type: 'KONAKLAMAVERGISI',
    notes: 'Baseline — TEMELFATURA+KONAKLAMAVERGISI, konaklama vergisi',
    dimensions: {
      kdvBreakdown: [20],
      currency: 'TRY',
      exchangeRate: false,
      exemptionCodes: [],
      withholdingCodes: [],
      allowanceCharge: { line: false, document: false },
      lineCount: 1,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: ['accommodationTax'],
    },
    input: {
      id: 'MTX2026000000012',
      uuid: 'a1000012-0001-4000-8001-000000000012',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'KONAKLAMAVERGISI',
      currencyCode: 'TRY',
      sender: {
        taxNumber: '1234567890',
        name: 'Matrix Test Otel A.Ş.',
        taxOffice: 'Beşiktaş',
        address: 'Levent Mah. No:42',
        district: 'Beşiktaş',
        city: 'İstanbul',
      },
      customer: {
        taxNumber: '9876543210',
        name: 'Matrix Test Misafir A.Ş.',
        taxOffice: 'Kadıköy',
        address: 'Bağdat Cad. No:100',
        district: 'Kadıköy',
        city: 'İstanbul',
      },
      lines: [
        {
          name: 'Konaklama — 2 gece',
          quantity: 2,
          price: 500,
          unitCode: 'Gece',
          kdvPercent: 20,
        },
      ],
    },
  },

  // ─── TEMELFATURA Tip-özel varyantlar + feature cross (8e.3) ───
  // TEMELFATURA+ISTISNA kod 201 — diplomatik istisna
  {
    kind: 'invoice',
    variantSlug: 'kod-201',
    profile: 'TEMELFATURA',
    type: 'ISTISNA',
    notes: 'İstisna kodu 201 — diplomatik temsilci/konsolosluk',
    dimensions: {
      kdvBreakdown: [0],
      currency: 'TRY',
      exchangeRate: false,
      exemptionCodes: ['201'],
      withholdingCodes: [],
      allowanceCharge: { line: false, document: false },
      lineCount: 1,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000013',
      uuid: 'a1000013-0001-4000-8001-000000000013',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'ISTISNA',
      currencyCode: 'TRY',
      kdvExemptionCode: '201',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER, name: 'Matrix Diplomatik Temsilci' },
      lines: [
        {
          name: 'Diplomatik hizmet',
          quantity: 1,
          price: 1000,
          unitCode: 'Adet',
          kdvPercent: 0,
        },
      ],
    },
  },

  // TEMELFATURA+ISTISNA kod 301 — Türkiye dışı teslim
  {
    kind: 'invoice',
    variantSlug: 'kod-301',
    profile: 'TEMELFATURA',
    type: 'ISTISNA',
    notes: 'İstisna kodu 301 — Türkiye dışında gerçekleşen ifa',
    dimensions: {
      kdvBreakdown: [0],
      currency: 'TRY',
      exchangeRate: false,
      exemptionCodes: ['301'],
      withholdingCodes: [],
      allowanceCharge: { line: false, document: false },
      lineCount: 1,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000014',
      uuid: 'a1000014-0001-4000-8001-000000000014',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'ISTISNA',
      currencyCode: 'TRY',
      kdvExemptionCode: '301',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [
        {
          name: 'Yurt dışı danışmanlık',
          quantity: 1,
          price: 1000,
          unitCode: 'Adet',
          kdvPercent: 0,
        },
      ],
    },
  },

  // TEMELFATURA+TEVKIFAT 650 dinamik stopaj %50
  {
    kind: 'invoice',
    variantSlug: 'dinamik-650',
    profile: 'TEMELFATURA',
    type: 'TEVKIFAT',
    notes: 'TEVKIFAT + 650 dinamik kod, kullanıcı belirlediği %50 oran',
    dimensions: {
      kdvBreakdown: [20],
      currency: 'TRY',
      exchangeRate: false,
      exemptionCodes: [],
      withholdingCodes: ['650'],
      allowanceCharge: { line: false, document: false },
      lineCount: 1,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000015',
      uuid: 'a1000015-0001-4000-8001-000000000015',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'TEVKIFAT',
      currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [
        {
          name: 'Dinamik tevkifatlı hizmet',
          quantity: 1,
          price: 1000,
          unitCode: 'Adet',
          kdvPercent: 20,
          withholdingTaxCode: '650',
          withholdingTaxPercent: 50,
        },
      ],
    },
  },

  // TEMELFATURA+SATIS USD döviz
  {
    kind: 'invoice',
    variantSlug: 'usd-doviz',
    profile: 'TEMELFATURA',
    type: 'SATIS',
    notes: 'Yabancı para birimi — USD + ExchangeRate 32.1',
    dimensions: {
      kdvBreakdown: [20],
      currency: 'USD',
      exchangeRate: true,
      exemptionCodes: [],
      withholdingCodes: [],
      allowanceCharge: { line: false, document: false },
      lineCount: 1,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000016',
      uuid: 'a1000016-0001-4000-8001-000000000016',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'SATIS',
      currencyCode: 'USD',
      exchangeRate: 32.1,
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [
        {
          name: 'USD ödeme — yazılım hizmeti',
          quantity: 1,
          price: 500,
          unitCode: 'Adet',
          kdvPercent: 20,
        },
      ],
    },
  },

  // TEMELFATURA+SATIS çoklu satır tek KDV
  {
    kind: 'invoice',
    variantSlug: 'coklu-satir',
    profile: 'TEMELFATURA',
    type: 'SATIS',
    notes: 'Çoklu satır — 3 satır aynı KDV %20',
    dimensions: {
      kdvBreakdown: [20],
      currency: 'TRY',
      exchangeRate: false,
      exemptionCodes: [],
      withholdingCodes: [],
      allowanceCharge: { line: false, document: false },
      lineCount: 3,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000017',
      uuid: 'a1000017-0001-4000-8001-000000000017',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'SATIS',
      currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [
        { name: 'Ürün A', quantity: 1, price: 100, unitCode: 'Adet', kdvPercent: 20 },
        { name: 'Ürün B', quantity: 2, price: 200, unitCode: 'Adet', kdvPercent: 20 },
        { name: 'Ürün C', quantity: 5, price: 50, unitCode: 'Adet', kdvPercent: 20 },
      ],
    },
  },

  // TEMELFATURA+SATIS Note + OrderReference
  {
    kind: 'invoice',
    variantSlug: 'not-siparis',
    profile: 'TEMELFATURA',
    type: 'SATIS',
    notes: 'Fatura notları + OrderReference + DespatchReference referansları',
    dimensions: {
      kdvBreakdown: [20],
      currency: 'TRY',
      exchangeRate: false,
      exemptionCodes: [],
      withholdingCodes: [],
      allowanceCharge: { line: false, document: false },
      lineCount: 1,
      paymentMeans: false,
      reducedKdvGate: false,
      phantomKdv: false,
      specialIdentifiers: ['orderReference', 'despatchReference'],
    },
    input: {
      id: 'MTX2026000000018',
      uuid: 'a1000018-0001-4000-8001-000000000018',
      datetime: '2026-04-24T10:00:00',
      profile: 'TEMELFATURA',
      type: 'SATIS',
      currencyCode: 'TRY',
      notes: [
        'Sözleşme no: SOZ-2026-0042',
        'Ödeme: 30 gün vadeli',
      ],
      orderReference: {
        id: 'ORD-2026-0042',
        issueDate: '2026-04-20',
      },
      despatchReferences: [
        { id: 'IRS-2026-001', issueDate: '2026-04-22' },
      ],
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [
        {
          name: 'Sözleşme kapsamı hizmet',
          quantity: 1,
          price: 1000,
          unitCode: 'Adet',
          kdvPercent: 20,
        },
      ],
    },
  },

  // ═════════════════════════════════════════════════════════════════════
  // TICARIFATURA — 8 baseline (SATIS/TEVKIFAT/~TEVKIFATIADE~/ISTISNA/
  // OZELMATRAH/IHRACKAYITLI/SGK/KOMISYONCU/KONAKLAMAVERGISI)
  // NOTE: Plan 23 hedefinden %35 (TEVKIFATIADE Bug#1 nedeniyle hariç)
  // ═════════════════════════════════════════════════════════════════════

  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TICARIFATURA',
    type: 'SATIS',
    notes: 'Baseline — TICARIFATURA+SATIS, tek satır %20',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000020',
      uuid: 'a1000020-0001-4000-8001-000000000020',
      datetime: '2026-04-24T10:00:00',
      profile: 'TICARIFATURA', type: 'SATIS', currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'Ticari satış', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 20 }],
    },
  },
  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TICARIFATURA',
    type: 'TEVKIFAT',
    notes: 'Baseline — TICARIFATURA+TEVKIFAT, kod 620 (%50 tekstil)',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: ['620'], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000021',
      uuid: 'a1000021-0001-4000-8001-000000000021',
      datetime: '2026-04-24T10:00:00',
      profile: 'TICARIFATURA', type: 'TEVKIFAT', currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'Tekstil ürünü', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 20, withholdingTaxCode: '620' }],
    },
  },
  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TICARIFATURA',
    type: 'ISTISNA',
    notes: 'Baseline — TICARIFATURA+ISTISNA, kod 213',
    dimensions: {
      kdvBreakdown: [0], currency: 'TRY', exchangeRate: false, exemptionCodes: ['213'],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000022',
      uuid: 'a1000022-0001-4000-8001-000000000022',
      datetime: '2026-04-24T10:00:00',
      profile: 'TICARIFATURA', type: 'ISTISNA', currencyCode: 'TRY',
      kdvExemptionCode: '213',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'Deniz taşıtı hizmeti', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 0 }],
    },
  },
  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TICARIFATURA',
    type: 'OZELMATRAH',
    notes: 'Baseline — TICARIFATURA+OZELMATRAH, kod 801',
    dimensions: {
      kdvBreakdown: [0], currency: 'TRY', exchangeRate: false, exemptionCodes: ['801'],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['ozelMatrah'],
    },
    input: {
      id: 'MTX2026000000023',
      uuid: 'a1000023-0001-4000-8001-000000000023',
      datetime: '2026-04-24T10:00:00',
      profile: 'TICARIFATURA', type: 'OZELMATRAH', currencyCode: 'TRY',
      kdvExemptionCode: '801',
      ozelMatrah: { percent: 18, taxable: 500, amount: 90 },
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'İkinci el oto', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 0 }],
    },
  },
  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TICARIFATURA',
    type: 'IHRACKAYITLI',
    notes: 'Baseline — TICARIFATURA+IHRACKAYITLI, kod 702 + GTİP + ALICIDIBKOD',
    dimensions: {
      kdvBreakdown: [0], currency: 'TRY', exchangeRate: false, exemptionCodes: ['702'],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['gtip', 'alicidibkod'],
    },
    input: {
      id: 'MTX2026000000024',
      uuid: 'a1000024-0001-4000-8001-000000000024',
      datetime: '2026-04-24T10:00:00',
      profile: 'TICARIFATURA', type: 'IHRACKAYITLI', currencyCode: 'TRY',
      kdvExemptionCode: '702',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{
        name: 'İhraç kayıtlı ürün', quantity: 10, price: 100, unitCode: 'Adet', kdvPercent: 0,
        delivery: {
          gtipNo: '620342000010', alicidibsatirkod: '12345678901',
          deliveryAddress: { address: 'Liman', district: 'Ambarlı', city: 'İstanbul', country: 'Türkiye' },
        },
      }],
    },
  },
  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TICARIFATURA',
    type: 'SGK',
    notes: 'Baseline — TICARIFATURA+SGK, SAGLIK_OPT (optik)',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['sgk'],
    },
    input: {
      id: 'MTX2026000000025',
      uuid: 'a1000025-0001-4000-8001-000000000025',
      datetime: '2026-04-24T10:00:00',
      profile: 'TICARIFATURA', type: 'SGK', currencyCode: 'TRY',
      sgk: { type: 'SAGLIK_OPT', documentNo: 'SGK-OPT-MTX025', companyName: 'Matrix Optik', companyCode: 'SGK-OPT-MTX' },
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'Gözlük çerçevesi', quantity: 1, price: 500, unitCode: 'Adet', kdvPercent: 20 }],
    },
  },
  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TICARIFATURA',
    type: 'KOMISYONCU',
    notes: 'Baseline — TICARIFATURA+KOMISYONCU',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000026',
      uuid: 'a1000026-0001-4000-8001-000000000026',
      datetime: '2026-04-24T10:00:00',
      profile: 'TICARIFATURA', type: 'KOMISYONCU', currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'Komisyon hizmet', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 20 }],
    },
  },
  {
    kind: 'invoice',
    variantSlug: 'baseline',
    profile: 'TICARIFATURA',
    type: 'KONAKLAMAVERGISI',
    notes: 'Baseline — TICARIFATURA+KONAKLAMAVERGISI',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000027',
      uuid: 'a1000027-0001-4000-8001-000000000027',
      datetime: '2026-04-24T10:00:00',
      profile: 'TICARIFATURA', type: 'KONAKLAMAVERGISI', currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'Konaklama — 3 gece', quantity: 3, price: 500, unitCode: 'Gece', kdvPercent: 20 }],
    },
  },

  // ═════════════════════════════════════════════════════════════════════
  // KAMU — 8 baseline (PaymentMeans + IBAN + BuyerCustomer zorunlu)
  // ═════════════════════════════════════════════════════════════════════

  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'KAMU', type: 'SATIS',
    notes: 'Baseline — KAMU+SATIS, PaymentMeans + IBAN + aracı kurum',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: true, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['buyerCustomer', 'iban'],
    },
    input: {
      id: 'MTX2026000000030',
      uuid: 'a1000030-0001-4000-8001-000000000030',
      datetime: '2026-04-24T10:00:00',
      profile: 'KAMU', type: 'SATIS', currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER, taxNumber: '1460415308', name: 'T.C. Kamu Alıcı Kurumu' },
      buyerCustomer: { ...KAMU_BUYER_CUSTOMER },
      paymentMeans: { ...KAMU_PAYMENT_MEANS },
      lines: [{ name: 'Kamu tedarik', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 20 }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'KAMU', type: 'TEVKIFAT',
    notes: 'Baseline — KAMU+TEVKIFAT, kod 603',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: ['603'], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: true, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['buyerCustomer', 'iban'],
    },
    input: {
      id: 'MTX2026000000031',
      uuid: 'a1000031-0001-4000-8001-000000000031',
      datetime: '2026-04-24T10:00:00',
      profile: 'KAMU', type: 'TEVKIFAT', currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER, taxNumber: '1460415308', name: 'T.C. Kamu Kurumu' },
      buyerCustomer: { ...KAMU_BUYER_CUSTOMER },
      paymentMeans: { ...KAMU_PAYMENT_MEANS },
      lines: [{ name: 'Tevkifatlı kamu hizmeti', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 20, withholdingTaxCode: '603' }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'KAMU', type: 'ISTISNA',
    notes: 'Baseline — KAMU+ISTISNA, kod 213',
    dimensions: {
      kdvBreakdown: [0], currency: 'TRY', exchangeRate: false, exemptionCodes: ['213'],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: true, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['buyerCustomer', 'iban'],
    },
    input: {
      id: 'MTX2026000000032',
      uuid: 'a1000032-0001-4000-8001-000000000032',
      datetime: '2026-04-24T10:00:00',
      profile: 'KAMU', type: 'ISTISNA', currencyCode: 'TRY',
      kdvExemptionCode: '213',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER, taxNumber: '1460415308', name: 'T.C. Kamu Kurumu' },
      buyerCustomer: { ...KAMU_BUYER_CUSTOMER },
      paymentMeans: { ...KAMU_PAYMENT_MEANS },
      lines: [{ name: 'İstisnalı kamu hizmet', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 0 }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'KAMU', type: 'OZELMATRAH',
    notes: 'Baseline — KAMU+OZELMATRAH, kod 801',
    dimensions: {
      kdvBreakdown: [0], currency: 'TRY', exchangeRate: false, exemptionCodes: ['801'],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: true, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['ozelMatrah', 'buyerCustomer', 'iban'],
    },
    input: {
      id: 'MTX2026000000033',
      uuid: 'a1000033-0001-4000-8001-000000000033',
      datetime: '2026-04-24T10:00:00',
      profile: 'KAMU', type: 'OZELMATRAH', currencyCode: 'TRY',
      kdvExemptionCode: '801',
      ozelMatrah: { percent: 18, taxable: 500, amount: 90 },
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER, taxNumber: '1460415308', name: 'T.C. Kamu Kurumu' },
      buyerCustomer: { ...KAMU_BUYER_CUSTOMER },
      paymentMeans: { ...KAMU_PAYMENT_MEANS },
      lines: [{ name: 'Özel matrah', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 0 }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'KAMU', type: 'IHRACKAYITLI',
    notes: 'Baseline — KAMU+IHRACKAYITLI, kod 702 + GTİP + ALICIDIBKOD',
    dimensions: {
      kdvBreakdown: [0], currency: 'TRY', exchangeRate: false, exemptionCodes: ['702'],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: true, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['gtip', 'alicidibkod', 'buyerCustomer', 'iban'],
    },
    input: {
      id: 'MTX2026000000034',
      uuid: 'a1000034-0001-4000-8001-000000000034',
      datetime: '2026-04-24T10:00:00',
      profile: 'KAMU', type: 'IHRACKAYITLI', currencyCode: 'TRY',
      kdvExemptionCode: '702',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER, taxNumber: '1460415308', name: 'T.C. Kamu Kurumu' },
      buyerCustomer: { ...KAMU_BUYER_CUSTOMER },
      paymentMeans: { ...KAMU_PAYMENT_MEANS },
      lines: [{
        name: 'İhraç kayıtlı kamu tedarik', quantity: 10, price: 100, unitCode: 'Adet', kdvPercent: 0,
        delivery: {
          gtipNo: '620342000010', alicidibsatirkod: '12345678901',
          deliveryAddress: { address: 'Liman', district: 'Ambarlı', city: 'İstanbul', country: 'Türkiye' },
        },
      }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'KAMU', type: 'SGK',
    notes: 'Baseline — KAMU+SGK, SAGLIK_HAS',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: true, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['sgk', 'buyerCustomer', 'iban'],
    },
    input: {
      id: 'MTX2026000000035',
      uuid: 'a1000035-0001-4000-8001-000000000035',
      datetime: '2026-04-24T10:00:00',
      profile: 'KAMU', type: 'SGK', currencyCode: 'TRY',
      sgk: { type: 'SAGLIK_HAS', documentNo: 'SGK-HAS-MTX035', companyName: 'Matrix Hastane', companyCode: 'SGK-HAS-MTX' },
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER, taxNumber: '1460415308', name: 'Sosyal Güvenlik Kurumu' },
      buyerCustomer: { ...KAMU_BUYER_CUSTOMER },
      paymentMeans: { ...KAMU_PAYMENT_MEANS },
      lines: [{ name: 'Hastane tedavi', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 20 }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'KAMU', type: 'KOMISYONCU',
    notes: 'Baseline — KAMU+KOMISYONCU',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: true, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['buyerCustomer', 'iban'],
    },
    input: {
      id: 'MTX2026000000036',
      uuid: 'a1000036-0001-4000-8001-000000000036',
      datetime: '2026-04-24T10:00:00',
      profile: 'KAMU', type: 'KOMISYONCU', currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER, taxNumber: '1460415308', name: 'T.C. Kamu Kurumu' },
      buyerCustomer: { ...KAMU_BUYER_CUSTOMER },
      paymentMeans: { ...KAMU_PAYMENT_MEANS },
      lines: [{ name: 'Komisyon kamu', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 20 }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'KAMU', type: 'KONAKLAMAVERGISI',
    notes: 'Baseline — KAMU+KONAKLAMAVERGISI',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: true, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['buyerCustomer', 'iban'],
    },
    input: {
      id: 'MTX2026000000037',
      uuid: 'a1000037-0001-4000-8001-000000000037',
      datetime: '2026-04-24T10:00:00',
      profile: 'KAMU', type: 'KONAKLAMAVERGISI', currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER, taxNumber: '1460415308', name: 'T.C. Kamu Kurumu' },
      buyerCustomer: { ...KAMU_BUYER_CUSTOMER },
      paymentMeans: { ...KAMU_PAYMENT_MEANS },
      lines: [{ name: 'Konaklama — kamu görevlisi', quantity: 2, price: 500, unitCode: 'Gece', kdvPercent: 20 }],
    },
  },

  // ═════════════════════════════════════════════════════════════════════
  // EARSIVFATURA — 12 baseline (9 temel + 3 YTB)
  // Bug#1 nedeniyle TEVKIFATIADE / YTBTEVKIFATIADE atlandı
  // TEKNOLOJIDESTEK ayrıca atlandı (customer.TCKN + satırda TELEFON/TABLET_PC şartı)
  // ═════════════════════════════════════════════════════════════════════

  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'EARSIVFATURA', type: 'SATIS',
    notes: 'Baseline — EARSIVFATURA+SATIS',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000040',
      uuid: 'a1000040-0001-4000-8001-000000000040',
      datetime: '2026-04-24T10:00:00',
      profile: 'EARSIVFATURA', type: 'SATIS', currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'E-arşiv satış', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 20 }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'EARSIVFATURA', type: 'IADE',
    notes: 'Baseline — EARSIVFATURA+IADE, billingReference',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['billingReference'],
    },
    input: {
      id: 'MTX2026000000041',
      uuid: 'a1000041-0001-4000-8001-000000000041',
      datetime: '2026-04-24T10:00:00',
      profile: 'EARSIVFATURA', type: 'IADE', currencyCode: 'TRY',
      billingReference: { id: 'MTX2026000000040', issueDate: '2026-04-24' },
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'E-arşiv iade', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 20 }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'EARSIVFATURA', type: 'TEVKIFAT',
    notes: 'Baseline — EARSIVFATURA+TEVKIFAT',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: ['603'], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000042',
      uuid: 'a1000042-0001-4000-8001-000000000042',
      datetime: '2026-04-24T10:00:00',
      profile: 'EARSIVFATURA', type: 'TEVKIFAT', currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'E-arşiv tevkifat', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 20, withholdingTaxCode: '603' }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'EARSIVFATURA', type: 'ISTISNA',
    notes: 'Baseline — EARSIVFATURA+ISTISNA, kod 213',
    dimensions: {
      kdvBreakdown: [0], currency: 'TRY', exchangeRate: false, exemptionCodes: ['213'],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000043',
      uuid: 'a1000043-0001-4000-8001-000000000043',
      datetime: '2026-04-24T10:00:00',
      profile: 'EARSIVFATURA', type: 'ISTISNA', currencyCode: 'TRY',
      kdvExemptionCode: '213',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'E-arşiv istisna', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 0 }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'EARSIVFATURA', type: 'OZELMATRAH',
    notes: 'Baseline — EARSIVFATURA+OZELMATRAH',
    dimensions: {
      kdvBreakdown: [0], currency: 'TRY', exchangeRate: false, exemptionCodes: ['801'],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['ozelMatrah'],
    },
    input: {
      id: 'MTX2026000000044',
      uuid: 'a1000044-0001-4000-8001-000000000044',
      datetime: '2026-04-24T10:00:00',
      profile: 'EARSIVFATURA', type: 'OZELMATRAH', currencyCode: 'TRY',
      kdvExemptionCode: '801',
      ozelMatrah: { percent: 18, taxable: 500, amount: 90 },
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'E-arşiv özel matrah', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 0 }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'EARSIVFATURA', type: 'IHRACKAYITLI',
    notes: 'Baseline — EARSIVFATURA+IHRACKAYITLI',
    dimensions: {
      kdvBreakdown: [0], currency: 'TRY', exchangeRate: false, exemptionCodes: ['702'],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['gtip', 'alicidibkod'],
    },
    input: {
      id: 'MTX2026000000045',
      uuid: 'a1000045-0001-4000-8001-000000000045',
      datetime: '2026-04-24T10:00:00',
      profile: 'EARSIVFATURA', type: 'IHRACKAYITLI', currencyCode: 'TRY',
      kdvExemptionCode: '702',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{
        name: 'E-arşiv ihraç kayıtlı', quantity: 10, price: 100, unitCode: 'Adet', kdvPercent: 0,
        delivery: {
          gtipNo: '620342000010', alicidibsatirkod: '12345678901',
          deliveryAddress: { address: 'Liman', district: 'Ambarlı', city: 'İstanbul', country: 'Türkiye' },
        },
      }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'EARSIVFATURA', type: 'SGK',
    notes: 'Baseline — EARSIVFATURA+SGK, MAL_HIZMET',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['sgk'],
    },
    input: {
      id: 'MTX2026000000046',
      uuid: 'a1000046-0001-4000-8001-000000000046',
      datetime: '2026-04-24T10:00:00',
      profile: 'EARSIVFATURA', type: 'SGK', currencyCode: 'TRY',
      sgk: { type: 'MAL_HIZMET', documentNo: 'SGK-MAL-MTX046', companyName: 'Matrix Medikal Tedarik', companyCode: 'SGK-MAL-MTX' },
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'Medikal tedarik', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 20 }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'EARSIVFATURA', type: 'KOMISYONCU',
    notes: 'Baseline — EARSIVFATURA+KOMISYONCU',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000047',
      uuid: 'a1000047-0001-4000-8001-000000000047',
      datetime: '2026-04-24T10:00:00',
      profile: 'EARSIVFATURA', type: 'KOMISYONCU', currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'E-arşiv komisyon', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 20 }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'EARSIVFATURA', type: 'KONAKLAMAVERGISI',
    notes: 'Baseline — EARSIVFATURA+KONAKLAMAVERGISI',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000048',
      uuid: 'a1000048-0001-4000-8001-000000000048',
      datetime: '2026-04-24T10:00:00',
      profile: 'EARSIVFATURA', type: 'KONAKLAMAVERGISI', currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'Konaklama — e-arşiv', quantity: 2, price: 500, unitCode: 'Gece', kdvPercent: 20 }],
    },
  },

  // YTB tipleri (YATIRIMTESVIK kuralları geçerli) — ytbNo + itemClassificationCode zorunlu
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'EARSIVFATURA', type: 'YTBSATIS',
    notes: 'Baseline — EARSIVFATURA+YTBSATIS, ytbNo + kod 01 makine',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['ytbNo'],
    },
    input: {
      id: 'MTX2026000000049',
      uuid: 'a1000049-0001-4000-8001-000000000049',
      datetime: '2026-04-24T10:00:00',
      profile: 'EARSIVFATURA', type: 'YTBSATIS', currencyCode: 'TRY',
      ytbNo: '123456', ytbIssueDate: '2026-01-15',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{
        name: 'Teşvikli makine', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 20,
        itemClassificationCode: '01', productTraceId: 'MAKINA-MTX-049',
        serialId: 'SN-MTX-049', brand: 'Matrix', model: 'MTX-01',
      }],
    },
  },
  // EARSIVFATURA+YTBISTISNA — Phantom KDV (M12)! 308 (makine) veya 339 (inşaat)
  {
    kind: 'invoice', variantSlug: 'phantom-308-makine', profile: 'EARSIVFATURA', type: 'YTBISTISNA',
    notes: 'EARSIVFATURA+YTBISTISNA — Phantom KDV (M12): kod 308 + itemClassificationCode 01',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: ['308'],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: true,
      specialIdentifiers: ['ytbNo', 'phantom-kdv'],
    },
    input: {
      id: 'MTX2026000000050',
      uuid: 'a1000050-0001-4000-8001-000000000050',
      datetime: '2026-04-24T10:00:00',
      profile: 'EARSIVFATURA', type: 'YTBISTISNA', currencyCode: 'TRY',
      ytbNo: '123456', ytbIssueDate: '2026-01-15',
      kdvExemptionCode: '308',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{
        name: 'Teşvikli makine — phantom KDV', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 20,
        itemClassificationCode: '01', kdvExemptionCode: '308',
        productTraceId: 'MAKINA-MTX-050', serialId: 'SN-MTX-050', brand: 'Matrix', model: 'MTX-02',
      }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'phantom-339-insaat', profile: 'EARSIVFATURA', type: 'YTBISTISNA',
    notes: 'EARSIVFATURA+YTBISTISNA — Phantom KDV: kod 339 + itemClassificationCode 02 inşaat',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: ['339'],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: true,
      specialIdentifiers: ['ytbNo', 'phantom-kdv'],
    },
    input: {
      id: 'MTX2026000000051',
      uuid: 'a1000051-0001-4000-8001-000000000051',
      datetime: '2026-04-24T10:00:00',
      profile: 'EARSIVFATURA', type: 'YTBISTISNA', currencyCode: 'TRY',
      ytbNo: '123456', ytbIssueDate: '2026-01-15',
      kdvExemptionCode: '339',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{
        name: 'Teşvikli inşaat hizmeti', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 20,
        itemClassificationCode: '02', kdvExemptionCode: '339',
      }],
    },
  },

  // ═════════════════════════════════════════════════════════════════════
  // IHRACAT + YOLCUBERABERFATURA + OZELFATURA + HKS + ENERJI (8 baseline)
  // ═════════════════════════════════════════════════════════════════════

  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'IHRACAT', type: 'ISTISNA',
    notes: 'Baseline — IHRACAT+ISTISNA, USD döviz + buyerCustomer + delivery(FOB+GTİP)',
    dimensions: {
      kdvBreakdown: [0], currency: 'USD', exchangeRate: true, exemptionCodes: ['301'],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['buyerCustomer', 'gtip', 'incoterms'],
    },
    input: {
      id: 'MTX2026000000060',
      uuid: 'a1000060-0001-4000-8001-000000000060',
      datetime: '2026-04-24T10:00:00',
      profile: 'IHRACAT', type: 'ISTISNA', currencyCode: 'USD', exchangeRate: 32.5,
      kdvExemptionCode: '301',
      sender: { ...STANDARD_SENDER, name: 'Matrix İhracat A.Ş.' },
      customer: {
        taxNumber: '2222222222',
        name: 'Global Trade Holdings (Germany)',
        address: 'Bahnhofstraße 123',
        district: 'Munich', city: 'Bayern',
      },
      buyerCustomer: {
        name: 'Global Trade Holdings GmbH',
        taxNumber: 'DE123456789',
        address: 'Bahnhofstraße 123', district: 'Munich', city: 'Bayern', country: 'Germany',
      },
      lines: [{
        name: 'İhracat — tekstil', quantity: 100, price: 10, unitCode: 'Adet', kdvPercent: 0,
        delivery: {
          deliveryTermCode: 'FOB', gtipNo: '620342000010',
          deliveryAddress: { address: 'Ambarlı Liman', district: 'Avcılar', city: 'İstanbul', country: 'Türkiye' },
        },
      }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'YOLCUBERABERFATURA', type: 'ISTISNA',
    notes: 'Baseline — YOLCUBERABERFATURA+ISTISNA, passport + nationalityId + taxRepresentativeParty',
    dimensions: {
      kdvBreakdown: [0], currency: 'TRY', exchangeRate: false, exemptionCodes: ['322'],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['passport', 'nationalityId', 'taxRepresentative'],
    },
    input: {
      id: 'MTX2026000000061',
      uuid: 'a1000061-0001-4000-8001-000000000061',
      datetime: '2026-04-24T10:00:00',
      profile: 'YOLCUBERABERFATURA', type: 'ISTISNA', currencyCode: 'TRY',
      kdvExemptionCode: '322',
      sender: {
        taxNumber: '1460415308',
        name: 'Matrix Bavul Ticaret A.Ş.',
        taxOffice: 'Beyoğlu', address: 'İstiklal Cad. No:321',
        district: 'Beyoğlu', city: 'İstanbul',
      },
      customer: { ...STANDARD_CUSTOMER, name: 'Matrix Turizm Aracı A.Ş.' },
      buyerCustomer: {
        name: 'Michael Schneider (Tourist)',
        taxNumber: '99999999999',
        address: 'Hauptstrasse 15', district: 'Berlin', city: 'Berlin', country: 'Germany',
        nationalityId: 'DE', passportId: 'N12345678',
      },
      taxRepresentativeParty: {
        vknTckn: '9876543210',
        label: 'MATRIX_TAXFREE',
        name: 'Matrix KDV İade Aracı',
      },
      lines: [{ name: 'El yapımı seramik', quantity: 1, price: 800, unitCode: 'Adet', kdvPercent: 0 }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'OZELFATURA', type: 'ISTISNA',
    notes: 'Baseline — OZELFATURA+ISTISNA (genel istisna profili)',
    dimensions: {
      kdvBreakdown: [0], currency: 'TRY', exchangeRate: false, exemptionCodes: ['322'],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000062',
      uuid: 'a1000062-0001-4000-8001-000000000062',
      datetime: '2026-04-24T10:00:00',
      profile: 'OZELFATURA', type: 'ISTISNA', currencyCode: 'TRY',
      kdvExemptionCode: '322',
      sender: { ...STANDARD_SENDER },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'Özel fatura satır', quantity: 1, price: 1000, unitCode: 'Adet', kdvPercent: 0 }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'HKS', type: 'HKSSATIS',
    notes: 'Baseline — HKS+HKSSATIS, KUNYENO 19-char per line',
    dimensions: {
      kdvBreakdown: [10], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['kunyeno'],
    },
    input: {
      id: 'MTX2026000000063',
      uuid: 'a1000063-0001-4000-8001-000000000063',
      datetime: '2026-04-24T10:00:00',
      profile: 'HKS', type: 'HKSSATIS', currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER, name: 'Matrix Sebze Meyve Tic.', address: 'Hal Kompleksi Blok 5', district: 'Bayrampaşa' },
      customer: { ...STANDARD_CUSTOMER, name: 'Matrix Market Zinciri Ltd.' },
      lines: [{
        name: 'Domates — Standart', quantity: 500, price: 20, unitCode: 'KGM', kdvPercent: 10,
        additionalItemIdentifications: [{ schemeId: 'KUNYENO', value: 'KUN-2026-MTX63-DOM1' }],
      }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'HKS', type: 'HKSKOMISYONCU',
    notes: 'Baseline — HKS+HKSKOMISYONCU, komisyoncu satış',
    dimensions: {
      kdvBreakdown: [10], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: ['kunyeno'],
    },
    input: {
      id: 'MTX2026000000064',
      uuid: 'a1000064-0001-4000-8001-000000000064',
      datetime: '2026-04-24T10:00:00',
      profile: 'HKS', type: 'HKSKOMISYONCU', currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER, name: 'Matrix Komisyoncu Hal' },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{
        name: 'Biber — Komisyon satış', quantity: 200, price: 15, unitCode: 'KGM', kdvPercent: 10,
        additionalItemIdentifications: [{ schemeId: 'KUNYENO', value: 'KUN-2026-MTX64-BIB1' }],
      }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'ENERJI', type: 'SARJ',
    notes: 'Baseline — ENERJI+SARJ, araç şarj hizmeti',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000065',
      uuid: 'a1000065-0001-4000-8001-000000000065',
      datetime: '2026-04-24T10:00:00',
      profile: 'ENERJI', type: 'SARJ', currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER, name: 'Matrix Şarj Operatörü A.Ş.' },
      customer: { ...STANDARD_CUSTOMER, taxNumber: '12345678901', name: 'Matrix Araç Sürücüsü' },
      lines: [{ name: 'EV DC Hızlı Şarj 45 kWh', quantity: 45, price: 8, unitCode: 'KWH', kdvPercent: 20 }],
    },
  },
  {
    kind: 'invoice', variantSlug: 'baseline', profile: 'ENERJI', type: 'SARJANLIK',
    notes: 'Baseline — ENERJI+SARJANLIK, operatörden anlık satış',
    dimensions: {
      kdvBreakdown: [20], currency: 'TRY', exchangeRate: false, exemptionCodes: [],
      withholdingCodes: [], allowanceCharge: { line: false, document: false },
      lineCount: 1, paymentMeans: false, reducedKdvGate: false, phantomKdv: false,
      specialIdentifiers: [],
    },
    input: {
      id: 'MTX2026000000066',
      uuid: 'a1000066-0001-4000-8001-000000000066',
      datetime: '2026-04-24T10:00:00',
      profile: 'ENERJI', type: 'SARJANLIK', currencyCode: 'TRY',
      sender: { ...STANDARD_SENDER, name: 'Matrix Şarj Operatörü A.Ş.' },
      customer: { ...STANDARD_CUSTOMER },
      lines: [{ name: 'EV AC şarj anlık', quantity: 20, price: 5, unitCode: 'KWH', kdvPercent: 20 }],
    },
  },
];

export const invalidSpecs: InvalidSpec[] = [
  // (Sprint 8e.10-8e.13'te doldurulacak)
];

export const allSpecs: Array<ValidSpec | InvalidSpec> = [
  ...validSpecs,
  ...invalidSpecs,
];
